---
permalink: cloud-connector/backup-intro-concept.html 
sidebar: sidebar 
keywords: Cloud Connector backup 
summary: 您可以访问 SANtricity 云连接器应用程序左侧导航面板中的备份选项。备份选项将显示备份页面，在此可以创建新的基于映像或基于文件的备份作业。 
---
= 备份
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以访问 SANtricity 云连接器应用程序左侧导航面板中的备份选项。备份选项将显示备份页面，在此可以创建新的基于映像或基于文件的备份作业。

使用 SANtricity 云连接器应用程序的 * 备份 * 页面创建和处理 E 系列卷的备份。您可以创建基于映像或基于文件的备份，然后立即或稍后执行这些操作。此外，您还可以根据上次执行的完整备份选择执行完整备份或增量备份。根据上次通过 SANtricity 云连接器应用程序执行的完整备份，最多可以执行六个增量备份。


NOTE: SANtricity 云连接器应用程序下列出的备份和还原作业的所有时间戳均使用本地时间。



== 创建新的基于映像的备份

您可以通过 SANtricity 云连接器应用程序的备份页面上的创建功能创建新的基于映像的备份。

确保已将 Web 服务代理中的存储阵列注册到 SANtricity 云连接器。

.步骤
. 在备份页面中，单击 * 创建 * 。
+
此时将显示创建备份窗口。

. 选择 * 创建基于映像的备份 * 。
. 单击 * 下一步 * 。
+
此时将在创建备份窗口中显示可用 E 系列卷的列表。

. 选择所需的 E 系列卷并单击 * 下一步 * 。
+
此时将显示创建备份确认窗口的 * 为备份命名并提供问题描述 * 页面。

. 要修改自动生成的备份名称，请在 * 作业名称 * 字段中输入所需名称。
. 如果需要，请在 * 作业问题描述 * 字段中为备份添加问题描述。
+

NOTE: 您应输入作业问题描述，以便于识别备份的内容。

. 单击 * 下一步 * 。
+
创建备份窗口的 * 查看备份信息 * 页面将显示选定基于映像的备份的摘要。

. 查看选定备份，然后单击 * 完成 * 。
+
此时将显示创建备份窗口的确认页面。

. 选择以下选项之一：
+
** * 是 * —为选定备份启动完整备份。
** * 否 * - 不会对选定基于映像的备份执行完整备份。
+

NOTE: 可以稍后通过备份页面上的运行功能为选定的基于映像的备份执行完整备份。



. 单击 * 确定 * 。
+
此时将启动选定 E 系列卷的备份，此任务的状态将显示在备份页面的结果列表部分下。





== 创建新的基于文件夹 / 文件的备份

您可以通过 SANtricity 云连接器应用程序的备份页面上的创建功能创建基于文件夹 / 文件的新备份。

确保已将 Web 服务代理中的存储阵列注册到 SANtricity 云连接器。

基于文件的备份会无条件备份您指定的文件系统上的所有文件。但是，您可以选择性地还原文件和文件夹。

.步骤
. 在备份页面中，单击 * 创建 * 。
+
此时将显示创建备份窗口。

. 选择 * 创建文件夹 / 基于文件的备份 * 。
. 单击 * 下一步 * 。
+
创建备份窗口中会显示包含可供备份的文件系统的卷列表。

. 选择所需的卷并单击 * 下一步 * 。
+
创建备份窗口将显示选定卷上可用文件系统的列表。

+

NOTE: 如果未显示您的文件系统，请验证 SANtricity 云连接器应用程序是否支持您的文件系统类型。有关详细信息，请参见 link:learn-intro-concept.html#supported-file-systems["支持的文件系统"]。

. 选择包含要备份的文件夹或文件的所需文件系统，然后单击 * 下一步 * 。
+
此时将显示创建备份确认窗口的 * 为备份命名并提供问题描述 * 页面。

. 要修改自动生成的备份名称，请在 * 作业名称 * 字段中输入所需名称。
. 如果需要，请在 * 作业问题描述 * 字段中为备份添加问题描述。
+

NOTE: 您应输入作业问题描述，以便于识别备份的内容。

. 单击 * 下一步 * 。
+
创建备份窗口的 * 查看备份信息 * 页面将显示选定文件夹 / 基于文件的备份的摘要。

. 查看选定的基于文件夹 / 文件的备份，然后单击 * 完成 * 。
+
此时将显示创建备份窗口的确认页面。

. 选择以下选项之一：
+
** * 是 * —为选定备份启动完整备份。
** * 否 * —不对选定备份执行完整备份。
+

NOTE: 也可以稍后通过备份页面上的运行功能为选定的基于文件的备份执行完整备份。



. 单击 * 关闭 * 。
+
此时将启动选定 E 系列卷的备份，此任务的状态将显示在备份页面的结果列表部分下。





== 运行完整备份和增量备份

您可以通过备份页面上的运行功能执行完整备份和增量备份。增量备份仅适用于基于文件的备份。

确保您已通过 SANtricity 云连接器创建备份作业。

.步骤
. 在备份选项卡中，选择所需的备份作业，然后单击 * 运行 * 。
+

NOTE: 只要选择了基于映像的备份作业或未执行先前初始备份的备份作业，就会自动执行完整备份。

+
此时将显示 Run Backup 窗口。

. 选择以下选项之一：
+
** * 完整 * —备份选定基于文件的备份的所有数据。
** * 增量 * —仅备份自上次执行备份以来所做的更改。
+

NOTE: 根据通过 SANtricity 云连接器应用程序执行的最后一次完整备份，最多可以执行六个增量备份。



. 单击 * 运行 * 。
+
备份请求已启动。





== 删除备份作业

删除功能将删除选定备份的指定目标位置的备份数据以及备份集。

确保备份的状态为已完成，失败或已取消。

.步骤
. 在备份页面中，选择所需的备份，然后单击 * 删除 * 。
+

NOTE: 如果选择删除完整基础备份，则所有关联的增量备份也会被删除。

+
此时将显示确认删除窗口。

. 在 * 键入 delete* 字段中，键入 `Delete` 确认删除操作。
. 单击 * 删除 * 。
+
选定备份将被删除。


