---
permalink: cloud-connector/config-intro-concept.html 
sidebar: sidebar 
keywords: Cloud Connector configuration 
summary: 成功安装后，您可以通过配置向导设置 SANtricity 云连接器应用程序。首次登录到 SANtricity 云连接器后，将显示配置向导。 
---
= 首次配置 SANtricity 云连接器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
成功安装后，您可以通过配置向导设置 SANtricity 云连接器应用程序。首次登录到 SANtricity 云连接器后，将显示配置向导。



== 首次登录到 SANtricity 云连接器

首次初始化 SANtricity 云连接器时，必须输入默认密码才能访问此应用程序。

.开始之前
确保您有权访问连接到 Internet 的浏览器。

.步骤
. 打开支持的浏览器。
. 连接到已配置的 SANtricity 云连接器服务器（例如， ` +http://localhost:8080/+` ）。
+
此时将显示 SANtricity 云连接器应用程序的初始登录页面。

. 在管理员密码字段中，输入默认密码 `password` 。
. 单击 * 登录 * 。
+
此时将显示 SANtricity 云连接器配置向导。





== 使用配置向导

成功初始登录到 SANtricity 云连接器后，将显示配置向导。

通过配置向导，您可以为 SANtricity 云连接器设置管理员密码， Web 服务代理登录管理凭据，所需的备份目标类型以及加密密码短语。



=== 第 1 步：设置管理员密码

您可以通过设置管理员密码页面自定义用于后续登录到 SANtricity 云连接器的密码。

通过 " 设置管理员密码 " 页面创建密码可以有效地替代 SANtricity Cloud Connector 应用程序首次登录时使用的默认密码。

.步骤
. 在设置管理员密码页面的 * 输入新管理员密码 * 字段中输入 SANtricity 云连接器所需的登录密码。
. 在 * 重新输入新管理员密码 * 字段中，从第一个字段重新输入密码。
. 单击 * 下一步 * 。
+
此时将接受 SANtricity 云连接器的密码设置，并在配置向导下显示设置密码短语页面。

+

NOTE: 完成配置向导后，才会设置用户定义的管理员密码。





=== 第 2 步：设置密码短语

在输入加密密码短语页面下，您可以指定一个介于 8 到 32 个字符之间的字母数字密码短语。

在 SANtricity 云连接器应用程序使用的数据加密密钥中，需要使用用户指定的密码短语。

.步骤
. 在 * 定义密码短语 * 字段中，输入所需的密码短语。
. 在 * 重新输入密码短语 * 字段中，重新输入第一个字段中的密码短语。
. 单击 * 下一步 * 。
+
系统将接受为 SANtricity 云连接器应用程序输入的密码短语，并显示配置向导的选择目标类型页面。





=== 第 3 步：选择目标类型

通过 SANtricity 云连接器，可以为 Amazon S3 ， AltaVault 和 StorageGRID 目标类型提供备份和还原功能。您可以在 " 选择目标类型 " 页面下为 SANtricity 云连接器应用程序指定所需的存储目标类型。

.开始之前
请确保您拥有以下选项之一： AltaVault 挂载点， Amazon AWS 帐户或 StorageGRID 帐户。

.步骤
. 在下拉菜单中，选择以下选项之一：
+
** Amazon AWS
** AltaVault
** StorageGRID
+
此时将在配置向导中显示选定选项的目标类型页面。



. 请参见适用于 AltaVault ， Amazon AWS 或 StorageGRID 的相应配置说明。




==== 配置 AltaVault 设备

在选择目标类型页面下选择 AltaVault 设备选项后，将显示 AltaVault 目标类型的配置选项。

.开始之前
* 您具有 AltaVault 设备的 NFS 挂载路径。
* 您已将 AltaVault 设备指定为目标类型。


.步骤
. 在 * NFS 挂载路径 * 字段中，输入 AltaVault 目标类型的挂载点。
+

NOTE: "* NFS 挂载路径 * " 字段中的值必须采用 Linux 路径格式。

. 选中 * 在此目标上保存配置数据库的备份 * 复选框，以便在选定目标类型上创建配置数据库的备份。
+

NOTE: 如果在测试连接时检测到指定目标类型上的现有数据库配置，您可以选择将 SANtricity 云连接器主机上的现有数据库配置信息替换为在配置向导中输入的新备份信息。

. 单击 * 测试连接 * 以测试指定 AltaVault 设置的连接。
. 单击 * 下一步 * 。
+
接受为 SANtricity 云连接器指定的目标类型，并在配置向导中显示 Web 服务代理页面。

. 继续执行 " 步骤 4 ：连接到 Web 服务代理 " 。




==== 配置 Amazon AWS 帐户

在选择目标类型页面下选择 Amazon AWS 选项后，将显示 Amazon AWS 目标类型的配置选项。

.开始之前
* 您已建立 Amazon AWS 帐户。
* 您已指定 Amazon AWS 作为目标类型。


.步骤
. 在 * 访问密钥 ID* 字段中，输入 Amazon AWS 目标的访问 ID 。
. 在 * 机密访问密钥 * 字段中，输入目标的机密访问密钥。
. 在 * 分段名称 * 字段中，输入目标的分段名称。
. 选中 * 在此目标上保存配置数据库的备份 * 复选框可在选定目标类型上创建配置数据库的备份。
+

NOTE: 建议启用此设置，以确保在数据库丢失时可以还原备份目标中的数据。

+

NOTE: 如果在测试连接时检测到指定目标类型上的现有数据库配置，您可以选择将 SANtricity 云连接器主机上的现有数据库配置信息替换为在配置向导中输入的新备份信息。

. 单击 * 测试连接 * 以验证输入的 Amazon AWS 凭据。
. 单击 * 下一步 * 。
+
接受为 SANtricity 云连接器指定的目标类型，并在配置向导下显示 Web 服务代理页面。

. 继续执行 " 步骤 4 ：连接到 Web 服务代理 " 。




==== 配置 StorageGRID 帐户

在选择目标类型页面下选择 StorageGRID 选项后，将显示 StorageGRID 目标类型的配置选项。

.开始之前
* 您已建立 StorageGRID 帐户。
* 您在 SANtricity 云连接器密钥库中拥有一个签名的 StorageGRID 证书。
* 您已指定 StorageGRID 作为目标类型。


.步骤
. 在 * URL * 字段中，输入 Amazon S3 云服务的 URL
. 在 * 访问密钥 ID* 字段中，输入 S3 目标的访问 ID 。
. 在 * 机密访问密钥 * 字段中，输入 S3 目标的机密访问密钥。
. 在 * 分段名称 * 字段中，输入 S3 目标的分段名称。
. 要使用路径模式访问，请选中 * 使用路径模式访问 * 复选框。
+

NOTE: 如果未选中，则会使用虚拟主机模式访问。

. 选中 * 在此目标上保存配置数据库的备份 * 复选框可在选定目标类型上创建配置数据库的备份。
+

NOTE: 建议启用此设置，以确保在数据库丢失时可以还原备份目标中的数据。

+

NOTE: 如果在测试连接时检测到指定目标类型上的现有数据库配置，您可以选择将 SANtricity 云连接器主机上的现有数据库配置信息替换为在配置向导中输入的新备份信息。

. 单击 * 测试连接 * 以验证输入的 S3 凭据。
+

NOTE: 某些符合 S3 的帐户可能需要安全的 HTTP 连接。有关在密钥库中放置 StorageGRID 证书的信息，请参见 link:install-intro-concept.html#add-storagegrid-certificate-into-a-keystore["将 StorageGRID 证书添加到密钥库中"]。

. 单击 * 下一步 * 。
+
接受为 SANtricity 云连接器指定的目标类型，并在配置向导下显示 Web 服务代理页面。

. 继续执行 " 步骤 4 ：连接到 Web 服务代理 " 。




=== 第 4 步：连接到 Web 服务代理

与 SANtricity 云连接器结合使用的 Web 服务代理的登录和连接信息可通过输入 Web 服务代理 URL 和凭据页面输入。

.开始之前
确保已与 SANtricity Web 服务代理建立连接。

.步骤
. 在 * URL * 字段中，输入用于 SANtricity 云连接器的 Web 服务代理的 URL 。
. 在 * 用户名 * 字段中，输入 Web 服务代理连接的用户名。
. 在 * 密码 * 字段中，输入 Web 服务代理连接的密码。
. 单击 * 测试连接 * 以验证所输入 Web 服务代理凭据的连接。
. 通过测试连接验证输入的 Web 服务代理凭据后。
. 单击 * 下一步 *
+
此时将接受 SANtricity 云连接器的 Web 服务代理凭据，并在配置向导中显示选择存储阵列页面。





=== 第 5 步：选择存储阵列

根据通过配置向导输入的 SANtricity Web 服务代理凭据，选择存储阵列页面下将显示可用存储阵列的列表。通过此页面，您可以选择 SANtricity 云连接器用于备份和还原作业的存储阵列。

.开始之前
确保已为 SANtricity Web 服务代理应用程序配置存储阵列。


NOTE: SANtricity 云连接器应用程序检测到无法访问的存储阵列会导致日志文件中出现 API 异常。这是 SANtricity Cloud Connector 应用程序在从无法访问的阵列中提取卷列表时的预期行为。为了避免日志文件中出现这些 API 异常，您可以直接使用存储阵列解析根问题描述，或者从 SANtricity Web 服务代理应用程序中删除受影响的存储阵列。

.步骤
. 选中要分配给 SANtricity 云连接器应用程序以执行备份和还原操作的存储阵列旁边的每个复选框。
. 单击 * 下一步 * 。
+
此时将接受选定存储阵列，并在配置向导中显示选择主机页面。

+

NOTE: 您必须为在选择存储阵列页面下选择的任何存储阵列配置有效密码。您可以通过 SANtricity Web 服务代理 API 文档配置存储阵列密码。





=== 第 6 步：选择主机

根据通过配置向导选择的 Web 服务代理托管的存储阵列，您可以通过选择主机页面选择一个可用主机，以便将备份和还原候选卷映射到 SANtricity 云连接器应用程序。

.开始之前
确保您有一个可通过 SANtricity Web 服务代理访问的主机。

.步骤
. 在列出的存储阵列的下拉菜单中，选择所需主机。
. 对 Select Host 页面下列出的任何其他存储阵列重复步骤 1 。
. 单击 * 下一步 * 。
+
此时将接受为 SANtricity 云连接器选择的主机，并在配置向导中显示 " 查看 " 页面。





=== 第 7 步：查看初始配置

SANtricity 云连接器配置向导的最后一页提供了输入结果的摘要，供您查看。

查看经验证的配置数据的结果。

* 如果所有配置数据均已成功验证和建立，请单击 * 完成 * 以完成配置过程。
* 如果无法验证配置数据的任何部分，请单击 * 返回 * 导航到配置向导的适用页面以修改提交的数据。

