---
permalink: cloud-connector/restore-intro-concept.html 
sidebar: sidebar 
keywords: Cloud Connector restore, 
summary: '您可以访问 SANtricity 云连接器应用程序左侧导航面板中的还原选项。"Restore" 选项将显示 "Restore" 页面，在此可以创建新的基于映像或基于文件的还原作业。' 
---
= 还原
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以访问 SANtricity 云连接器应用程序左侧导航面板中的还原选项。"Restore" 选项将显示 "Restore" 页面，在此可以创建新的基于映像或基于文件的还原作业。

SANtricity 云连接器使用作业概念执行 E 系列卷的实际还原。在执行还原之前，您必须确定要用于此操作的 E 系列卷。将要还原的 E 系列卷添加到 SANtricity 云连接器主机后，您可以使用 SANtricity 云连接器应用程序的 `还原` 页面创建和处理还原。


NOTE: SANtricity 云连接器应用程序下列出的备份和还原作业的所有时间戳均使用本地时间。



== 创建新的基于映像的还原

您可以通过 SANtricity 云连接器应用程序的 " 还原 " 页面上的 " 创建 " 功能创建新的基于映像的还原。

确保您可以通过 SANtricity 云连接器使用基于映像的备份。

.步骤
. 在 SANtricity 云连接器应用程序的还原页面中，单击 * 创建 * 。
+
此时将显示还原窗口。

. 选择所需的备份。
. 单击 * 下一步 * 。
+
此时将在还原窗口中显示选择备份点页面。

. 选择所需的已完成备份。
. 单击 * 下一步 * 。
+
此时将在还原窗口中显示选择还原目标页面。

. 选择还原卷并单击 * 下一步 * 。
+
此时将在还原窗口中显示 Review 页面。

. 查看选定的还原操作，然后单击 * 完成 * 。
+
此时将启动对选定目标主机卷的还原，此任务的状态将显示在还原页面的结果列表部分中。





== 创建新的基于文件的还原

您可以通过 SANtricity 云连接器应用程序的 " 还原 " 页面中的 " 创建 " 功能创建新的基于文件的还原。

确保您可以通过 SANtricity 云连接器使用基于文件的备份。

.步骤
. 在 SANtricity 云连接器应用程序的还原页面中，单击 * 创建 * 。
+
此时将显示还原窗口。

. 在还原窗口中，选择所需的基于文件的备份。
. 单击 * 下一步 * 。
+
此时将在创建还原作业窗口中显示选择备份点页面。

. 在选择备份点页面中，选择所需的已完成备份。
. 单击 * 下一步 * 。
+
此时将在还原窗口中显示可用文件系统或文件夹 / 文件页面的列表。

. 选择要还原的所需文件夹或文件，然后单击 * 下一步 * 。
+
此时将在还原窗口中显示选择还原目标页面。

. 选择还原卷并单击 * 下一步 * 。
+
此时将在还原窗口中显示 Review 页面。

. 查看选定的还原操作，然后单击 * 完成 * 。
+
此时将启动对选定目标主机卷的还原，此任务的状态将显示在还原页面的结果列表部分中。





== 删除还原

您可以使用删除功能从还原页面的结果列表部分中删除选定还原项。

确保存在状态为已完成，失败或已取消的还原作业。

.步骤
. 在还原页面中，单击 * 删除 * 。
+
此时将显示确认删除窗口。

. 在 * 键入 delete* 字段中，键入 `delete` 确认删除操作。
. 单击 * 删除 * 。
+

NOTE: 您不能删除已暂停的还原。

+
选定还原将被删除。


