---
permalink: config-linux/iscsi-install-smcli-11-53-task.html 
sidebar: sidebar 
keywords: install Storage Manager Linux, install CLI Windows, install command line interface, install Host Context Agent, install HCA, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 使用 Linux 快速方法安装适用于 CLI 和 HCA 的 Storage Manager 。 
---
= 安装适用于 SMCLI 的 SANtricity 存储管理器（ SANtricity 软件 11.53 或更早版本）
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用的是 SANtricity 软件 11.53 或更早版本，则可以在管理工作站上安装 SANtricity 存储管理器软件，以帮助管理阵列。

SANtricity 存储管理器包括用于执行其他管理任务的命令行界面（ CLI ）以及用于通过 I/O 路径将主机配置信息推送到存储阵列控制器的主机上下文代理。


NOTE: 如果您使用的是 SANtricity 软件 11.60 及更高版本，则无需执行以下步骤。SANtricity 安全命令行界面（ SMcli ）包含在 SANtricity 操作系统中，可通过 SANtricity 系统管理器下载。有关如何通过SANtricity系统管理器下载SMcli的详细信息、请参阅 link:https://docs.netapp.com/us-en/e-series-santricity/sm-settings/download-cli.html["下载SANtricity系统管理器联机帮助下的命令行界面(CLI)主题"^]


NOTE: 从SANtricity软件11.80.1版开始、不再支持主机上下文代理。

.开始之前
确保您已具备以下条件：

* SANtricity 软件 11.53 或更早版本。
* 正确的管理员或超级用户权限。
* SANtricity 存储管理器客户端的系统，最低要求如下：
+
** * RAM * ： 2 GB 用于 Java Runtime Engine
** * 磁盘空间 * ： 5 GB
** * 操作系统 / 架构 * ：有关确定支持的操作系统版本和架构的指导，请访问 http://mysupport.netapp.com["NetApp 支持"^]。从 * 下载 * 选项卡中，转到菜单：下载 [E 系列 SANtricity 存储管理器 ] 。




.关于此任务
此任务介绍如何在 Windows 和 Linux 操作系统平台上安装 SANtricity 存储管理器，因为在数据主机使用 Linux 时， Windows 和 Linux 都是通用的管理工作站平台。

.步骤
. 从下载 SANtricity 软件版本 http://mysupport.netapp.com["NetApp 支持"^]。从 * 下载 * 选项卡中，转到菜单：下载 [E 系列 SANtricity 存储管理器 ] 。
. 运行 SANtricity 安装程序。
+
|===
| Windows | Linux 


 a| 
双击 SMIA* 。 exe 安装包以开始安装。
 a| 
.. 转到 SMIA* .bin 安装包所在的目录。
.. 如果临时挂载点没有执行权限，请设置 `IATEMPDIR` 变量。示例： `IATEMPDIR=/root ./AMI-LINUXX64-11.25.0A00.0002.bin`
.. 运行 `chmod +x sMIA* .bin` 命令为文件授予执行权限。
.. 运行 ` ./SMIA* .bin` 命令启动安装程序。


|===
. 使用安装向导在管理工作站上安装软件。

