---
permalink: config-linux/iser-ib-configure-multipath-software-task.html 
sidebar: sidebar 
keywords: multipath software for Linux, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 配置多路径软件，以便在其中一个物理路径中断时为存储阵列提供冗余路径。 
---
= 在E系列- Linux中配置多路径软件(基于InfiniBand的iSER)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要为存储阵列提供冗余路径，您可以配置多路径软件。

.开始之前
您必须在系统上安装所需的软件包。

* 对于 Red Hat （ RHEL ）主机，运行 `rpm -q device-mapper-multipath` 验证软件包是否已安装。
* 对于 SLES 主机，请运行 `rpm -q multipath-tools` 来验证软件包是否已安装。


如果尚未安装操作系统，请使用操作系统供应商提供的介质。

.关于此任务
如果某个物理路径中断，多路径软件可提供指向存储阵列的冗余路径。多路径软件为操作系统提供一个虚拟设备，该虚拟设备表示存储的活动物理路径。多路径软件还可管理更新虚拟设备的故障转移过程。

您可以在 Linux 安装中使用设备映射程序多路径（ DM-MP ）工具。默认情况下，在 RHEL 和 SLES 中禁用 DM-MP 。要在主机上启用 DM-MP 组件，请完成以下步骤。

.步骤
. 如果尚未创建 multipath.conf 文件，请运行 ` # touch /etc/multipath.conf` 命令。
. 使用默认多路径设置，将 multipath.conf 文件留空。
. 启动多路径服务。
+
[listing]
----
# systemctl start multipathd
----
. 运行 `uname -r` 命令以保存内核版本。
+
[listing]
----
# uname -r
3.10.0-327.el7.x86_64
----
+
在向主机分配卷时，您将使用此信息。

. 在启动时启用multipathd守护进程。
+
[listing]
----
systemctl enable multipathd
----
. 在 /boot 目录下重建 `initramfs` 映像或 `initrd` 映像：
+
[listing]
----
dracut --force --add multipath
----
. 确保在启动配置文件中选择了新创建的 /boot/initrams-* 映像或 /boot/initrd-* 映像。
+
例如，对于 grub ，它为 ` /boot/grub/menu.lst` ；对于 grub2 ，它为 ` /boot/grub2/menu.cfg` 。

. 使用 https://docs.netapp.com/us-en/e-series-santricity/sm-storage/create-host-manually.html["手动创建主机"] 在联机帮助中使用操作步骤 检查是否已定义主机。验证每个主机类型设置是否基于中收集的内核信息 <<step4,第4步>>。



NOTE: 对于映射到运行内核3.9或更早版本的主机的任何卷、将禁用自动负载平衡。

. 重新启动主机。

