---
permalink: config-linux/nvme-fc-setup-failover-host-task.html 
sidebar: sidebar 
keywords: failover, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 将主机配置为运行故障转移。 
---
= 在E系列- Linux (基于FC的NVMe)中的主机上设置故障转移
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要为存储阵列提供冗余路径，您可以将主机配置为运行故障转移。

.开始之前
您必须在系统上安装所需的软件包。

* 对于 Red Hat （ RHEL ）主机，运行 `rpm -q device-mapper-multipath` 验证软件包是否已安装
* 对于 SLES 主机，请运行 `rpm -q multipath-tools` 来验证软件包是否已安装


 SLES 12 use Device Mapper Multipath (DMMP) for multipathing when using NVMe over Fibre Channel. RHEL 8, RHEL 9, and SLES 15 use a built-in Native NVMe Failover. Depending on which OS you are running, some additional configuration of multipath is required to get it running properly.


== 为 SLES 12 启用设备映射器多路径 (DMMP)

默认情况下，SLES 中禁用 DM-MP。完成以下步骤以在主机上启用 DM-MP 组件。

.步骤
. 将 NVMe E 系列设备条目添加到 /etc/multipath.conf 文件的 devices 部分，如以下示例所示：
+
[listing]
----

devices {
        device {
                vendor "NVME"
                product "NetApp E-Series*"
                path_grouping_policy group_by_prio
                failback immediate
                no_path_retry 30
        }
}
----
. 将 `multipathd` 配置为在系统启动时启动。
+
[listing]
----
# systemctl enable multipathd
----
. 如果当前未运行，请启动 `multipathd` 。
+
[listing]
----
# systemctl start multipathd
----
. 验证 `multipathd` 的状态，以确保其处于活动状态且正在运行：
+
[listing]
----
# systemctl status multipathd
----




== 为RHEL 8设置原生 NVMe多路径

.关于此任务
默认情况下，原生 NVMe 多路径在 RHEL 8 中处于禁用状态，必须使用以下步骤启用。

.步骤
. 设置 `modprobe` 规则以启用原生 NVMe 多路径。
+
[listing]
----
# echo "options nvme_core multipath=y" >> /etc/modprobe.d/50-nvme_core.conf
----
. 使用新的 modprobe 参数 remake `initramfs` 。
+
[listing]
----
# dracut -f
----
. 重新启动服务器以在启用原生 NVMe 多路径的情况下启动它
+
[listing]
----
# reboot
----
. 确认主机重新启动后已启用原生 NVMe 多路径。
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
----
+
.. 如果命令输出为 `N` ，则原生 NVMe 多路径仍处于禁用状态。
.. 如果命令输出为 `Y` ，则原生 NVMe 多路径将处于启用状态，您发现的任何 NVMe 设备将使用该功能。





NOTE: 对于RHEL 9和SLES 15、原生 NVMe多路径默认处于启用状态、不需要其他配置。
