---
permalink: config-linux/nvme-roce-verify-linux-config-support-task.html 
sidebar: sidebar 
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 为了确保操作可靠，您需要创建一个实施计划，然后使用 NetApp 互操作性表工具（ IMT ）验证是否支持整个配置。 
---
= 验证 Linux 支持并查看限制
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
首先，您应验证 Linux 配置是否受支持，并查看控制器，交换机，主机和恢复限制。



== 验证是否支持 Linux 配置

为了确保操作可靠，您需要创建一个实施计划，然后使用 NetApp 互操作性表工具（ IMT ）验证是否支持整个配置。

.步骤
. 转至 https://mysupport.netapp.com/matrix["NetApp 互操作性表工具"^]。
. 单击 * 解决方案 Search* 图块。
. 在菜单：协议 [SAN 主机 ] 区域中，单击 * E 系列 SAN 主机 * 旁边的 * 添加 * 按钮。
. 单击 * 查看细化搜索条件 * 。
+
此时将显示细化搜索条件部分。在本节中，您可以选择适用的协议以及其他配置标准，例如操作系统， NetApp 操作系统和主机多路径驱动程序。

. 选择您知道配置所需的条件，然后查看适用的兼容配置要素。
. 根据需要，根据工具中的规定更新操作系统和协议。
+
单击右页面箭头可在查看支持的配置页面上访问选定配置的详细信息。





== 验证基于 RoCE 的 NVMe 限制

在使用基于 RoCE 的 NVMe 之前，请查看控制器，交换机，主机和恢复限制。有关所有限制的最新列表，请参见 https://mysupport.netapp.com/matrix["NetApp 互操作性表工具"^]。



=== 控制器限制

* 可以为 EF300 （仅限 100 GB 控制器）， EF600 ， EF570 和 E5700 控制器配置基于 RoCE 的 NVMe 。控制器必须具有 100 GB 或 200 GB 主机端口。
* 此协议只能用于 EF300 ， EF600 ， EF570 和 E5700 控制器。要在 EF600 ， EF570 和 E5700 控制器上使用协议，至少需要 32 GB 的物理内存。对于 EF300 ，至少需要 16 GB 的物理内存。如果在每天开始操作期间不满足控制器的最低内存要求，则会显示一条消息，帮助您诊断问题。
* 不支持单工（单控制器）配置。
* 唯一支持的主机接口卡（ HIC ）是 100G 或 200G EDR HIC ，它还支持基于 InfiniBand 的 NVMe ， iSER 和 SRP 。
* 不支持将基于 RoCE 的 NVMe 与基于 InfiniBand 的 NVMe 或 SCSI 主机接口混合使用。




=== 交换机限制


NOTE: * 数据丢失风险。 * 您必须在交换机上启用优先级流量控制或全局暂停控制，以消除基于 RoCE 的 NVMe 环境中的数据丢失风险。



=== 主机，主机协议和主机操作系统限制

有关完整的要求列表，请参见 https://mysupport.netapp.com/matrix["NetApp 互操作性表工具"^]。



=== 存储和灾难恢复限制

* 不支持异步和同步镜像。
* 不支持精简配置（创建精简卷）。

