---
permalink: config-linux/nvme-fc-define-host-task.html 
sidebar: sidebar 
keywords: define host Linux, configure host linux, express linux configuration, linux host, 
summary: 您可以使用 SANtricity 系统管理器定义向存储阵列发送数据的主机。定义主机是让存储阵列知道连接了哪些主机并允许对卷进行 I/O 访问所需的步骤之一。 
---
= 使用SANtricity系统管理器创建主机—Linux (基于FC的NVMe)
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 SANtricity 系统管理器定义向存储阵列发送数据的主机。定义主机是让存储阵列知道连接了哪些主机并允许对卷进行 I/O 访问所需的步骤之一。

.关于此任务
定义主机时，请牢记以下准则：

* 您必须定义与主机关联的主机标识符端口。
* 请确保提供与主机分配的系统名称相同的名称。
* 如果您选择的名称已在使用中，则此操作不会成功。
* 名称长度不能超过 30 个字符。


.步骤
. 选择菜单： Storage[Hosts] 。
. 单击菜单：创建 [ 主机 ] 。
+
此时将显示创建主机对话框。

. 根据需要选择主机设置。
+
|===
| 正在设置 ... | Description 


 a| 
Name
 a| 
键入新主机的名称。



 a| 
主机操作系统类型
 a| 
从下拉列表中选择以下选项之一：

** 适用于 SANtricity 11.60 及更高版本的 * Linux *
** 对于 SANtricity 11.60 之前的版本， * Linux DM-MP （内核 3.10 或更高版本） *




 a| 
主机接口类型
 a| 
选择要使用的主机接口类型。如果您配置的阵列只有一个可用的主机接口类型，则可能无法选择此设置。



 a| 
主机端口
 a| 
执行以下操作之一：

** * 选择 I/O 接口 *
+
如果主机端口已登录，则可以从列表中选择主机端口标识符。这是建议的方法。

** * 手动添加 *
+
如果主机端口尚未登录，请查看主机上的 /etc/nve/hostnqn 以查找 hostnqn 标识符并将其与主机定义关联。

+
您可以手动输入主机端口标识符，或者将它们从 /etc/nve/hostnqn 文件（一次一个）复制 / 粘贴到 * 主机端口 * 字段中。

+
您必须一次添加一个主机端口标识符才能将其与主机关联，但您可以继续选择与主机关联的任意数量的标识符。每个标识符都会显示在 * 主机端口 * 字段中。如有必要，您还可以通过选择标识符旁边的 * X * 来删除该标识符。



|===
. 单击 * 创建 * 。


.结果
成功创建主机后， SANtricity 系统管理器会为为主机配置的每个主机端口创建一个默认名称。

默认别名为 ` < 主机名端口号 >` 。例如，为 `主机 IPT 创建的第一个端口的默认别名是 ipt_1` 。
