---
permalink: config-linux/nvme-roce-discover-connect-storage-host-task.html 
sidebar: sidebar 
keywords: discover storage, host, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 在 SANtricity System Manager 中定义每个主机之前，您必须先从主机发现目标控制器端口，然后建立 NVMe 连接。 
---
= 从E系列中的主机发现存储并连接到Linux (基于RoCE的NVMe)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在 SANtricity System Manager 中定义每个主机之前，您必须先从主机发现目标控制器端口，然后建立 NVMe 连接。

.步骤
. 使用以下命令验证是否可以使用预期的 MTU 速率从主机 ping 每个阵列 HIC 端口：
+
[listing]
----
ping -M do -s <size> <IP of array HIC port>
----
. 使用以下命令发现 NVMe-oF 目标上所有路径的可用子系统：
+
[listing]
----
nvme discover -t rdma -a target_ip_address
----
+
在此命令中， `target_ip_address` 是目标端口的 IP 地址。

+

NOTE: `nvme discover` 命令可发现子系统中的所有控制器端口，而不管主机访问权限如何。

+
[listing]
----
# nvme discover -t rdma -a 192.168.1.77
Discovery Log Number of Records 2, Generation counter 0
=====Discovery Log Entry 0======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  0
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:5700.600a098000a527a7000000005ab3af94
traddr:  192.168.1.77
rdma_prtype: roce
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
=====Discovery Log Entry 1======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  1
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:5700.600a098000a527a7000000005ab3af94
traddr:  192.168.2.77
rdma_prtype: roce
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
----
. 对于任何其他连接，请重复步骤 2。
. 使用命令 `nvme connect -t rdma -n discovered_sub_nqn -a target_ip_address -Q queue_depth_setting -l controller_los_timeout_period` 连接到第一个路径上发现的子系统
+

NOTE: 上面列出的命令不会在重新启动后继续存在。每次重新启动后都需要执行此  `nvme connect` 命令才能重新建立 NVMe 连接。

+

NOTE: 未为主机无法访问的任何已发现端口建立连接。

+

NOTE: 如果使用此命令指定端口号，则连接将失败。默认端口是为连接设置的唯一端口。

+

NOTE: 建议的队列深度设置为 1024。使用 `-Q 1024` 命令行选项用 1024 覆盖默认设置 128，如以下示例所示。

+

NOTE: 建议的控制器丢失超时期限（以秒为单位）为 60 分钟（ 3600 秒）。使用 ` -l 3600` 命令行选项将默认设置 600 秒替换为 3600 秒，如以下示例所示。

+
[listing]
----
# nvme connect -t rdma -a 192.168.1.77 -n nqn.1992-
08.com.netapp:EF80.600a098000a527a7000000005ab3af94 -Q 1024 -l 3600
----
. 重复步骤 4，将发现的子系统连接到第二条路径。
. **可选** - 将主机设置为在每次启动时自动发现并连接到目标。
+
.. 将步骤 2 和步骤 3 中的发现参数添加到 `/etc/nvme/discovery.conf`，使用以下过程和格式：
+
[listing]
----
# echo "--transport=rdma --traddr= target_ip_address --trsvcid=4420" | sudo tee -a /etc/nvme/discovery.conf
----
.. 使用以下命令填充 `/etc/nvme/discovery.conf`文件后启用 nvmf-autoconnect 服务：
+
[listing]
----
sudo systemctl enable nvmf-autoconnect.service
----




.下一步是什么？
建立连接后，link:nvme-roce-define-host-task.html["定义主机"]。
