---
permalink: config-linux/nvme-roce-configure-storage-connections-task.html 
sidebar: sidebar 
keywords: NVMe over RoCE, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: '如果您的控制器包括通过 RoCE 连接 NVMe （基于融合以太网的 RDMA ），则可以从 SANtricity 系统管理器的 " 硬件 " 页面或 " 系统 " 页面配置 NVMe 端口设置。' 
---
= 在E系列- Linux中配置基于RoCE的存储阵列NVMe连接
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您的控制器包括通过 RoCE 连接 NVMe （基于融合以太网的 RDMA ），则可以从 SANtricity 系统管理器的硬件页面或系统页面配置 NVMe 端口设置。

.开始之前
确保您已具备以下条件：

* 控制器上的基于 RoCE 的 NVMe 主机端口；否则， System Manager 中不提供基于 RoCE 的 NVMe 设置。
* 主机连接的 IP 地址。


.关于此任务
您可以从 * 硬件 * 页面或菜单：设置 [ 系统 ] 访问基于 RoCE 的 NVMe 配置。此任务介绍如何从硬件页面配置端口。


NOTE: 只有当存储阵列的控制器包含基于 RoCE 的 NVMe 端口时，才会显示基于 RoCE 的 NVMe 设置和功能。

.步骤
. 从 System Manager 界面中，选择 * 硬件 * 。
. 单击具有要配置的基于 RoCE 的 NVMe 端口的控制器。
+
此时将显示控制器的上下文菜单。

. 选择 * 配置基于 RoCE 的 NVMe 端口 * 。
+
此时将打开 * 通过 RoCE 端口配置 NVMe * 对话框。

. 在下拉列表中，选择要配置的端口，然后单击 * 下一步 * 。
. 选择要使用的端口配置设置，然后单击 * 下一步 * 。
+
要查看所有端口设置，请单击对话框右侧的 * 显示更多端口设置 * 链接。

+
|===
| 端口设置 | Description 


 a| 
已配置以太网端口速度
 a| 
选择所需的速度。下拉列表中显示的选项取决于您的网络可以支持的最大速度（例如 10 Gbps ）。可能的值包括：

** 自动协商
** 10 Gbps
** 25 Gbps
** 40 Gbps
** 50 Gbps
** 100 Gbps
** 200 Gbps



NOTE: 如果使用 QSFP56 缆线连接支持 200 GB 的 HIC ，则只有在连接到 Mellanox 交换机和 / 或适配器时，自动协商才可用。


NOTE: 配置的基于 RoCE 的 NVMe 端口速度应与选定端口上 SFP 的速度功能匹配。所有端口都必须设置为相同的速度。



 a| 
启用 IPv4 和 / 或启用 IPv6
 a| 
选择一个或两个选项以启用对 IPv4 和 IPv6 网络的支持。



 a| 
MTU 大小（可通过单击 * 显示更多端口设置 * 来获取。）
 a| 
如有必要，请为最大传输单元（ MTU ）输入一个新大小（以字节为单位）。默认 MTU 大小为每帧 1500 字节。您必须输入一个介于1500和9000之间的值。

|===
+
如果选择了 * 启用 IPv* ，则在单击 * 下一步 * 后，将打开一个对话框，用于选择 IPv4 设置。如果选择了 * 启用 IPv6* ，则在单击 * 下一步 * 后，将打开一个对话框，用于选择 IPv6 设置。如果同时选择了这两个选项，则 IPv4 设置对话框将首先打开，然后单击 * 下一步 * ， IPv6 设置对话框将打开。

. 自动或手动配置 IPv4 和 / 或 IPv6 设置。要查看所有端口设置，请单击对话框右侧的 * 显示更多设置 * 链接。
+
|===
| 端口设置 | Description 


 a| 
自动从 DHCP 服务器获取配置
 a| 
选择此选项可自动获取配置。



 a| 
手动指定静态配置
 a| 
选择此选项，然后在字段中输入静态地址。对于 IPv4 ，请包括网络子网掩码和网关。对于 IPv6 ，请包括可路由的 IP 地址和路由器 IP 地址。


NOTE: 如果只有一个可路由的 IP 地址，请将其余地址设置为 0 ： 0 ： 0 ： 0 ： 0 ： 0 ： 0 ： 0 。



 a| 
启用 VLAN 支持（可通过单击 * 显示更多设置 * 来获取。）
 a| 

NOTE: 此选项仅在 iSCSI 环境中可用。它在基于 RoCE 的 NVMe 环境中不可用。



 a| 
启用以太网优先级（可通过单击 * 显示更多设置 * 来使用）。
 a| 

NOTE: 此选项仅在 iSCSI 环境中可用。它在基于 RoCE 的 NVMe 环境中不可用。

|===
. 单击 * 完成 * 。

