---
permalink: config-linux/nvme-roce-access-virtual-targets-concept.html 
sidebar: sidebar 
keywords: NVMe volume virtual, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 您可以根据 Linux 版本配置定向到设备目标的 I/O 。 
---
= 访问虚拟设备目标的 NVMe 卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以根据所使用的操作系统（以及扩展多路径方法）配置定向到设备目标的 I/O 。

对于 RHEL 7 和 SLES 12 ， Linux 主机会将 I/O 定向到虚拟设备目标。DM-MP 负责管理这些虚拟目标的物理路径。



== 虚拟设备是 I/O 目标

确保仅对 DM-MP 创建的虚拟设备运行 I/O ，而不对物理设备路径运行 I/O 。如果对物理路径运行 I/O ， DM-MP 将无法管理故障转移事件，并且 I/O 将失败。

您可以通过 /dev/mapper 中的 `dm` device 或 `symlink` 访问这些块设备。例如：

[listing]
----
/dev/dm-1
/dev/mapper/eui.00001bc7593b7f5f00a0980000af4462
----


== 示例

以下 `nvme list` 命令的输出示例显示了主机节点名称及其与命名空间 ID 的关联。

[listing]
----

NODE         SN           MODEL           NAMESPACE

/dev/nvme1n1 021648023072 NetApp E-Series 10
/dev/nvme1n2 021648023072 NetApp E-Series 11
/dev/nvme1n3 021648023072 NetApp E-Series 12
/dev/nvme1n4 021648023072 NetApp E-Series 13
/dev/nvme2n1 021648023151 NetApp E-Series 10
/dev/nvme2n2 021648023151 NetApp E-Series 11
/dev/nvme2n3 021648023151 NetApp E-Series 12
/dev/nvme2n4 021648023151 NetApp E-Series 13
----
|===
| 列 | Description 


 a| 
`节点`
 a| 
节点名称包括两部分：

* 表示法 `nvme1` 表示控制器 A ， `nvme2` 表示控制器 B
* 表示法 `n1` ， `n2` 等代表主机角度的命名空间标识符。这些标识符在表中重复出现，一次用于控制器 A ，一次用于控制器 B




 a| 
`命名空间`
 a| 
命名空间列列出了命名空间 ID （ NSID ），从存储阵列角度来看，命名空间 ID 是标识符。

|===
在以下 `multipath -ll` 输出中，优化路径显示为 `prio` 值 50 ，而非优化路径显示为 `prio` 值 10 。

Linux 操作系统会将 I/O 路由到显示为 `status=active` 的路径组，而列为 `status=enabled` 的路径组可用于故障转移。

[listing]
----
eui.00001bc7593b7f500a0980000af4462 dm-0 NVME,NetApp E-Series
size=15G features='1 queue_if_no_path' hwhandler='0' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| `- #:#:#:# nvme1n1 259:5 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  `- #:#:#:# nvme2n1 259:9  active ready running

eui.00001bc7593b7f5f00a0980000af4462 dm-0 NVME,NetApp E-Series
size=15G features='1 queue_if_no_path' hwhandler='0' wp=rw
|-+- policy='service-time 0' prio=0 status=enabled
| `- #:#:#:# nvme1n1 259:5 failed faulty running
`-+- policy='service-time 0' prio=10 status=active
  `- #:#:#:# nvme2n1 259:9  active ready running
----
|===
| 行项目 | Description 


 a| 
`policy='service-time 0' prio=50 status=active`
 a| 
此行和以下行显示， `nvme1n1` 是 NSID 为 10 的命名空间，它在 `prio` value of 50 和 `ststatus` value of `active` 的路径上进行了优化。

此命名空间属于控制器 A



 a| 
`policy='service-time 0' prio=10 status=enabled`
 a| 
此行显示了命名空间 10 的故障转移路径，其中 `prio` value of 10 and a `stStatus` value of `enabled` 。此时， I/O 不会定向到此路径上的命名空间。

此命名空间属于控制器 B



 a| 
`policy='service-time 0' prio=0 status=enabled`
 a| 
此示例显示了控制器 A 正在重新启动时不同时间点的 ``multipath -ll``输出。命名空间 10 的路径显示为 `failed faulty running` ，其中 `prio` 值为 0 ， `s状态` 值为 `enabled` 。



 a| 
`policy='service-time 0' prio=10 status=active`
 a| 
请注意， `active` 路径是指 `nvme2` ，因此 I/O 将通过此路径定向到控制器 B

|===