---
permalink: maintenance-e2800/batteries-prepare-replace-task.html 
sidebar: sidebar 
keywords: E2800 battery fail, E2800 battery, E2800 battery replacement, replace E2800 battery, replacing E2800 battery, E2800, E-Series, eseries 
summary: 按照适用于双工或单工的步骤准备更换 E2800 电池。 
---
= 准备更换电池- E2800
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
准备更换电池的步骤取决于您采用的是双工配置（两个控制器）还是单工配置（一个控制器）。

* 有关双工配置，请参见 <<使控制器脱机（双工）>>。
* 有关单工配置，请参见 <<关闭控制器架电源（单工）>>。


.开始之前
* 验证是否未使用任何卷，或者是否已在使用这些卷的所有主机上安装多路径驱动程序。
* 查看 link:batteries-overview-requirements-concept.html["更换 E2800 电池的要求"]。




== 使控制器脱机（双工）

如果您采用双工配置，则必须将受影响的控制器置于脱机状态，以便安全地取出故障电池。未置于脱机状态的控制器必须处于联机状态（处于最佳状态）。


NOTE: 只有当存储阵列具有两个控制器（双工配置）时，才能执行此任务。

.步骤
. 在 SANtricity 系统管理器中，查看恢复 Guru 中的详细信息，确认问题描述具有电池，并确保不需要先解决任何其他问题。
. 从 Recovery Guru 的 Details 区域中，确定要更换的电池。
. 使用 SANtricity 系统管理器备份存储阵列的配置数据库。
+
如果删除控制器时出现问题，您可以使用保存的文件还原配置。系统将保存 RAID 配置数据库的当前状态，其中包括控制器上卷组和磁盘池的所有数据。

+
** 在 System Manager 中：
+
... 选择菜单： Support[ 支持中心 > 诊断 ] 。
... 选择 * 收集配置数据 * 。
... 单击 * 收集 * 。
+
此文件将保存在浏览器的 "Downloads" 文件夹中，名为 * configurationData-<arrayName>-<DateTime>.7z* 。



** 或者，您也可以使用以下命令行界面命令备份配置数据库：
+
`s存取存储阵列 dbmDatabase sourceLocation=Onboard contentType=all file="filename" ；`



. 使用 SANtricity 系统管理器收集存储阵列的支持数据。
+
如果删除控制器时出现问题，您可以使用保存的文件对问题描述进行故障排除。系统会将有关存储阵列的清单，状态和性能数据保存在一个文件中。

+
.. 选择菜单： Support[ 支持中心 > 诊断 ] 。
.. 选择 * 收集支持数据 * 。
.. 单击 * 收集 * 。
+
此文件将保存在浏览器的 "Downloads" 文件夹中，名为 * support-data.7z* 。



. 如果控制器尚未脱机，请立即使用 SANtricity 系统管理器将其脱机。
+
** 在 SANtricity 系统管理器中：
+
... 选择 * 硬件 * 。
... 如果图形显示了驱动器，请选择 * 显示磁盘架背面 * 以显示控制器。
... 选择要置于脱机状态的控制器。
... 从上下文菜单中，选择 * 置于脱机状态 * ，然后确认要执行此操作。
+

NOTE: 如果您正在使用尝试脱机的控制器访问 SANtricity 系统管理器，则会显示 SANtricity 系统管理器不可用消息。选择 * 连接到备用网络连接 * 以使用另一个控制器自动访问 SANtricity 系统管理器。



** 或者，您也可以使用以下命令行界面命令使控制器脱机：
+
* 对于控制器 A ： * `set controller [a] availability = 脱机`

+
* 对于控制器 B ： * `set controller [b] availability = 脱机`



. 等待 SANtricity System Manager 将控制器状态更新为脱机。
. 转至 link:batteries-remove-controller-canister-task.html["拆下 E2800 控制器箱"]。
+

CAUTION: 更新状态之前，请勿开始任何其他操作。





== 关闭控制器架电源（单工）

如果您采用单工配置，请关闭控制器架，以便安全地取出故障电池。


NOTE: 只有当存储阵列具有一个控制器（单工配置）时，才能执行此任务。

.步骤
. 使用 SANtricity 系统管理器备份存储阵列的配置数据库。
+
如果删除控制器时出现问题，您可以使用保存的文件还原配置。系统将保存 RAID 配置数据库的当前状态，其中包括控制器上卷组和磁盘池的所有数据。

+
** 在 System Manager 中：
+
... 选择菜单： Support[ 支持中心 > 诊断 ] 。
... 选择 * 收集配置数据 * 。
... 单击 * 收集 * 。
+
此文件将保存在浏览器的 "Downloads" 文件夹中，名为 * configurationData-<arrayName>-<DateTime>.7z* 。



** 或者，您也可以使用以下命令行界面命令备份配置数据库：
+
`s存取存储阵列 dbmDatabase sourceLocation=Onboard contentType=all file="filename" ；`



. 使用 SANtricity 系统管理器收集存储阵列的支持数据。
+
如果删除控制器时出现问题，您可以使用保存的文件对问题描述进行故障排除。系统会将有关存储阵列的清单，状态和性能数据保存在一个文件中。

+
.. 选择菜单： Support[ 支持中心 > 诊断 ] 。
.. 选择 * 收集支持数据 * 。
.. 单击 * 收集 * 。
+
此文件将保存在浏览器的 "Downloads" 文件夹中，名为 * support-data.7z* 。



. 确保存储阵列与所有已连接主机之间未发生任何 I/O 操作。例如，您可以执行以下步骤：
+
.. 停止涉及从存储映射到主机的 LUN 的所有进程。
.. 确保没有应用程序向从存储映射到主机的任何 LUN 写入数据。
.. 卸载与阵列上的卷关联的所有文件系统。
+

NOTE: 停止主机 I/O 操作的确切步骤取决于主机操作系统和配置，这些步骤不在本说明的范围之内。如果您不确定如何停止环境中的主机 I/O 操作，请考虑关闭主机。

+

CAUTION: * 可能的数据丢失 * - 如果在执行 I/O 操作时继续执行此操作步骤，则可能会丢失数据。



. 等待缓存中的所有数据写入驱动器。
+
需要将缓存数据写入驱动器时，控制器背面的绿色缓存活动 LED 亮起。您必须等待此 LED 关闭。

. 从 SANtricity 系统管理器的主页中，选择 * 查看正在执行的操作 * 。
. 确认所有操作均已完成，然后再继续下一步。
. 关闭控制器架上的两个电源开关。
. 等待控制器架上的所有 LED 熄灭。
. 转至 link:batteries-remove-controller-canister-task.html["拆下 E2800 控制器箱"]。

