---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity, 12.0, 11.9, 11.8, EF80, EF50, E4000, EF300, EF600, E2800, EF280, E5700, EF570, 
summary: SANtricity OS 中的新增功能。 
---
= SANtricity OS 中的新增功能
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ./media/


[role="lead"]
下表介绍了用于 EF80、EF50、E4000、EF300、EF600、E2800/EF280 和 E5700/EF570 控制器嵌入式管理的最新 SANtricity 操作系统版本中的新功能。



== 版本 12.0 中的新增功能


NOTE: SANtricity OS 12.0 版本仅与新的 EF80 和 EF50 全闪存存储系统兼容。

[cols="35h,~"]
|===
| 新增功能 | Description 


 a| 
新存储系统型号 – EF80 和 EF50 全闪存存储系统
 a| 
此版本引入了 EF80 和 EF50 全 NVMe 闪存存储系统。EF80 和 EF50 支持 24 个 NVME SSD 驱动器和每个控制器一个控制器间镜像卡。支持的 NVMe over Fabrics 主机接口包括 NVMe over RoCE、NVMe over IB、EF80 的 NVMe over FC 和 EF50 的 NVMe over FC。支持的 SCSI 接口是两个系统的光纤通道。EF50 支持每个控制器最多两个主机接口卡，而 EF80 支持每个控制器最多三个主机接口卡。

EF80 和 EF50 也支持 30TB 或 60TB 大小的大容量 NVMe SSD 驱动器。EF80 和 EF50 只能在阵列装有 30TB 或 60TB 驱动器时使用动态磁盘池。



 a| 
SANtricity System Manager 的新用户界面
 a| 
对于新的 EF80 和 EF50 控制器，SANtricity System Manager 用户界面经过重新设计，以提供更现代的外观和感觉。新界面包括左侧面板导航和增强的可用性，以简化管理任务。



 a| 
服务器证书的使用者备用名称 (SAN) 现在仅允许字母、数字和连字符
 a| 
在 SANtricity System Manager 或 Unified Manager 中创建或编辑服务器证书时，使用者备用名称 (SAN) 字段现在只允许使用字母、数字和连字符。此更改可增强安全性，并确保与 SSL/TLS 证书的行业标准兼容。



 a| 
对于基于 SSD 和 NVMe 的系统，动态磁盘池段大小现在默认为 32K
 a| 
对于基于 SSD 和 NVMe 的系统上的动态磁盘池，默认数据段大小已更改为 32K。以前，这些系统的动态磁盘池默认段大小固定为 128K。此更改可优化涉及小型和大型 I/O 操作混合的工作负载的性能。



 a| 
现在可在 SANtricity System Manager 中使用脚本编辑器
 a| 
SANtricity System Manager 中现在提供了新的脚本编辑器。脚本编辑器允许您创建或编辑脚本文件，将脚本文件保存到存储管理站的本地磁盘，或从磁盘加载脚本文件。脚本编辑器提供用于管理存储系统的语法检查和命令执行功能。有关详细信息，请参见 link:https://docs.netapp.com/us-en/e-series-santricity/sm-support/use-script-editor.html["使用脚本编辑器"^]。

|===


== 版本 11.90R5 中的新增功能

此版本仅包含缺陷修复，不包含新功能。有关此版本中更改的更多信息，请参见 E-Series SANtricity 操作系统 11.90R5 README。



== 11.90R4 版本新增功能

此版本仅包含小的更改，没有新功能。有关此版本中更改的更多信息，请参见 E-Series SANtricity 操作系统 11.90R4 README。



== 11.90R3中的新增功能

[cols="35h,~"]
|===
| 新增功能 | Description 


 a| 
SANtricity 操作系统对 IOM12C 和 DCM3 的支持
 a| 
控制器固件版本 11.90R3 或更高版本现已支持 IOM12C 和 DCM3 SAS-3 磁盘架。IOM12C和 DCM3 磁盘架将替代 IOM12B 和 DCM2 磁盘架。

|===


== 11.90R2中的新增功能

此版本仅包含少量更改、没有任何新功能。有关此版本中变更的详细信息，请参阅 https://library.netapp.com/ecm/ecm_download_file/ECMLP3334464["E系列11.90发行说明"^]。



== 11.90R1中的新增功能

[cols="35h,~"]
|===
| 新增功能 | Description 


 a| 
新存储系统型号—EF300C和EF600C
 a| 
此版本推出了EF300C和EF600C全闪存NVMe存储系统。EF300C和EF600C是现有EF300和EF600存储系统的高容量闪存版本。EF300C和EF600C支持30 TB或60 TB大小的高容量NVMe SSD驱动器。EF300C/EF600C仅兼容动态磁盘池、不支持原有RAID。



 a| 
支持E4000控制器上的12 Gb SAS接口
 a| 
E4000控制器现在支持12 Gb SAS主机接口卡。

|===


== 11.90版中的新增功能

[cols="35h,~"]
|===
| 新增功能 | Description 


 a| 
新存储系统型号— E4000
 a| 
此版本引入了E4000低成本存储系统。E4000支持12个和60个驱动器以及每个控制器一个主机接口卡(Host Interface Card、HIC)。初始版本支持的主机接口卡包括iSCSI和光纤通道。可以在Unified Manager中查看和管理E4000存储系统和其他E系列存储系统。



 a| 
增加了动态磁盘池的容量
 a| 
只要动态磁盘池(Dynamic Disk Pool、DDP)中每个驱动器的容量超过23 TB、该容量就会增加到12 PB。如果单个驱动器容量小于23 TB、则DDP容量为6 PB。



 a| 
增加了默认介质扫描设置
 a| 
默认介质扫描速率已增加到120天。



 a| 
专用密钥现在可用于外部密钥管理
 a| 
现在、可以通过System Manager导入外部通过私钥和公共密钥对生成的证书签名请求(CSR)文件。



 a| 
现在、Web服务可以使用登录锁定功能
 a| 
现在、嵌入式Web服务和代理Web服务均可使用新的登录锁定设置、该设置仅可通过REST API进行配置。

|===


== 11.80.1R4中的新增功能

此版本仅包含少量更改、没有任何新功能或限制。有关此版本中更改的详细信息、请参阅自述文件。



== 11.80.1R3中的新增功能

此版本仅包含少量更改、没有任何新功能或限制。有关此版本中更改的详细信息、请参阅自述文件。



== 11.80.1R2中的新增功能

此版本仅包含少量更改、没有任何新功能或限制。有关此版本中更改的详细信息、请参阅自述文件。



== 11.80.1R1中的新增功能

[cols="35h,~"]
|===
| 新增功能 | Description 


 a| 
增加了新的自签名和CA签名管理证书的密钥大小长度。
 a| 
SANtricity系统管理器和Unified Manager应用程序自签名证书的管理证书密钥大小长度已从2048位修改为3072位。此更改将应用于SANtricity应用程序中新生成的自签名证书和CA签名证书。密钥长度是固定的、不受NV遭受NV遭受 中默认密钥大小定义的影响。

|===


== 11.80.1版中的新增功能

[cols="35h,~"]
|===
| 新增功能 | Description 


 a| 
`-identifyDevices` 参数
 a| 
SMcli 中现在有一个新 `-identifyDevices`参数。此新参数允许您查找与存储阵列关联的所有 SCSI 本机块设备。有关详细信息，请参见link:https://docs.netapp.com/us-en/e-series-cli/get-started/downloadable-smcli-parameters.html#identify-Devices["可下载的 SMcli 命令行参数"^]。



 a| 
以太网内核统计信息
 a| 
在 System Manager 的 View iSCSI Statistics Packages 页面下，现在提供了新的 Ethernet Kernel Statistics 选项。此新选项允许您查看 iSCSI 设备的平台内核驱动程序的统计信息。有关详细信息，请参见 link:https://docs.netapp.com/us-en/e-series-santricity/sm-support/view-iscsi-statistics-packages-support.html["查看 iSCSI 统计数据包"^]。



 a| 
增加了通过REST API端点阻止IP地址的功能
 a| 
现在、用户可以通过设置端点阻止特定IP地址 (`/devmgr/v2/settings`）。通过设置端点配置后、只有通过白列表指定的IP地址才能与存储设备进行通信。此新功能支持IPv4和IPv6地址列表。



 a| 
vCenter存储插件
 a| 
vCenter存储插件已更新、可与E系列11.80.1版兼容。



 a| 
Web服务代理
 a| 
Web服务代理已更新到6.1版、以便与E系列11.80.1版兼容。

|===


== 11.80版中的新增功能

[cols="35h,~"]
|===
| 新增功能 | Description 


 a| 
增强型卷奇偶校验扫描
 a| 
现在、可以通过REST API或CLI在后台启动卷奇偶校验扫描。只要完成扫描操作需要、生成的奇偶校验扫描就会在后台运行。扫描操作将在控制器重新启动和故障转移操作后继续运行。



 a| 
Unified Manager的SAML支持
 a| 
Unified Manager现在支持SAML (安全断言标记语言)。为Unified Manager启用SAML后、用户必须对身份提供程序使用多因素身份验证、才能与用户界面进行交互。请注意、在Unified Manager上启用SAML后、如果不通过Idp对请求进行身份验证、则无法使用REST API。



 a| 
自动配置功能
 a| 
现在支持设置卷块大小参数、以便在初始阵列设置时与自动配置功能结合使用。此功能在CLI中仅作为"blocksize"参数提供。



 a| 
控制器固件加密签名
 a| 
控制器固件已进行加密签名。签名会在初始下载期间和每次控制器启动时进行检查。预期不会对最终用户造成影响。签名由CA颁发的扩展验证证书提供支持。



 a| 
驱动器固件加密签名
 a| 
驱动器固件已进行加密签名。签名会在初始下载期间进行检查、并由CA颁发的扩展验证证书提供支持。驱动器固件内容现在以ZIP文件的形式提供、其中包含旧的未签名固件以及新的已签名固件。用户必须根据目标系统上运行的代码版本选择适当的文件。



 a| 
外部密钥服务器管理-证书密钥大小
 a| 
新的默认证书密钥大小为3072位(2048位)。支持高达4096位的密钥大小。要支持非默认密钥大小、必须更改NVSRAM位。

密钥大小选择值如下：

* 默认值为0
* 长度2048 = 1
* 长度3072 = 2
* 长度4096 = 3


要通过SMCli,将密钥大小更改为4096：

`set controller[b] globalnvsrambyte[0xc0]=3;`
`set controller[a] globalnvsrambyte[0xc0]=3;`

查询密钥大小：

`show allcontrollers globalnvsrambyte[0xc0];`



 a| 
改进了磁盘池
 a| 
使用运行11.80或更高版本的控制器创建的磁盘池将为_Version 1_ Pool、而不是_Version 0_ Pool。如果存在_Version 1_磁盘池、则降级操作会受到限制。

可以在存储阵列配置文件中确定磁盘池的版本。



 a| 
除非满足最低浏览器要求、否则System Manager和Unified Manager将无法启动
 a| 
要启动System Manager或Unified Manager、必须安装最低版本的浏览器。

以下是支持的最低版本：

* Firefox最低版本80
* Chrome最低版本89
* Edge最小版本90
* Safari最低版本14




 a| 
支持FIPS 140-2 NVMe SSD驱动器
 a| 
现在支持经NetApp认证的FIPS 140-2 NVMe SSD驱动器。它们将在存储阵列配置文件和System Manager中正确标识。



 a| 
支持EF300和EF600上的SSD读取缓存
 a| 
现在、使用HDD和SAS扩展的EF300和EF600控制器支持SSD读取缓存。



 a| 
支持EF300和EF600上的iSCSI和光纤通道异步远程镜像
 a| 
现在、使用基于NVMe和SAS的卷的EF300和EF600控制器支持异步远程镜像(ARVM)。



 a| 
支持基本托架上没有驱动器的EF300和EF600
 a| 
现在支持在基座托盘上不使用NVMe驱动器的EF300和EF600控制器配置。



 a| 
已为所有平台禁用USB端口
 a| 
现在、所有平台均已禁用USB端口。



 a| 
增加了SSD读取缓存最大值
 a| 
SSD读取缓存最大值从5 TB增加到8 TB。



 a| 
为双工配置中的单个卷分配全闪存读取缓存
 a| 
现在、只要一个卷使用整个SSD缓存、就可以将所有SSD读取缓存分配给双工系统上的同一个卷。



 a| 
已将驱动器序列号添加到存储阵列配置文件的驱动器摘要表中
 a| 
驱动器序列号已添加到存储阵列配置文件的驱动器摘要表中。



 a| 
已将dom0-MiSC日志添加到每日ASUP
 a| 
控制器A和B的dom0-MiSC日志已添加到每日ASUP中。



 a| 
默认情况下、端口443用于应用程序与嵌入式Web服务进行通信
 a| 
现在、默认情况下、在与嵌入式Web服务器通信时会使用端口443。。  `-useLegacyTransferPort` 已为改用旧版8443传输端口的用户添加了命令行界面命令。有关新的-usealeTransferPort CLI命令的详细信息、请参见 https://docs.netapp.com/us-en/e-series-cli/whats-new.html["SANtricity命令行界面新增功能"]。



 a| 
扫描卷奇偶校验进度功能
 a| 
已实施以下命令行界面命令来支持基于作业的卷奇偶校验扫描操作：

* 启动检查卷奇偶校验
* 保存检查卷奇偶校验作业错误
* 停止检查卷奇偶校验作业
* 显示检查卷奇偶校验作业


有关新的基于作业的卷奇偶校验扫描命令行界面命令的详细信息、请参见 https://docs.netapp.com/us-en/e-series-cli/whats-new.html["SANtricity命令行界面新增功能"]。



 a| 
Unified Manager的MFA支持
 a| 
现在、Unified Manager支持多因素身份验证(MFA)。



 a| 
切换图标可显示前背硬件视图
 a| 
在System Manager/Unified Manager的硬件视图中、现在可以使用以下两个选项卡来控制正面视图和背面视图：

* 驱动器选项卡
* 控制器和组件选项卡




 a| 
vCenter存储插件
 a| 
vCenter存储插件已更新、可与E系列11.80版本兼容。



 a| 
Web服务代理6.0
 a| 
Web服务代理已更新到6.0版、以便与E系列11.80版本兼容。



 a| 
删除了E系列额定和最大温度已超过事件的ASUP案例创建标志
 a| 
现在、对于不需要采取任何操作的标称和最大温度已超过事件、案例创建标志已禁用。



 a| 
为0x1209 Mel事件启用优先级案例创建标志
 a| 
现在、将为创建案例创建标志 `MEL_EV_DEGRADE_CHANNEL 0x1209` MEL事件。

|===