---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 11.73 
summary: SANtricity OS 中的新增功能。 
---
= SANtricity OS 中的新增功能
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
下表介绍了SANtricity OS 11.7中用于嵌入式管理EF300、EF600、E2800/EF280和E5700/EF570控制器的新功能。



== 11.74版中的新增功能

[cols="35h,~"]
|===
| 新增功能 | Description 


 a| 
支持FIPS 140-3
 a| 
现在、对于基于SAS和NVMe的SSD、某些驱动器均支持FIPS 140-3。FIPS 140-3级SSD驱动器可以与FIPS 140-2级SSD驱动器共存、但前提是这些驱动器要么全部基于NVMe、要么全部基于SAS。在卷组和磁盘池中混合使用这些级别时、请注意组或池将在较低的安全级别(140-2)下运行。



 a| 
MFA和SSH支持
 a| 
对于SANtricity 11.74及更高版本、远程登录功能允许您通过要求用户输入SSH密钥和/或SSH密码来配置多因素授权(Multifactor Authorization、MFA)。硬件部分中的菜单选项已从*更改远程登录*更改为*配置远程登录(SSH)*。



 a| 
访问令牌
 a| 
此版本包含一项用于创建访问令牌的新功能。通过这些令牌、您可以使用REST API或命令行界面(CLI)进行身份验证、而不会公开用户名和密码。访问管理部分提供了此功能。



 a| 
美国政府行政命令
 a| 
为了遵守执行订单、此版本包括多项安全更改。

|===


== 11.73版中的新增功能

[cols="35h,~"]
|===
| 新增功能 | Description 


 a| 
资源配置和DULBE"支持
 a| 
此版本现在完全支持资源配置功能和DULBE-驱动器功能。这种支持包括使资源配置卷上的主机定向UNMAP更广泛地可用。



 a| 
EF600 SAS (512e)扩展
 a| 
此版本支持将EF600存储系统的SAS-3机箱扩展为SAS。通过此扩展， 4KiB 块 NVMe SSD 可以与 512e SAS SSD 和 HDD 共存。但是，块大小不同的驱动器不能配置在同一个池或卷组中。



 a| 
qlc SSD支持
 a| 
此版本支持在驱动器固件中设置了ONTAP 功能但未设置完整E系列专用功能的新一代QLC SSD。qlc驱动器(仅限NVMe)的成本较低、但写入性能较低、持久性等级较低、因此不应用于写入密集型工作负载。



 a| 
支持TLS 1.3
 a| 
现在、嵌入式管理支持TLS 1.3。这样可以支持适用场景 System Manager和嵌入式Web服务、并可以启用或禁用它。(在先前版本中为Web服务代理和Unified Manager增加了TLS 1.3支持。)



 a| 
RAID 1 DDP、最少8个驱动器
 a| 
在此版本中、RAID 1 DDP不再要求池中至少有11个SSD。现在、如果在池中仅创建RAID 1卷、则最小值允许使用8驱动器SSD池。



 a| 
删除EKMS密钥
 a| 
现在、存储管理员可以请求外部密钥管理服务器(EKMS)删除旧密钥。只有在已安装驱动器具有新密钥后、才会在重新设置密钥过程中删除此密钥。

|===


== 11.72 版中的新增功能

[cols="35h,~"]
|===
| 新增功能 | Description 


 a| 
SNMPv3 支持
 a| 
现在、警报通知支持SNMPv3、可在菜单：设置[警报]中进行配置。SNMPv3 可通过强大的身份验证和数据加密提供安全性。



 a| 
支持将密钥复制到多个密钥服务器
 a| 
对于自加密驱动器的外部密钥管理，创建外部密钥管理对话框提供了一个用于添加多个密钥服务器的新选项。



 a| 
已更新浏览器版本
 a| 
已更新 System Manager 的最低浏览器版本。

|===


== 11.71 版中的新增功能

[cols="35h,~"]
|===
| 新增功能 | Description 


 a| 
EF300 扩展
| 此版本支持将 EF300 存储系统的 SAS-3 机箱扩展为 SAS 。通过此扩展， 4KiB 块 NVMe SSD 可以与 512e SAS SSD 和 HDD 共存。但是，块大小不同的驱动器不能配置在同一个池或卷组中。 


 a| 
iSCSI 配置中的 FEC 模式选项
 a| 
对于使用 25 Gb iSCSI 主机接口卡的存储阵列，可以使用一个新选项在配置 iSCSI 端口时设置正向错误更正（ FEC ）模式。



 a| 
远程存储卷
 a| 
通过可选的远程存储卷功能，您可以使用 iSCSI 连接将卷从远程存储系统导入到本地 E 系列存储系统。远程存储可以与您的 E 系列系统具有相同的品牌，也可以来自其他存储供应商，只要可以通过 iSCSI 进行访问即可。



 a| 
为非 FDE 驱动器添加了清理（擦除）功能
 a| 
驱动器清理功能现在在操作步骤中包括非 FDE 驱动器。在硬件页面中，您可以打开驱动器的上下文菜单并选择 " 擦除 " （以前，此选项为 " 安全擦除 " ）。



 a| 
电子邮件警报的安全连接
 a| 
要启用加密电子邮件通知，您可以选择配置传出电子邮件（警报， ASUP 派单）以提供身份验证凭据。加密类型包括 SMTPS 和 STARTTLS 。



 a| 
AutoSupport 新增功能
 a| 
现在，如果未启用 AutoSupport ，则通知区域将显示一条警报。



 a| 
系统日志警报格式更改
 a| 
系统日志警报格式现在支持 RFC 5424 。

|===


== 11.70 版中的新增功能

[cols="35h,~"]
|===
| 新增功能 | Description 


 a| 
新存储系统型号— EF300
 a| 
此版本引入了 EF300 低成本纯 NVMe 闪存存储系统。EF300 包括 24 个 NVMe SSD 驱动器和每个控制器一个主机接口卡（ HIC ）。支持的基于网络结构的 NVMe 主机接口包括基于 IB 的 NVMe ，基于 RoCE 的 NVMe 和基于 FC 的 NVMe 。支持的 SCSI 接口包括 FC ， iSER 上的 IB 和 SRP 上的 IB 。可以在 Unified Manager 中查看和管理多个 EF300 存储系统和其他 E 系列存储系统。



 a| 
新的资源配置功能（仅限 EF300 和 EF600 ）
 a| 
资源配置功能是 EF300 和 EF600 存储系统的新增功能。资源配置的卷可以立即投入使用，而无需后台初始化过程。



 a| 
添加 512e 块大小选项（仅限 EF300 和 EF600 ）
 a| 
对于 EF300 和 EF600 存储系统，可以将卷设置为支持 512 字节或 4KiB 块大小。添加了 512e 功能，以支持 iSCSI 主机接口和 VMware 操作系统。如果可能， System Manager 会建议适当的默认值。



 a| 
用于按需发送 AutoSupport 派单的新选项
 a| 
通过新的发送 AutoSupport 派遣功能，您无需等待计划的派单，即可向技术支持发送数据。此选项可在支持中心的 AutoSupport 选项卡中找到。



 a| 
外部密钥管理服务器增强功能
 a| 
用于连接到外部密钥管理服务器的功能包括以下增强功能：

* 绕过创建备份密钥的功能。
* 除了客户端和服务器证书之外，还为密钥管理服务器选择一个中间证书。




 a| 
证书增强功能
 a| 
此版本允许使用 OpenSSL 等外部工具生成证书签名请求（ Certificate Signing Request ， CSR ），同时还要求您导入私钥文件以及签名证书。



 a| 
为卷组提供了新的脱机初始化功能
 a| 
在创建卷时， System Manager 提供了一种跳过主机分配步骤的方法，以便新创建的卷脱机初始化。此功能仅适用于SAS驱动器上的RAID卷组(即、不适用于动态磁盘池或EF300和EF600存储系统中包含的NVMe SSD)。此功能适用于在使用开始时需要使卷处于完全性能状态的工作负载，而不是在后台运行初始化。



 a| 
新增了收集配置数据功能
 a| 
这一新功能可从控制器保存RAID配置数据、其中包括卷组和磁盘池的所有数据(与用于`s存储量阵列dbmDatabase`的CLI命令的信息相同)。此功能已添加到支持中心的 "Diagnostics （诊断） " 选项卡中，以协助技术支持。



 a| 
在 12 个驱动器的情况下更改磁盘池的默认保留容量
 a| 
以前，创建了一个具有足够保留（备用）容量的 12 驱动器磁盘池，以容纳两个驱动器。现在，默认值已更改，可处理单个驱动器故障，从而提供更经济高效的小型池默认值。

|===