---
permalink: getting-started/learn-terms-concept.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, terms 
summary: 详细了解 E 系列中使用的术语。 
---
= E 系列术语
:icons: font
:imagesdir: ../media/


[role="lead"]
详细了解 E 系列中使用的术语。

|===
| 期限 | Description 


 a| 
控制器
 a| 
控制器由主板，固件和软件组成。它控制驱动器并实施功能。



 a| 
双工 / 单工配置
 a| 
双工是存储阵列中的双控制器模块配置。单工是一种单控制器模块配置。



 a| 
HDD
 a| 
硬盘驱动器（ HDD ）是指使用带有磁性层的旋转金属盘的数据存储设备。



 a| 
HIC
 a| 
主机接口卡（ HIC ）用于将阵列连接到主机。可以选择将其安装在控制器箱中。



 a| 
IB
 a| 
InfiniBand （ IB ）是高性能服务器和存储系统之间数据传输的一种通信标准。



 a| 
IOPS
 a| 
IOPS 是指每秒输入 / 输出操作数。



 a| 
镜像
 a| 
镜像是指将数据卷复制到单独的存储阵列，以确保持续可用性。



 a| 
池
 a| 
池是指一组按逻辑分组的驱动器。您可以使用池创建一个或多个可供主机访问的卷。



 a| 
电源 / 风扇箱
 a| 
电源 / 风扇箱是一个可滑入磁盘架的组件。它包括一个电源和一个集成风扇。



 a| 
机架单元（ U ）
 a| 
机架单元（缩写为 U ）是一个度量单位，定义为 44.50 毫米（ 1.75 英寸）。



 a| 
（ SAS ）。
 a| 
串行连接 SCSI （ SAS ）是一种点对点串行协议，可将控制器直接链接到磁盘驱动器。



 a| 
RoCE
 a| 
基于融合以太网的 RDMA （ RoCE ）是一种网络协议，允许通过以太网远程直接内存访问（ RDMA ）。



 a| 
磁盘架
 a| 
磁盘架是安装在机柜或机架中的机箱。它包含存储阵列的硬件组件。磁盘架有两种类型：控制器磁盘架和驱动器磁盘架。控制器架包括控制器和驱动器。驱动器架包括输入 / 输出模块（ IOM ）和驱动器。



 a| 
Snapshot
 a| 
快照映像是指在特定时间点捕获的卷数据的逻辑副本。与还原点一样，您可以通过快照映像回滚到已知正常的数据集。



 a| 
SSD
 a| 
固态磁盘（ SSD ）是指使用固态内存（ Flash ）持久存储数据的数据存储设备。SSD 可模拟传统硬盘驱动器，并可与硬盘驱动器使用相同的接口。



 a| 
存储阵列
 a| 
存储阵列包括磁盘架，控制器，驱动器，软件和固件。



 a| 
volume
 a| 
卷是应用程序，数据库和文件系统用于存储数据的容器。它是为主机创建的逻辑组件，用于访问存储阵列上的存储。



 a| 
工作负载
 a| 
工作负载是指支持应用程序的存储对象。对于某些应用程序， System Manager 会将工作负载配置为包含具有类似底层卷特征的卷。这些卷特征会根据工作负载支持的应用程序类型进行优化。

|===