---
permalink: config-vmware/verify-vmware-config-support-task.html 
sidebar: sidebar 
keywords: express vmware configuration, software configuration, vmware host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 验证是否支持 VMware 配置。 
---
= 验证是否支持 VMware 配置
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
为了确保操作可靠，您需要创建一个实施计划，然后使用 NetApp 互操作性表工具（ IMT ）验证是否支持整个配置。

.步骤
. 转至 http://mysupport.netapp.com/matrix["NetApp 互操作性表工具"^]。
. 单击 * 解决方案 Search* 图块。
. 在菜单：协议 [SAN 主机 ] 区域中，单击 * E 系列 SAN 主机 * 旁边的 * 添加 * 按钮。
. 单击 * 查看细化搜索条件 * 。
+
此时将显示细化搜索条件部分。在本节中，您可以选择适用的协议以及其他配置标准，例如操作系统， NetApp 操作系统和主机多路径驱动程序。选择您知道配置所需的条件，然后查看适用的兼容配置要素。根据需要，根据工具中的规定更新操作系统和协议。单击右页面箭头可在查看支持的配置页面上访问选定配置的详细信息。

. 根据需要，根据表中列出的操作系统和协议进行更新。
+
|===
| 操作系统更新 | 协议 | 与协议相关的更新 


 a| 
** 您可能需要安装开箱即用的驱动程序，以确保正常运行和可支持性。您可以使用 ESXi Shell 或与 ESXi 主机的远程 SSH 连接安装 HBA 驱动程序。要使用上述任一方法访问主机，必须启用 ESXi Shell 和 SSH 访问。有关 ESXi shell 的详细信息，请参阅 VMware 知识库中有关在 ESXi 中使用 ESXi shell 的信息。有关安装命令，请参见 HBA 驱动程序随附的说明。
** 每个 HBA 供应商都有特定的方法来更新启动代码和固件。其中一些方法可能包括使用 vCenter 插件或在 ESXi 主机上安装 CIM 提供程序。vCenter 插件可用于获取有关供应商的特定 HBA 的信息。请参阅供应商网站的支持部分，获取更新 HBA 启动代码或固件所需的说明和软件。要获取正确的启动代码或固件，请参见 _VMware 兼容性指南 _ 或 HBA 供应商的网站。

 a| 
FC
 a| 
主机总线适配器（ HBA ）驱动程序，固件和启动代码



 a| 
iSCSI
 a| 
网络接口卡（ Network Interface Card ， NIC ）驱动程序，固件和启动代码



 a| 
（ SAS ）。
 a| 
主机总线适配器（ HBA ）驱动程序，固件和启动代码

|===

