---
sidebar: sidebar 
permalink: vcenter-plugin/faq-storage-plugin-vcenter.html 
keywords:  
summary: 如果您只是想快速了解问题解答，此常见问题解答会很有帮助。 
---
= SANtricity Storage Plugin for vCenter 的常见问题解答
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== 导入了哪些设置？

导入设置功能是一个批处理操作、可将配置从一个存储阵列加载到多个存储阵列。

在此操作期间导入的设置取决于源存储阵列在System Manager中的配置方式。可以将以下设置导入到多个存储阵列：

* *电子邮件警报*-设置包括邮件服务器地址和警报收件人的电子邮件地址。
* *系统日志警报*-设置包括系统日志服务器地址和UDP端口。
* * SNMP警报*-设置包括SNMP服务器的社区名称和IP地址。
* * AutoSupport *—设置包括不同的功能(基本AutoSupport 、AutoSupport OnDemand和远程诊断)、维护窗口、交付方法、 和派单计划。
* *目录服务*—配置包括LDAP (轻型目录访问协议)服务器的域名和URL、以及LDAP服务器用户组与存储阵列预定义角色的映射。
* *存储配置*—配置包括卷(仅厚卷和非存储库卷)、卷组、池和热备用驱动器分配。
* *系统设置*-配置包括卷的介质扫描设置、控制器的SSD缓存以及自动负载平衡(不包括主机连接报告)。




== 为什么我看不到所有存储阵列？

在导入设置操作期间、某些存储阵列可能在目标选择对话框中不可用。

存储阵列可能不会显示、原因如下：

* 固件版本低于8.50。
* 存储阵列已脱机。
* 系统无法与该阵列进行通信(例如、该阵列存在证书、密码或网络问题)。




== 为什么这些卷不与工作负载关联？

如果卷是使用命令行界面(CLI)创建的、或者已从其他存储阵列迁移(导入/导出)、则卷不会与工作负载关联。



== 选定工作负载对卷创建有何影响？

在创建卷期间、系统会提示您提供有关工作负载使用情况的信息。系统会使用此信息为您创建最佳卷配置、您可以根据需要对其进行编辑。或者、您也可以在卷创建序列中跳过此步骤。

工作负载是指支持应用程序的存储对象。您可以为每个应用程序定义一个或多个工作负载或实例。对于某些应用程序、系统会将工作负载配置为包含具有类似底层卷特征的卷。这些卷特征会根据工作负载支持的应用程序类型进行优化。例如、如果您创建了一个支持Microsoft SQL Server应用程序的工作负载、然后为该工作负载创建了卷、则底层卷特征将进行优化以支持Microsoft SQL Server。

* *应用程序专用*—当您使用应用程序专用工作负载创建卷时、系统可能会建议优化卷配置、以最大程度地减少应用程序工作负载I/O与应用程序实例中的其他流量之间的争用。对于为以下应用程序类型创建的工作负载、系统会自动建议并优化卷特征、例如I/O类型、区块大小、控制器所有权以及读写缓存。
+
** Microsoft SQL Server
** Microsoft Exchange Server
** 视频监控应用程序
** VMware ESXi (适用于要与虚拟机文件系统结合使用的卷)
+
您可以使用添加/编辑卷对话框查看建议的卷配置以及编辑、添加或删除系统建议的卷和特征。



* *其他(或不支持特定卷创建的应用程序)*- 其他工作负载使用的卷配置、您必须在创建与特定应用程序无关的工作负载时手动指定、或者如果您要在存储阵列上使用的应用程序没有内置优化功能、则必须手动指定。您必须使用添加/编辑卷对话框手动指定卷配置。




== 为什么我看不到所有卷、主机或主机集群？

具有已启用DA的基础卷的Snapshot卷不能分配给不支持数据保证(Data Assurance、DA)的主机。您必须先在基础卷上禁用DA、然后才能将快照卷分配给不支持DA的主机。

对于要将快照卷分配到的主机、请考虑以下准则：

* 如果主机通过不支持DA的I/O接口连接到存储阵列、则该主机将不支持DA。
* 如果主机集群至少有一个主机成员不支持DA、则此主机集群不支持DA。



NOTE: 您不能在与快照(一致性组、快照组、快照映像和快照卷)、卷副本、 和镜像。必须先删除所有关联的预留容量和快照对象、然后才能在基础卷上禁用DA。



== 为什么无法删除选定工作负载？

此工作负载由一组使用命令行界面(CLI)创建或从其他存储阵列迁移(导入/导出)的卷组成。因此、此工作负载中的卷不会与特定于应用程序的工作负载关联、因此无法删除此工作负载。



== 应用程序特定的工作负载如何帮助我管理存储阵列？

应用程序特定工作负载的卷特征决定了该工作负载如何与存储阵列的组件进行交互、并有助于确定给定配置下环境的性能。

应用程序是指SQL Server或Exchange等软件。您可以定义一个或多个工作负载来支持每个应用程序。对于某些应用程序、系统会自动建议一种可优化存储的卷配置。卷配置包括I/O类型、区块大小、控制器所有权以及读写缓存等特征。



== 要识别扩展的容量、我需要执行哪些操作？

如果增加卷的容量、则主机可能无法立即识别卷容量的增加。

大多数操作系统都会识别扩展后的卷容量、并在启动卷扩展后自动进行扩展。但是、有些可能不会。如果操作系统无法自动识别扩展的卷容量、则可能需要执行磁盘重新扫描或重新启动。

扩展卷容量后、必须手动增加文件系统大小以匹配。如何执行此操作取决于所使用的文件系统。

有关更多详细信息、请参见主机操作系统文档。



== 稍后要在何时使用分配主机选项？

如果要加快创建卷的过程、可以跳过主机分配步骤、使新创建的卷脱机初始化。

必须初始化新创建的卷。系统可以使用以下两种模式之一对其进行初始化：即即时可用格式(Immediate Available Format、IAF)后台初始化过程或脱机过程。

将卷映射到主机时、它会强制该组中所有初始化的卷过渡到后台初始化。此后台初始化过程允许并发主机I/O、这有时可能非常耗时。

如果未映射卷组中的任何卷、则会执行脱机初始化。脱机过程比后台进程快得多。



== 关于主机块大小要求、我需要了解哪些信息？

对于EF300和EF600系统、可以将卷设置为支持512字节或4KiB块大小(也称为"扇区大小")。您必须在创建卷期间设置正确的值。如果可能、系统会建议适当的默认值。

在设置卷块大小之前、请阅读以下限制和准则。

* 某些操作系统和虚拟机(尤其是VMware、目前)需要512字节的块大小、并且不支持4KiB、因此请确保在创建卷之前了解主机要求。通常、可以通过将卷设置为显示4KiB块大小来实现最佳性能；但是、请确保主机允许4KiB (或"4Kn")块。
* 为池或卷组选择的驱动器类型还决定了支持的卷块大小、如下所示：
+
** 如果使用写入512字节块的驱动器创建卷组、则只能创建包含512字节块的卷。
** 如果使用写入4KiB块的驱动器创建卷组、则可以创建包含512字节或4KiB块的卷。


* 如果阵列具有iSCSI主机接口卡、则所有卷都将限制为512字节的块(无论卷组块大小如何)。这是由于实施了特定的硬件造成的。
* 设置块大小后、您将无法更改块大小。如果需要更改块大小、则必须删除卷并重新创建它。




== 为什么需要创建主机集群？

如果要使两个或更多主机共享对同一组卷的访问、则需要创建主机集群。通常、各个主机都安装了集群软件来协调卷访问。



== 如何知道哪种主机操作系统类型正确？

主机操作系统类型字段包含主机的操作系统。您可以从下拉列表中选择建议的主机类型。

下拉列表中显示的主机类型取决于存储阵列型号和固件版本。最新版本会首先显示最常见的选项、最有可能是最合适的选项。此列表中的显示并不表示完全支持此选项。


NOTE: 有关主机支持的详细信息、请参见 http://mysupport.netapp.com/matrix["NetApp 互操作性表工具"^]。

列表中可能会显示以下某些主机类型：

|===
| 主机操作系统类型 | 操作系统(OS)和多路径驱动程序 


| Linux DM-MP (内核3.10或更高版本) | 支持使用设备映射程序多路径故障转移解决方案 和3.10或更高版本内核的Linux操作系统。 


| VMware ESXi | 支持使用VMware内置存储阵列类型策略模块sap_alUA运行原生 多路径插件(NMP)架构的VMware ESXi操作系统。 


| Windows (集群或非集群) | 支持未运行ATTO多路径驱动程序的Windows集群或非集群配置。 


| ATTO集群(所有操作系统) | 支持使用ATTO Technology、Inc.多路径驱动程序的所有集群配置。 


| Linux (Veritas DMP) | 支持使用Veritas DMP多路径解决方案 的Linux操作系统。 


| Linux (ATTO) | 支持使用ATTO Technology、Inc.多路径驱动程序的Linux操作系统。 


| Mac OS | 支持使用ATTO Technology、Inc.多路径驱动程序的Mac OS版本。 


| Windows (ATTO) | 支持使用ATTO Technology、Inc.多路径驱动程序的Windows操作系统。 


| IBM服务 | 支持IBM SAN卷控制器配置。 


| 出厂默认值 | 为存储阵列的初始启动预留。如果您的主机操作系统类型设置为出厂默认值、请将其更改为与所连接主机上运行的主机操作系统和多路径驱动程序匹配。 


| Linux DM-MP (Kernal 3.9或更早版本) | 支持使用具有3.9或更早内核的设备映射程序多路径故障转移解决方案 的Linux操作系统。 


| 窗口集群(已弃用) | 如果主机操作系统类型设置为此值、请改用Windows (集群或非集群)设置。 
|===


== 如何将主机端口与主机匹配？

如果要手动创建主机、则必须首先使用主机上可用的相应主机总线适配器(HBA)实用程序来确定与主机中安装的每个HBA关联的主机端口标识符。

获得此信息后、请从创建主机对话框中提供的列表中选择已登录到存储阵列的主机端口标识符。


CAUTION: 确保为要创建的主机选择适当的主机端口标识符。如果关联的主机端口标识符不正确、则可能会发生原因 从另一台主机意外访问此数据。



== 默认集群是什么？

默认集群是一个系统定义的实体、它允许登录到存储阵列的任何未关联主机端口标识符访问分配给默认集群的卷。

未关联的主机端口标识符是指与特定主机没有逻辑关联、但实际安装在主机中并登录到存储阵列的主机端口。


NOTE: 如果您希望主机对存储阵列中的某些卷具有特定访问权限、则不能使用默认集群。而是必须将主机端口标识符与其对应的主机相关联。此任务可以在创建主机操作期间手动完成。然后、将卷分配给单个主机或主机集群。

只有在外部存储环境有利于允许所有主机以及连接到存储阵列的所有已登录主机端口标识符都能够访问所有卷的特殊情况下、才应使用默认集群(完全访问模式) 而不是专门使存储阵列或用户界面知道这些主机。

最初、您只能通过命令行界面(CLI)将卷分配给默认集群。但是、在将至少一个卷分配给默认集群后、此实体(称为默认集群)将显示在用户界面中、您可以在此界面中管理此实体。



== 什么是冗余检查？

冗余检查可确定池或卷组中卷上的数据是否一致。如果池或卷组中的某个驱动器发生故障、则可以使用冗余数据快速重建替代驱动器上的信息。

一次只能对一个池或卷组执行此检查。卷冗余检查将执行以下操作：

* 扫描RAID 3卷、RAID 5卷或RAID 6卷中的数据块、然后检查每个块的冗余信息。(只能使用命令行界面将RAID 3分配给卷组。)
* 比较RAID 1镜像驱动器上的数据块。
* 如果控制器固件确定数据不一致、则返回冗余错误。



NOTE: 立即对同一个池或卷组运行冗余检查可能会出现发生原因 错误。要避免此问题、请等待一到两分钟、然后再对同一个池或卷组运行另一个冗余检查。



== 什么是保留容量？

保留容量是指池中为支持潜在驱动器故障而预留的容量(驱动器数量)。

创建池时、系统会根据池中的驱动器数量自动预留默认保留容量。

池会在重建期间使用保留容量、而卷组则会出于相同目的使用热备用驱动器。与热备用驱动器相比、保留容量方法有所改进、因为它可以更快地进行重建。对于热备用驱动器、保留容量会分布在池中的多个驱动器上、而不是分布在一个驱动器上、因此您不会受到一个驱动器的速度或可用性的限制。



== 哪种RAID级别最适合我的应用程序？

要最大程度地提高卷组的性能、必须选择适当的RAID级别。

您可以通过了解正在访问卷组的应用程序的读写百分比来确定适当的RAID级别。使用性能页面可获取这些百分比。



=== RAID级别和应用程序性能

RAID依靠一系列称为级别的配置来确定如何从驱动器写入和检索用户和冗余数据。每个RAID级别提供不同的性能功能。由于RAID 5和RAID 6配置具有出色的读取性能、读取百分比较高的应用程序在使用RAID 5卷或RAID 6卷时性能良好。

读取百分比较低(写入密集型)的应用程序在RAID 5卷或RAID 6卷上的性能较差。性能下降是由于控制器将数据和冗余数据写入RAID 5卷组或RAID 6卷组中的驱动器的方式造成的。

根据以下信息选择RAID级别。



==== RAID 0

*问题描述 ：*

* 非冗余条带化模式。
* RAID 0可在卷组中的所有驱动器之间对数据进行条带化。


*数据保护功能：*

* 不建议使用RAID 0来满足高可用性需求。RAID 0更适合非关键数据。
* 如果卷组中的一个驱动器发生故障、则所有关联卷都会发生故障、并且所有数据都将丢失。


*驱动器编号要求：*

* RAID级别0至少需要一个驱动器。
* RAID 0卷组可以包含30个以上的驱动器。
* 您可以创建一个包含存储阵列中所有驱动器的卷组。




==== RAID 1或RAID 10

*问题描述 ：*

* 条带化/镜像模式。


*工作原理：*

* RAID 1使用磁盘镜像将数据同时写入两个重复磁盘。
* RAID 10使用驱动器条带化功能在一组镜像驱动器对之间条带化数据。


*数据保护功能：*

* RAID 1和RAID 10可提供高性能和最佳数据可用性。
* RAID 1和RAID 10使用驱动器镜像从一个驱动器精确复制到另一个驱动器。
* 如果驱动器对中的一个驱动器发生故障、存储阵列可以立即切换到另一个驱动器、而不会丢失任何数据或服务。
* 单个驱动器故障会导致关联卷降级。镜像驱动器允许访问数据。
* 卷组中的驱动器对故障会导致所有关联卷出现故障、并且可能会发生数据丢失。


*驱动器编号要求：*

* RAID 1至少需要两个驱动器：一个驱动器用于用户数据、一个驱动器用于镜像数据。
* 如果选择四个或更多驱动器、则会在卷组中自动配置RAID 10：两个驱动器用于用户数据、两个驱动器用于镜像数据。
* 卷组中的驱动器数量必须为偶数。如果驱动器数量不是偶数、并且还有一些未分配的驱动器、请转到*池和卷组*向卷组添加其他驱动器、然后重试此操作。
* RAID 1和RAID 10卷组可以包含30个以上的驱动器。可以创建一个包含存储阵列中所有驱动器的卷组。




==== RAID 5

*问题描述 ：*

* 高I/O模式。


*工作原理：*

* 用户数据和冗余信息(奇偶校验)在驱动器之间进行条带化。
* 一个驱动器的等效容量用于提供冗余信息。


*数据保护功能*

* 如果RAID 5卷组中的一个驱动器发生故障、则所有关联卷都会降级。冗余信息允许仍访问数据。
* 如果RAID 5卷组中的两个或更多驱动器发生故障、则所有关联卷都会发生故障、并且所有数据都将丢失。


*驱动器编号要求：*

* 卷组中必须至少有三个驱动器。
* 通常、卷组中最多只能包含30个驱动器。




==== RAID 6

*问题描述 ：*

* 高I/O模式。


*工作原理：*

* 用户数据和冗余信息(双奇偶校验)在驱动器之间进行条带化。
* 两个驱动器的等效容量用于提供冗余信息。


*数据保护功能：*

* 如果RAID 6卷组中的一个或两个驱动器发生故障、则所有关联卷都会降级、但冗余信息仍允许访问数据。
* 如果RAID 6卷组中的三个或更多驱动器发生故障、则所有关联卷都会发生故障、并且所有数据都将丢失。


*驱动器编号要求：*

* 卷组中必须至少有五个驱动器。
* 通常、卷组中最多只能包含30个驱动器。



NOTE: 您不能更改池的RAID级别。用户界面会自动将池配置为RAID 6。



=== RAID级别和数据保护

RAID 1、RAID 5和RAID 6向驱动器介质写入冗余数据以实现容错。冗余数据可以是数据的副本(镜像)、也可以是从数据派生的错误更正代码。如果驱动器发生故障、您可以使用冗余数据快速重建替代驱动器上的信息。

您可以在一个卷组中配置一个RAID级别。该卷组的所有冗余数据都存储在该卷组中。卷组的容量等于成员驱动器的聚合容量减去为冗余数据预留的容量。冗余所需的容量取决于使用的RAID级别。



== 为什么某些驱动器不显示？

在添加容量对话框中、并非所有驱动器都可用于向现有池或卷组添加容量。

驱动器不符合条件的原因如下：

* 驱动器必须已取消分配、并且未启用安全保护。驱动器已属于另一个池、另一个卷组或配置为热备用磁盘不符合条件。如果某个驱动器未分配但已启用安全保护、则必须手动擦除该驱动器才能使其符合条件。
* 处于非最佳状态的驱动器不符合条件。
* 如果驱动器容量太小、则不符合条件。
* 驱动器介质类型必须在池或卷组中匹配。您不能混用以下内容：
+
** 采用固态磁盘(SSD)的硬盘驱动器(HDD)
** 采用SAS驱动器的NVMe
** 卷块大小为512字节和4 KiB的驱动器


* 如果池或卷组包含所有支持安全的驱动器、则不会列出不支持安全的驱动器。
* 如果池或卷组包含所有联邦信息处理标准(FIPS)驱动器、则不会列出非FIPS驱动器。
* 如果池或卷组包含支持所有数据保证(DA)的驱动器、并且池或卷组中至少有一个已启用DA的卷、则不支持DA的驱动器将不符合条件、因此无法将其添加到该池或卷组。但是、如果池或卷组中没有启用了DA的卷、则可以将不支持DA的驱动器添加到该池或卷组中。如果决定混用这些驱动器、请记住、您不能创建任何已启用DA的卷。



NOTE: 可以通过添加新驱动器或删除池或卷组来增加存储阵列中的容量。



== 为什么我不能增加我的保留容量？

如果已在所有可用容量上创建卷、则可能无法增加保留容量。

保留容量是指池中为支持潜在驱动器故障而预留的容量(驱动器数量)。创建池时、系统会根据池中的驱动器数量自动预留默认保留容量。如果已在所有可用容量上创建卷、则在不通过添加驱动器或删除卷向池添加容量的情况下、无法增加保留容量。

您可以从池和卷组更改保留容量。选择要编辑的池。单击*查看/编辑设置*、然后选择*设置*选项卡。


NOTE: 保留容量指定为多个驱动器、即使实际保留容量分布在池中的驱动器之间也是如此。



== 什么是数据保证？

数据保证(Data Assurance、DA)实施了T10保护信息(Protection Information、PI)标准、该标准可通过检查并更正在I/O路径上传输数据时可能发生的错误来提高数据完整性。

通常情况下、使用数据保证功能将检查控制器和驱动器之间I/O路径的部分。DA 功能在池和卷组级别提供。

启用此功能后、存储阵列会向卷中的每个数据块附加错误检查代码(也称为循环冗余检查或CRC)。移动数据块后、存储阵列会使用这些CRC代码来确定传输期间是否发生任何错误。可能损坏的数据既不会写入磁盘、也不会返回到主机。如果要使用DA功能、请在创建新卷时选择一个支持DA的池或卷组(在Pool and volume group candidates表中的* DA*旁边查找*是*)。

请确保使用支持DA的I/O接口将这些启用了DA的卷分配给主机。支持DA的I/O接口包括光纤通道、SAS、基于TCP/IP的iSCSI、NVMe/FC、NVMe/IB、 基于InfiniBand的NVMe/RoCE和iSER (适用于RDMA/IB的iSCSI扩展)。基于InfiniBand的SRP不支持DA。



== 什么是FDE/Fips安全性？

FDE/Fips安全性是指在写入期间对数据进行加密的安全驱动器、以及在读取期间使用唯一加密密钥对数据进行解密的驱动器。

这些支持安全的驱动器可防止未经授权访问从存储阵列中物理删除的驱动器上的数据。支持安全的驱动器可以是全磁盘加密(Full Disk Encryption、FDE)驱动器、也可以是联邦信息处理标准(Federal Information Processing Standard、FIPS)驱动器。FIPS驱动器已通过认证测试。


NOTE: 对于需要FIPS支持的卷、请仅使用FIPS驱动器。在卷组或池中混用FIPS和FDE驱动器将导致所有驱动器被视为FDE驱动器。此外、FDE驱动器不能添加到纯FIPS卷组或池中或用作备用磁盘。



== 什么是安全功能(驱动器安全)？

驱动器安全性是一项功能、可防止在从存储阵列中删除启用了安全功能的驱动器上的数据时未经授权进行访问。

这些驱动器可以是全磁盘加密(Full Disk Encryption、FDE)驱动器、也可以是联邦信息处理标准(Federal Information Processing Standard、FIPS)驱动器。



== 如何查看和解释所有SSD缓存统计信息？

您可以查看SSD缓存的标称统计信息和详细统计信息。

标称统计信息是详细统计信息的一部分。只有在将所有SSD统计信息导出到.csv文件时、才能查看详细统计信息。在查看和解释统计信息时、请记住、某些解释是通过结合统计信息得出的。



=== 标称统计信息

要查看SSD缓存统计信息、请转到*管理*页面。选择菜单：配置[配置池和卷组]。选择要查看统计信息的SSD缓存、然后选择菜单：更多(查看统计信息)。标称统计信息显示在"查看SSD缓存统计信息"对话框中。


NOTE: EF600或EF300存储系统不支持此功能。

此列表包含标称统计信息、这些统计信息是详细统计信息的一部分。



=== 详细统计信息

详细统计信息包括名义统计信息和其他统计信息。这些附加统计信息会与标称统计信息一起保存、但与标称统计信息不同、它们不会显示在"查看SSD缓存统计信息"对话框中。只有在将统计信息导出到.csv文件后、才能查看详细统计信息。

详细统计信息列在标称统计信息之后。



== 什么是磁盘架丢失保护和抽屉丢失保护？

磁盘架丢失保护和抽盒丢失保护是池和卷组的属性、可用于在单个磁盘架或抽盒发生故障时保持数据访问。



=== 磁盘架丢失保护

磁盘架是指包含驱动器或驱动器和控制器的机箱。磁盘架丢失保护功能可确保在与单个驱动器磁盘架完全失去通信时能够访问池或卷组中卷上的数据。完全失去通信的一个示例可能是驱动器架断电或两个I/O模块(IOM)均发生故障。


NOTE: 如果池或卷组中的驱动器已发生故障、则无法保证磁盘架丢失保护。在这种情况下、如果无法访问某个驱动器架以及池或卷组中的另一个驱动器、则会导致数据丢失。

磁盘架丢失保护的标准取决于保护方法、如下表所述。

|===
| 级别 | 磁盘架丢失保护的标准 | 所需的最小磁盘架数 


| 池 | 该池必须包含至少来自五个磁盘架的驱动器、并且每个磁盘架中的驱动器数量必须相等。磁盘架丢失保护不适用于高容量磁盘架；如果您的系统包含高容量磁盘架、请参阅"抽屉丢失保护"。 | 5. 


| RAID 6 | 卷组在一个抽屉中包含的驱动器不超过两个。 | 3. 


| RAID 3或RAID 5 | 卷组中的每个驱动器都位于一个单独的磁盘架中。 | 3. 


| RAID 1 | RAID 1对中的每个驱动器都必须位于一个单独的磁盘架中。 | 2. 


| RAID 0 | 无法实现磁盘架丢失保护。 | 不适用 
|===


=== 抽盒丢失保护

抽盒是拉出以访问驱动器的磁盘架的一个隔室。只有大容量磁盘架才具有抽盒。抽盒丢失保护功能可确保在与单个抽盒完全失去通信时能够访问池或卷组中卷上的数据。完全失去通信的一个示例可能是抽盒断电或抽盒内的内部组件发生故障。


CAUTION: 如果池或卷组中的驱动器已发生故障、则不保证提供抽盒丢失保护。在这种情况下、如果无法访问某个抽盒(以及池或卷组中的另一个驱动器)、则会导致数据丢失。

抽盒丢失保护的标准取决于保护方法、如下表所述：

|===
| 级别 | 抽盒丢失保护的标准 | 所需的最小抽盒数量 


| 池 | 候选池必须包含所有抽盒中的驱动器、并且每个抽盒中的驱动器数量必须相等。池中必须至少包含五个抽盒中的驱动器、并且每个抽盒中的驱动器数量必须相等。如果池包含15、20、25、30、35、 40、45、50、55或60个驱动器。首次创建后、可以将增量以5的倍数添加到池中。 | 5. 


| RAID 6 | 卷组在一个抽屉中包含的驱动器不超过两个。 | 3. 


| RAID 3或5 | 卷组中的每个驱动器都位于一个单独的抽盒中 | 3. 


| RAID 1 | 镜像对中的每个驱动器都必须位于一个单独的抽盒中。 | 2. 


| RAID 0 | 无法实现抽盒丢失保护。 | 不适用 
|===


== 如何维护磁盘架和抽屉丢失保护？

要为池或卷组维护磁盘架和抽屉丢失保护、请使用下表中指定的标准。

|===
| 级别 | 磁盘架/抽屉丢失保护的标准 | 所需的最小磁盘架/抽屉数 


| 池 | 对于磁盘架、池中一个磁盘架中的驱动器不能超过两个。对于抽盒、池中每个抽盒中必须包含相同数量的驱动器。 | 6个用于磁盘架5个用于抽屉 


| RAID 6 | 卷组在一个磁盘架或抽屉中包含的驱动器不超过两个。 | 3. 


| RAID 3或RAID 5 | 卷组中的每个驱动器都位于一个单独的磁盘架或抽屉中。 | 3. 


| RAID 1 | 镜像对中的每个驱动器都必须位于单独的磁盘架或抽屉中。 | 2. 


| RAID 0 | 无法实现磁盘架/抽屉丢失保护。 | 不适用 
|===

NOTE: 如果池或卷组中的驱动器已发生故障、则不会保持磁盘架/抽屉丢失保护。在这种情况下、如果无法访问某个驱动器架或抽盒、进而无法访问池或卷组中的另一个驱动器、则会导致数据丢失。



== 什么是池的优化容量？

如果未分配一部分容量、SSD驱动器的使用寿命将会延长、并且最大写入性能也会提高。

对于与池关联的驱动器、未分配的容量由池的保留容量、可用容量(卷未使用的容量)以及作为额外优化容量而预留的部分可用容量组成。额外的优化容量可通过减少可用容量来确保最低的优化容量级别、因此不可用于创建卷。

创建池时、系统会生成一个建议的优化容量、以便在性能、驱动器使用寿命和可用容量之间实现平衡。通过位于Pool Settings对话框中的Additional Optimization Capacity滑块、可以调整池的优化容量。调整滑块可以提高性能和驱动器磨损寿命、而不会影响可用容量、也不会影响性能和驱动器磨损寿命。


NOTE: 附加优化容量滑块仅适用于EF600和EF300存储系统。



== 卷组的优化容量是多少？

如果未分配一部分容量、SSD驱动器的使用寿命将会延长、并且最大写入性能也会提高。

对于与卷组关联的驱动器、未分配的容量由卷组的可用容量(卷未使用的容量)以及作为优化容量预留的部分可用容量组成。额外的优化容量可通过减少可用容量来确保最低的优化容量级别、因此不可用于创建卷。

创建卷组时、系统会生成一个建议的优化容量、以便在性能、驱动器使用寿命和可用容量之间取得平衡。通过"卷组设置"对话框中的"其他优化容量"滑块、可以调整卷组的优化容量。调整滑块可以提高性能和驱动器磨损寿命、而不会影响可用容量、也不会影响性能和驱动器磨损寿命。


NOTE: 其他优化容量滑块仅适用于EF600和EF300存储系统。



== 什么是资源配置功能？

资源配置是EF300和EF600存储阵列中提供的一项功能、可在不执行后台初始化过程的情况下立即使用卷。

资源配置卷是SSD卷组或池中的厚卷、在创建卷时会分配(分配给卷)驱动器容量、但会取消分配(取消映射)驱动器块。相比之下、在传统厚卷中、所有驱动器块都会在后台卷初始化操作期间映射或分配、以便初始化数据保证保护信息字段并使每个RAID条带中的数据和RAID奇偶校验保持一致。对于资源配置的卷、不会进行有时间限制的后台初始化。而是在首次写入条带中的卷块时初始化每个RAID条带。

只有SSD卷组和池支持资源配置的卷、其中组或池中的所有驱动器都支持NVMe已取消分配或未写入逻辑块错误启用(DULBE")错误恢复功能。创建资源配置的卷时、分配给该卷的所有驱动器块都会进行取消分配(未映射)。此外、主机还可以使用NVMe Dataset Management命令取消分配卷中的逻辑块。取消分配块可以延长SSD的使用寿命并提高最大写入性能。性能提升因驱动器型号和容量而异。



== 关于资源配置卷功能、我需要了解哪些信息？

资源配置是EF300和EF600存储阵列中提供的一项功能、可在不执行后台初始化过程的情况下立即使用卷。


NOTE: 此时、资源配置功能不可用。在某些视图中、组件可能会报告为具有资源配置功能、但创建资源配置卷的功能已被禁用、直到可以在将来的更新中重新启用为止。



=== 资源配置的卷

资源配置卷是SSD卷组或池中的厚卷、在创建卷时会分配(分配给卷)驱动器容量、但会取消分配(取消映射)驱动器块。相比之下、在传统厚卷中、所有驱动器块都会在后台卷初始化操作期间映射或分配、以便初始化数据保证保护信息字段并使每个RAID条带中的数据和RAID奇偶校验保持一致。对于资源配置的卷、不会进行有时间限制的后台初始化。而是在首次写入条带中的卷块时初始化每个RAID条带。

只有SSD卷组和池支持资源配置的卷、其中组或池中的所有驱动器都支持NVMe已取消分配或未写入逻辑块错误启用(DULBE")错误恢复功能。创建资源配置的卷时、分配给该卷的所有驱动器块都会进行取消分配(未映射)。此外、主机还可以使用NVMe Dataset Management命令取消分配卷中的逻辑块。取消分配块可以延长SSD的使用寿命并提高最大写入性能。性能提升因驱动器型号和容量而异。



=== 启用和禁用此功能

在驱动器支持DULBE"的系统上、默认情况下会启用资源配置。您可以从"池和卷组"中禁用此默认设置。禁用资源配置是对现有卷执行的一项永久操作、无法反转(即、您无法为这些卷组和池重新启用资源配置)。

但是、如果要为您创建的任何新卷重新启用资源配置、则可以从菜单：Settings[系统]执行此操作。请注意、在重新启用资源配置时、仅会影响新创建的卷组和池。任何现有卷组和池将保持不变。如果需要、您还可以从菜单：Settings[系统]再次禁用资源配置。



== 内部安全密钥与外部安全密钥管理有何区别？

在实施驱动器安全功能时、当从存储阵列中删除启用了安全保护的驱动器时、您可以使用内部安全密钥或外部安全密钥锁定数据。

安全密钥是一个字符串、在存储阵列中启用了安全保护的驱动器和控制器之间共享。内部密钥会保留在控制器的永久性内存上。外部密钥使用密钥管理互操作性协议(Key Management Interoperability Protocol、KMIP)在单独的密钥管理服务器上进行维护。



== 在创建安全密钥之前、我需要了解哪些信息？

安全密钥由存储阵列中的控制器和启用了安全保护的驱动器共享。如果从存储阵列中删除了启用了安全保护的驱动器、则安全密钥可防止数据遭受未经授权的访问。

您可以使用以下方法之一创建和管理安全密钥：

* 控制器永久性内存上的内部密钥管理。
* 外部密钥管理服务器上的外部密钥管理。




== 内部密钥管理

内部密钥会在控制器永久性内存上的不可访问位置进行维护和"隐藏"。在创建内部安全密钥之前、必须执行以下操作：

. 在存储阵列中安装支持安全保护的驱动器。这些驱动器可以是全磁盘加密(Full Disk Encryption、FDE)驱动器或联邦信息处理标准(Federal Information Processing Standard、FIPS)驱动器。
. 确保已启用驱动器安全功能。如有必要、请联系您的存储供应商、了解有关启用驱动器安全功能的说明。


然后、您可以创建内部安全密钥、其中包括定义标识符和密码短语。标识符是与安全密钥关联的字符串、存储在控制器以及与该密钥关联的所有驱动器上。密码短语用于对安全密钥进行加密、以用于备份。完成后、安全密钥将存储在控制器上不可访问的位置。然后、您可以创建启用了安全保护的卷组或池、也可以对现有卷组和池启用安全性。



=== 外部密钥管理

外部密钥使用密钥管理互操作性协议(Key Management Interoperability Protocol、KMIP)在单独的密钥管理服务器上进行维护。在创建外部安全密钥之前、必须执行以下操作：

. 在存储阵列中安装支持安全保护的驱动器。这些驱动器可以是全磁盘加密(Full Disk Encryption、FDE)驱动器或联邦信息处理标准(Federal Information Processing Standard、FIPS)驱动器。
. 确保已启用驱动器安全功能。如有必要、请联系您的存储供应商、了解有关启用驱动器安全功能的说明
. 获取签名的客户端证书文件。客户端证书用于验证存储阵列的控制器、以便密钥管理服务器可以信任其KMIP请求。
+
.. 首先、您需要完成并下载客户端证书签名请求(CSR)。转到菜单：设置[证书>密钥管理>完成CSR]。
.. 接下来、您需要从密钥管理服务器信任的CA请求签名客户端证书。(您也可以使用下载的CSR文件从密钥管理服务器创建和下载客户端证书。)
.. 拥有客户端证书文件后、将该文件复制到要访问System Manager的主机。


. 从密钥管理服务器检索证书文件、然后将该文件复制到要访问System Manager的主机。密钥管理服务器证书用于验证密钥管理服务器、以便存储阵列可以信任其IP地址。您可以对密钥管理服务器使用根证书、中间证书或服务器证书。


然后、您可以创建外部密钥、其中包括定义密钥管理服务器的IP地址以及用于KMIP通信的端口号。在此过程中、您还可以加载证书文件。完成后、系统将使用您输入的凭据连接到密钥管理服务器。然后、您可以创建启用了安全保护的卷组或池、也可以对现有卷组和池启用安全性。



== 为什么需要定义密码短语？

密码短语用于对存储在本地管理客户端上的安全密钥文件进行加密和解密。如果没有密码短语、则无法对安全密钥进行解密、并使用此安全密钥从启用了安全功能的驱动器中解锁数据、如果此驱动器重新安装在另一个存储阵列中。
