---
sidebar: sidebar 
permalink: vcenter-plugin/san-spvc-ic-storage-array-discovery.html 
keywords: discover arrays vCenter plugin, discover storage resources Plugin for vCenter, resolve certificates vCenter plugin 
summary: 使用适用于 vCenter 的插件界面发现网络中阵列的 IP 地址。 
---
= 在适用于vCenter的SANtricity存储插件中发现存储阵列
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
要显示和管理存储资源，您必须使用适用于 vCenter 的存储插件界面发现网络中阵列的 IP 地址。

.开始之前
* 您必须知道阵列控制器的网络 IP 地址（或地址范围）。
* 必须正确设置和配置存储阵列，并且您必须知道存储阵列登录凭据（用户名和密码）。




== 第 1 步：输入要发现的网络地址

.步骤
. 在 Manage 页面中，选择 * 添加 / 发现 * 。
+
此时将显示输入网络地址范围对话框。

. 执行以下操作之一：
+
** 要发现一个阵列，请选择 * 发现单个存储阵列 * 单选按钮，然后输入存储阵列中某个控制器的 IP 地址。
** 要发现多个存储阵列，请选择 * 发现网络范围内的所有存储阵列 * 单选按钮，然后输入起始网络地址和结束网络地址，以便在本地子网络中搜索。


. 单击 * 启动发现 * 。
+
发现过程开始时，对话框会在发现存储阵列时显示这些阵列。完成发现过程可能需要几分钟时间。

+
如果未发现任何可管理的阵列，请验证这些存储阵列是否已正确连接到您的网络，以及其分配的地址是否在范围内。单击 * 新发现参数 * 以返回到 " 添加 / 发现 " 页面。

. 选中要添加到管理域的任何存储阵列旁边的复选框。
+
系统会对要添加到管理域的每个阵列执行凭据检查。在继续操作之前，您可能需要解决不可信证书的任何问题。

. 单击 * 下一步 * 继续执行向导中的下一步。
+
如果存储阵列具有有效证书，请转至 <<第 3 步：提供密码>>。

+
如果任何存储阵列没有有效证书，则会显示解析自签名证书对话框。转至 <<第 2 步：在发现期间解析不可信的证书>>。

+
如果要导入 CA 签名的证书，请退出发现向导并单击左侧面板中的 * 证书管理 * 。有关详细说明，请参见联机帮助。





== 第 2 步：在发现期间解析不可信的证书

在继续执行发现过程之前，您必须解决任何证书问题。

. 如果 " 解析自签名证书 " 对话框打开，请查看为不可信证书显示的信息。有关详细信息，您还可以单击表最末尾的省略号，然后从弹出菜单中选择 * 查看 * 。
. 执行以下操作之一：
+
** 如果您信任与发现的存储阵列的连接，请单击 * 下一步 * ，然后单击 * 是 * 确认并继续到向导中的下一个对话框。自签名证书将标记为可信证书，存储阵列将添加到插件中。
** 如果您不相信与存储阵列的连接，请选择 * 取消 * 并在添加任何存储阵列之前验证每个存储阵列的安全证书策略。


. 单击 * 下一步 * 继续执行向导中的下一步。




== 第 3 步：提供密码

作为发现的最后一步，您必须输入要添加到管理域的存储阵列的密码。

. 对于每个已发现的阵列，请在字段中输入其管理员密码。
. 单击 * 完成 * 。
+
系统可能需要几分钟才能连接到指定的存储阵列。完成此过程后，存储阵列将添加到管理域中并与选定组（如果指定）关联。


