---
sidebar: sidebar 
permalink: vcenter-plugin/san-spvc-ic-installation.html 
keywords: install vCenter plugin, installing vCenter plugin, vCenter plugin, 
summary: 安装或升级适用于vCenter的SANtricity 存储插件。 
---
= 安装或升级适用于vCenter的SANtricity存储插件
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
按照以下步骤安装适用于vCenter的存储插件并验证插件注册。您也可以按照以下说明升级此插件。



== 查看安装前提条件

请确保您的系统满足中的要求 link:san-spvc-ic-reqs.html["查看安装和升级要求"]。


NOTE: 升级过程不会保留*。vcenter.properties*文件。如果要升级、则必须在升级之前取消注册此插件。升级成功后、您可以将此插件重新注册到vCSA。



== 安装插件软件

要安装插件软件，请执行以下操作：

. 将安装程序文件复制到要用作应用程序服务器的主机，然后访问下载安装程序的文件夹。
. 双击安装文件：
+
`santriciity_storage_vcenterplugin-windows_x64- nn.nn.nnnn.exe`

+
在上述文件名中， `nn.nn.nn.nnnn` 表示版本号。

. 安装开始后、按照屏幕上的提示启用多项功能并输入一些配置参数。如有必要，您可以稍后在配置文件中更改其中任何一个选项。
+

NOTE: 在升级期间、系统不会提示您输入配置参数。

+

NOTE: 在安装期间、系统会提示您进行证书验证。如果要在插件和存储阵列之间强制执行证书验证、请保持选中状态。通过此强制实施，系统会检查存储阵列证书，使其受插件的信任。如果证书不可信，则不允许将其添加到插件中。如果要覆盖证书验证，请取消选中此复选框，以便可以使用自签名证书将所有存储阵列添加到插件中。要了解有关证书的详细信息，请参阅插件界面中提供的联机帮助。

. 出现Webserver started消息时、单击*确定*完成安装、然后单击*完成*。
. 运行 * 服务 .msc* 命令验证是否已成功安装应用程序服务器。
. 验证是否已安装应用程序服务器（ VCP ）服务 * 适用于 vCenter 的 NetApp SANtricity 存储插件 * ，并且此服务已启动。
+

NOTE: 如有必要，您可以在安装后更改证书验证和 Web 服务端口设置。从安装目录中，打开 wsconfig.xml 文件。要删除存储阵列上的证书验证，请将 `env` key ， `trust.all.arrays` 更改为 `true` 。要更改 Web 服务端口，请将 `sslport` 值修改为 0-65535 范围内的所需端口值。确保使用的端口号未绑定到其他进程。完成后，保存所做的更改并重新启动插件 Web 服务器。如果在将插件注册到 vCSA 后插件 Web 服务器的端口值发生更改，则必须取消注册并重新注册插件，以便 vCSA 能够通过更改后的端口与插件 Web 服务器进行通信。





== 将此插件注册到 vCenter Server 设备

安装插件软件后，请向 vCSA 注册此插件。


NOTE: 此插件一次只能注册到一个 vCSA 。要注册到其他vCSA、您必须从当前vCSA中取消注册此插件、然后从应用程序主机中卸载它。然后、您可以重新安装此插件并将其注册到另一个vCSA。

. 通过命令行打开提示符并导航到以下目录：
+
` <install directory>\vCenter-register\bin`

. 执行 * vCenter-register.bat* 文件： `vcenter-register.bat ^ -action registerPlugin ^ -vcenterHostname <vCenter FQDN> ^ -username <Administrator username> ^`
. 验证脚本是否成功。


这些日志将保存到 ` %install_dir%/log/vc-registration.log` 中。



== 验证插件注册

安装插件并执行注册脚本后，验证此插件是否已成功注册到 vCenter Server 设备。

. 打开 vCenter Server 设备的 vSphere Client 。
. 在菜单栏上，选择菜单：管理员 [ 客户端插件 ] 。
. 确保适用于vCenter的存储插件列为*已启用*。
+
如果插件列为 Disabled ，并显示一条错误消息，指出它无法与应用程序服务器通信，请验证为应用程序服务器定义的端口号是否已启用，以便通过可能正在使用的任何防火墙。默认应用程序服务器传输控制协议（ TCP ）端口号为 8445 。


