---
sidebar: sidebar 
permalink: vcenter-plugin/san-spvc-ic-storage-provisioning.html 
keywords: create volumes vCenter plugin, provision Plugin for vCenter, vCenter plugin storage provisioning, vCenter plugin host 
summary: 使用适用于 vCenter 的插件创建卷，将卷分配给主机，然后将卷分配给数据存储库。 
---
= 在插件中配置存储
:hardbreaks:
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
要配置存储，请创建卷，将卷分配给主机，然后将卷分配给数据存储库。


NOTE: 有关存储配置的详细信息，请参见插件界面中提供的联机帮助。



== 创建卷

卷是一种数据容器，用于管理和组织存储阵列上的存储空间。您可以使用存储阵列上的可用存储容量创建卷，这有助于组织系统的资源。" 卷 " 的概念类似于在计算机上使用文件夹 / 目录来组织文件以实现快速访问。

卷是主机唯一可见的数据层。在 SAN 环境中，卷会映射到逻辑单元号（ LUN ）。这些 LUN 用于保存可使用存储阵列支持的一个或多个主机访问协议访问的用户数据。

.步骤
. 从管理页面中，选择存储阵列。
. 选择菜单：配置 [ 管理卷 ] 。
. 选择菜单：创建 [ 卷 ] 。
+
此时将显示选择主机对话框。

. 从下拉列表中，选择要将卷分配到的特定主机或主机集群，或者选择稍后再分配主机或主机集群。
. 要继续为选定主机或主机集群创建卷，请单击 * 下一步 * 。
+
此时将显示选择工作负载对话框。工作负载包含具有类似特征的卷，这些卷根据工作负载支持的应用程序类型进行了优化。您可以定义工作负载，也可以选择现有工作负载。

. 执行以下操作之一：
+
** 选择 * 为现有工作负载创建卷 * 选项，然后从下拉列表中选择工作负载。
** 选择 * 创建新工作负载 * 选项为支持的应用程序或 " 其他 " 应用程序定义新的工作负载，然后执行以下步骤：
+
... 从下拉列表中，选择要为其创建新工作负载的应用程序的名称。如果未列出要在此存储阵列上使用的应用程序，请选择 " 其他 " 条目之一。
... 输入要创建的工作负载的名称。




. 单击 * 下一步 * 。如果您的工作负载与支持的应用程序类型关联，请输入所请求的信息；否则，请转到下一步。
+
此时将显示添加 / 编辑卷对话框。在此对话框中，您可以从符合条件的池或卷组创建卷。对于每个符合条件的池和卷组，将显示可用驱动器数和总可用容量。对于某些特定于应用程序的工作负载，每个符合条件的池或卷组都会根据建议的卷配置显示建议的容量，并以 GiB 显示剩余可用容量。对于其他工作负载，在将卷添加到池或卷组并指定报告的容量时，将显示建议的容量。

. 开始添加卷之前，请阅读下表中的准则。
+
|===
| 字段 | Description 


 a| 
可用容量
 a| 
由于卷是从池或卷组创建的，因此您选择的池或卷组必须具有足够的可用容量。



 a| 
数据保证（ DA ）
 a| 
要创建启用了 DA 的卷，您计划使用的主机连接必须支持 DA 。

** 如果要创建启用了 DA 的卷，请选择一个支持 DA 的池或卷组（在 Pool and volume group candidates 表的 "DA" 旁边查找是）。
** DA 功能在池和卷组级别提供。DA 保护功能可检查并更正数据通过控制器向下传输到驱动器时可能发生的错误。为新卷选择支持 DA 的池或卷组可确保检测到并更正任何错误。
** 如果存储阵列中控制器上的任何主机连接不支持 DA ，则关联的主机将无法访问已启用 DA 的卷上的数据。




 a| 
驱动器安全性
 a| 
要创建启用了安全保护的卷，必须为存储阵列创建安全密钥。

** 如果要创建启用了安全的卷，请选择一个支持安全的池或卷组（在 Pool and volume group candidates 表中，查找 "Secure-capable" 旁边的是）。
** 驱动器安全功能在池和卷组级别提供。支持安全的驱动器可防止未经授权访问从存储阵列中物理删除的驱动器上的数据。启用了安全保护的驱动器会在写入期间对数据进行加密，并在读取期间使用唯一的加密密钥对数据进行解密。
** 池或卷组可以同时包含支持安全和不支持安全的驱动器，但所有驱动器都必须具有安全功能才能使用其加密功能。




 a| 
资源配置
 a| 
要创建资源配置的卷，所有驱动器都必须是具有已取消分配或未写入逻辑块错误（ DULBE" ）选项的 NVMe 驱动器。

|===
. 根据您在上一步中选择的是其他工作负载还是应用程序专用工作负载，选择以下操作之一：
+
** * 其他 * —单击要用于创建一个或多个卷的每个池或卷组中的 * 添加新卷 * 。
** * 应用程序专用工作负载 * —单击 * 下一步 * 接受系统为选定工作负载建议的卷和特征，或者单击 * 编辑卷 * 更改，添加或删除系统为选定工作负载建议的卷和特征。
+
此时将显示以下字段。

+
|===
| 字段 | Description 


 a| 
卷名称
 a| 
在卷创建序列期间，系统会为卷分配默认名称。您可以接受默认名称，也可以提供一个更具描述性的名称来指示卷中存储的数据类型。



 a| 
已报告容量
 a| 
定义新卷的容量以及要使用的容量单位（ MIB ， GiB 或 TiB ）。对于厚卷，最小容量为 1 MiB ，最大容量由池或卷组中驱动器的数量和容量决定。池中的容量以 4 GiB 为增量进行分配。分配的容量不是 4 GiB 的倍数，但不可用。要确保整个容量可用，请以 4 GiB 为增量指定容量。如果存在不可用的容量，则要重新获得该容量，唯一的方法是增加卷的容量。



 a| 
卷类型
 a| 
如果选择了应用程序专用工作负载，则会显示卷类型字段。这表示为特定于应用程序的工作负载创建的卷类型。



 a| 
卷块大小（仅限 EF300 和 EF600 ）
 a| 
显示了可为卷创建的块大小：

*** 512 – 512 字节
*** 4 k – 4 ， 096 字节




 a| 
区块大小
 a| 
显示了分段大小调整设置，此设置仅适用于卷组中的卷。您可以更改区块大小以优化性能。

* 允许的分段大小转换 * —系统将确定允许的分段大小转换。与当前区块大小的过渡不适当的区块大小在下拉列表中不可用。允许的过渡通常是当前区块大小的两倍或一半。例如，如果当前卷分段大小为 32 KiB ，则允许使用新的卷分段大小 16 KiB 或 64 KiB 。

* 已启用 SSD 缓存的卷 * —您可以为已启用 SSD 缓存的卷指定 4-KiB 分段大小。确保仅为支持 SSD 缓存且处理小块 I/O 操作的卷（例如， 16 KiB I/O 块大小或更小）选择 4-KiB 区块大小。如果为处理大型块顺序操作且已启用 SSD 缓存的卷选择 4 KiB 作为分段大小，则性能可能会受到影响。

* 更改区块大小所需的时间 * —更改卷区块大小所需的时间取决于以下变量：

*** 主机的 I/O 负载
*** 卷的修改优先级
*** 卷组中的驱动器数量
*** 驱动器通道的数量
*** 存储阵列控制器的处理能力


更改卷的区块大小时， I/O 性能会受到影响，但数据仍可用。



 a| 
支持安全保护
 a| 
只有当池或卷组中的驱动器支持加密时， " 支持安全 " 旁边才会显示 * 是 * 。驱动器安全性可防止未经授权访问从存储阵列中物理删除的驱动器上的数据。只有在启用了驱动器安全功能且为存储阵列设置了安全密钥时，此选项才可用。池或卷组可以同时包含支持安全和不支持安全的驱动器，但所有驱动器都必须具有安全功能才能使用其加密功能。



| da. | 只有当池或卷组中的驱动器支持数据保证（ Data Assurance ， DA ）时， "DA" 旁边才会显示 * 是 * 。DA 可提高整个存储系统的数据完整性。通过 DA ，存储阵列可以检查在数据通过控制器向下传输到驱动器时可能发生的错误。对新卷使用 DA 可确保检测到任何错误。 
|===


. 要继续对选定应用程序执行卷创建序列，请单击 * 下一步 * 。
. 在最后一步中，查看要创建的卷的摘要，并进行任何必要的更改。要进行更改，请单击 * 返回 * 。对卷配置感到满意后，单击 * 完成 * 。




== 创建主机访问权限并分配卷

可以自动或手动创建主机：

* * 自动 * —主机上下文代理（ HCA ）会为基于 SCSI （而不是 NVMe-oF ）的主机启动自动主机创建。HCA 是一个实用程序，您可以在连接到存储阵列的每个主机上安装该实用程序。安装了 HCA 的每个主机都会通过 I/O 路径将其配置信息推送到存储阵列控制器。根据主机信息，控制器会自动创建主机以及关联的主机端口并设置主机类型。如果需要，您可以对主机配置进行任何其他更改。HCA 执行自动检测后，主机将自动配置以下属性：
+
** 从主机的系统名称派生的主机名。
** 与主机关联的主机标识符端口。
** 主机的主机操作系统类型。





NOTE: 可从获取适用于 Linux 和 Windows 的 Host Context Agent 软件 https://mysupport.netapp.com/site/downloads["NetApp 支持—下载"^]。


NOTE: 主机作为独立主机创建； HCA 不会自动创建或添加到主机集群。

* * 手动 * —在手动创建主机期间，您可以通过从列表中选择主机端口标识符或手动输入这些标识符来关联主机端口标识符。创建主机后，如果您计划共享对卷的访问，则可以为其分配卷或将其添加到主机集群。




==== 使用 HCA 自动发现主机

您可以允许主机上下文代理（ Host Context Agent ， HCA ）自动检测主机，然后验证信息是否正确。

.步骤
. 从管理页面中，选择具有主机连接的存储阵列。
. 选择菜单：配置 [ 配置主机 ] 。
+
此时将打开配置主机页面。

. 选择菜单： Storage[Hosts] 。
+
此表列出了自动创建的主机。

. 验证 HCA 提供的信息是否正确（名称，主机类型，主机端口标识符）。
. 如果需要更改任何信息，请选择主机，然后单击 * 查看 / 编辑设置 * 。




==== 手动创建主机

请阅读以下准则：

* 您必须已在环境中添加或发现存储阵列。
* 您必须定义与主机关联的主机标识符端口。
* 请确保提供与主机分配的系统名称相同的名称。
* 如果您选择的名称已在使用中，则此操作不会成功。
* 名称长度不能超过 30 个字符。


.步骤
. 从管理页面中，选择具有主机连接的存储阵列。
. 选择菜单：配置 [ 配置主机 ] 。
+
此时将打开配置主机页面。

. 单击菜单：创建 [ 主机 ] 。
+
此时将显示创建主机对话框。

. 根据需要选择主机设置。
+
|===
| 字段 | Description 


 a| 
Name
 a| 
键入新主机的名称。



 a| 
主机操作系统类型
 a| 
从下拉列表中选择新主机上运行的操作系统。



 a| 
主机接口类型
 a| 
（可选）如果存储阵列支持多种类型的主机接口，请选择要使用的主机接口类型。



 a| 
主机端口
 a| 
执行以下操作之一：

** * 选择 I/O 接口 * 。通常，主机端口应已登录并可从下拉列表中使用。您可以从列表中选择主机端口标识符。
** * 手动添加 * 。如果列表中未显示主机端口标识符，则表示主机端口尚未登录。可以使用 HBA 实用程序或 iSCSI 启动程序实用程序来查找主机端口标识符并将其与主机关联。


您可以手动输入主机端口标识符，也可以将它们从实用程序（一次一个）复制 / 粘贴到主机端口字段中。

您必须一次选择一个主机端口标识符才能将其与主机关联，但您可以继续选择与主机关联的任意数量的标识符。每个标识符都会显示在主机端口字段中。如有必要，您还可以通过选择标识符旁边的 X 来删除此标识符。



 a| 
设置 CHAP 启动程序密钥
 a| 
（可选）如果您选择或手动输入具有 iSCSI IQN 的主机端口，并且希望要求尝试访问存储阵列的主机使用质询握手身份验证协议（ CHAP ）进行身份验证，请选中设置 CHAP 启动程序密钥复选框。对于您选择或手动输入的每个 iSCSI 主机端口，请执行以下操作：

** 输入在每个 iSCSI 主机启动程序上为 CHAP 身份验证设置的相同 CHAP 密钥。如果您使用相互 CHAP 身份验证（双向身份验证，可使主机向存储阵列验证自身，并使存储阵列向主机验证自身），则还必须在初始设置或通过更改设置为存储阵列设置 CHAP 密钥。
** 如果不需要主机身份验证，请将此字段留空。


目前，唯一使用的 iSCSI 身份验证方法是 CHAP 。

|===
. 单击 * 创建 * 。
. 如果需要更新主机信息，请从表中选择主机，然后单击 * 查看 / 编辑设置 * 。
+
成功创建主机后，系统会为为为主机配置的每个主机端口创建一个默认名称（用户标签）。默认别名为 ` < 主机名端口号 >` 。例如，为主机 IPT 创建的第一个端口的默认别名为 `ipt_1` 。

. 接下来，您必须将卷分配给主机或主机集群，以便用于 I/O 操作。选择菜单：配置 [ 配置主机 ] 。
+
此时将打开配置主机页面。

. 选择要将卷分配到的主机或主机集群，然后单击 * 分配卷 * 。
+
此时将显示一个对话框，其中列出了可分配的所有卷。您可以对任意列进行排序，也可以在筛选器框中键入某些内容，以便于查找特定卷。

. 选中要分配的每个卷旁边的复选框，或者选中表标题中的复选框以选择所有卷。
. 单击 * 分配 * 以完成此操作。
+
系统将执行以下操作：

+
** 分配的卷将收到下一个可用的 LUN 编号。主机使用此 LUN 编号来访问此卷。
** 用户提供的卷名称将显示在与主机关联的卷列表中。如果适用，出厂配置的访问卷也会显示在与主机关联的卷列表中。






== 在 vSphere Client 中创建数据存储库

要在 vSphere Client 中创建数据存储库，请参见 VMware 文档中心中的以下主题：

* https://docs.vmware.com/en/VMware-vSphere/6.0/com.vmware.vsphere.hostclient.doc/GUID-7EB0CE06-02DD-4B31-85C7-E54993CC06DC.html["在 vSphere Client 中创建 VMFS 数据存储库"^]




=== 通过增加卷容量来增加现有数据存储库的容量

您可以使用池或卷组中的可用容量来增加卷的报告容量（向主机报告的容量）。要了解有关池和卷组的详细信息，请参见插件的联机帮助。

请确保：

* 卷的关联池或卷组具有足够的可用容量。
* 卷处于最佳状态，不处于任何修改状态。
* 卷中未使用任何热备用驱动器。（仅适用于卷组中的卷。）



NOTE: 只有某些操作系统才支持增加卷的容量。如果在不支持 LUN 扩展的主机操作系统上增加卷容量，则扩展的容量将不可用，并且无法还原原始卷容量。

.步骤
. 导航到 vSphere Client 中的插件。
. 在插件中，选择所需的存储阵列。
. 单击 * 配置 * 并选择 * 管理卷 * 。
. 选择要增加容量的卷，然后选择 * 增加容量 * 。
+
此时将显示确认增加容量对话框。

. 选择 * 是 * 继续。
+
此时将显示增加报告的容量对话框。

+
此对话框显示卷当前报告的容量以及卷关联的池或卷组中可用的容量。

. 使用 * 通过添加增加报告容量 ...* 框向当前可用报告容量添加容量。您可以将容量值更改为以兆字节（ MiB ），吉字节（ GiB ）或太字节（ TiB ）为单位显示。
. 单击 * 增加 * 。
. 查看近期任务窗格，了解当前正在对选定卷运行的增加容量操作的进度。此操作可能会很长，并且可能会影响系统性能。
. 卷容量完成后，您必须手动增加 VMFS 大小，使其与以下主题中所述的大小一致：
+
** https://docs.vmware.com/en/VMware-vSphere/6.0/com.vmware.vsphere.hostclient.doc/GUID-B0D89816-02E5-4C42-AAFC-19751800A284.html["增加 vSphere Client 中的 VMFS 数据存储库容量"^]






=== 通过添加卷来增加现有数据存储库的容量

. 您可以通过添加卷来增加数据存储库的容量。按照 _Create volumes_ 中的步骤进行操作。
. 接下来，将卷分配给所需主机以增加数据存储库的容量。请参见以下主题：
+
** https://docs.vmware.com/en/VMware-vSphere/6.0/com.vmware.vsphere.hostclient.doc/GUID-B0D89816-02E5-4C42-AAFC-19751800A284.html["增加 vSphere Client 中的 VMFS 数据存储库容量"^]



