---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-use-ca-signed-certificates.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 获取并导入CA签名证书、以安全访问托管适用于vCenter的存储插件的管理系统。 
---
= 使用CA签名的证书
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以获取并导入CA签名的证书、以安全访问托管适用于vCenter的存储插件的管理系统。

使用CA签名证书分为三步操作步骤 ：

*  1: Complete a CSR file。
*  2: Submit CSR file。
*  3: Import management certificates。




== 第1步：完成CSR文件

您必须先生成证书签名请求(CSR)文件、用于标识您的组织以及运行插件的主机系统。或者、您也可以使用OpenSSL等工具生成CSR文件、然后跳至  2: Submit CSR file。

.步骤
. 选择*证书管理*。
. 从*管理*选项卡中、选择*完成CSR*。
. 输入以下信息、然后单击*下一步*：
+
** *组织*—贵公司或组织的法定全名。包括后缀、例如Inc.或Corp.
** *组织单位(可选)*—组织中负责处理证书的部门。
** *城市/位置*-主机系统或业务所在的城市。
** *省/自治区/直辖市(可选)*—主机系统或业务所在的省/自治区/直辖市。
** *国家/地区ISO代码*—您所在国家/地区的两位数ISO (国际标准化组织)代码、例如美国。


. 输入有关运行此插件的主机系统的以下信息：
+
** *公用名*—运行插件的主机系统的IP地址或DNS名称。请确保此地址正确无误；它必须与您在浏览器中输入的地址完全匹配才能访问此插件。请勿包含http：//或https：//。DNS名称不能以通配符开头。
** *备用IP地址*-如果公用名称为IP地址、则可以选择为主机系统输入任何其他IP地址或别名。对于多个条目、请使用逗号分隔格式。
** *备用DNS名称*-如果公用名称为DNS名称、请输入主机系统的任何其他DNS名称。对于多个条目、请使用逗号分隔格式。如果没有备用DNS名称、但您在第一个字段中输入了DNS名称、请将此名称复制到此处。DNS名称不能以通配符开头。


. 确保主机信息正确无误。否则、从CA返回的证书将在您尝试导入时失败。
. 单击 * 完成 * 。




== 第2步：提交CSR文件

创建证书签名请求(CSR)文件后、您可以将生成的CSR文件发送到CA、以接收托管此插件的系统的已签名管理证书。

E系列系统要求对签名证书使用PEM格式(Base64 ASCII编码)、其中包括以下文件类型：.pem、.crt、.cer或.key。

.步骤
. 找到已下载的CSR文件。
+
下载内容的文件夹位置取决于您的浏览器。

. 将CSR文件提交到CA (例如VeriSign或DigiCert)、并请求PEM格式的签名证书。



CAUTION: 将CSR文件提交到CA后、请勿重新生成其他CSR文件。

每当生成CSR时、系统都会创建一个专用密钥对和公有 密钥对。公有 密钥是CSR的一部分、而私钥则保留在系统的密钥库中。当您收到签名证书并将其导入时、系统会确保私钥和公有 密钥都是原始对。如果密钥不匹配、则签名证书将不起作用、您必须从CA请求新证书。



== 第3步：导入管理证书

从证书颁发机构(CA)收到签名证书后、请将这些证书导入到安装此插件的主机系统中。

.开始之前
* 您必须拥有来自CA的签名证书。这些文件包括根证书、一个或多个中间证书以及服务器证书。
* 如果CA提供了一个链式证书文件(例如.p7b文件)、则必须将链式文件解压缩到各个文件中：根证书、一个或多个中间证书以及服务器证书。您可以使用Windows certmgr实用程序解压缩文件(右键单击并选择菜单：所有任务[导出])。建议使用64位编码。导出完成后、系统将为链中的每个证书文件显示一个CER"文件。
* 您必须将证书文件复制到运行插件的主机系统。


.步骤
. 选择*证书管理*。
. 从*管理*选项卡中、选择*导入*。
+
此时将打开一个对话框、用于导入证书文件。

. 单击*浏览*以首先选择根证书和中间证书文件、然后选择服务器证书。如果从外部工具生成CSR、则还必须导入随CSR一起创建的私钥文件。
+
文件名将显示在对话框中。

. 单击 * 导入 * 。


这些文件将上传并进行验证。证书信息将显示在证书管理页面上。
