---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-configuration-settings-for-a-volume-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 编辑卷组的设置、包括其名称和RAID级别。 
---
= 更改卷组的配置设置
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以编辑卷组的设置、包括其名称和RAID级别。

.开始之前
如果要更改RAID级别以满足访问卷组的应用程序的性能需求、请确保满足以下前提条件：

* 卷组必须处于最佳状态。
* 卷组中必须有足够的容量才能转换为新的RAID级别。


.步骤
. 从管理页面中、选择具有卷组的存储阵列。
. 选择菜单：配置[配置池和卷组]。
. 选择要编辑的卷组、然后单击*查看/编辑设置*。
+
此时将显示卷组设置对话框。

. 选择*设置*选项卡、然后根据需要编辑卷组设置。
+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 正在设置 ... | Description 


 a| 
Name
 a| 
您可以更改用户提供的卷组名称。需要为卷组指定名称。



 a| 
RAID级别
 a| 
从下拉菜单中选择新的RAID级别。

** * RAID 0条带化*—提供高性能、但不提供任何数据冗余。如果卷组中的一个驱动器发生故障、则所有关联卷都会发生故障、并且所有数据都将丢失。条带化RAID组将两个或更多驱动器组合成一个大型逻辑驱动器。
** * RAID 1镜像*—提供高性能和最佳数据可用性、适合在企业或个人级别存储敏感数据。通过自动将一个驱动器的内容镜像到镜像对中的第二个驱动器来保护数据。它可以在单个驱动器发生故障时提供保护。
** * RAID 10条带化/镜像*-提供RAID 0 (条带化)和RAID 1 (镜像)的组合、可在选择四个或更多驱动器时实现。RAID 10适用于需要高性能和容错能力的高卷事务应用程序、例如数据库。
** * RAID 5*—最适合多用户环境(例如数据库或文件系统存储)、其中典型I/O大小较小且读取活动比例较高。
** * RAID 6*—最适合需要RAID 5以上冗余保护但不需要高写入性能的环境。使用命令行界面(CLI)只能将RAID 3分配给卷组。更改RAID级别后、此操作将无法在开始后取消。在更改期间、您的数据将保持可用。




 a| 
优化容量(仅限EF600阵列)
 a| 
创建卷组时、系统会生成一个建议的优化容量、以便在可用容量与性能以及驱动器使用寿命之间取得平衡。您可以通过向右移动滑块以提高性能和驱动器使用寿命而降低可用容量的增加来调整这种平衡、也可以将滑块移至左侧以增加可用容量、从而降低性能和驱动器使用寿命。如果未分配一部分容量、SSD驱动器的使用寿命将会延长、并且最大写入性能也会提高。对于与卷组关联的驱动器、未分配的容量由组的可用容量(卷未使用的容量)以及作为额外优化容量而预留的部分可用容量组成。额外的优化容量可通过减少可用容量来确保最低的优化容量级别、因此不可用于创建卷。

|===
====
. 单击 * 保存 * 。


如果因RAID级别更改而导致容量减少、卷冗余丢失或磁盘架/抽屉丢失保护丢失、则会显示一个确认对话框。选择*是*继续；否则单击*否*。

.结果
如果更改卷组的RAID级别、插件将更改组成卷组的每个卷的RAID级别。在此操作期间、性能可能会受到轻微影响。
