---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-pools-and-volume-group-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: '要配置存储、请创建一个池或卷组、其中包含要在存储阵列中使用的硬盘驱动器(HDD)或固态磁盘(SSD)驱动器。' 
---
= 在适用于vCenter的SANtricity存储插件中了解存储池和卷组
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
要在适用于vCenter的存储插件中配置存储、请创建一个池或卷组、其中包含要在存储阵列中使用的硬盘驱动器(HDD)或固态磁盘(SSD)驱动器。



== 配置

物理硬件配置到逻辑组件中、以便对数据进行组织并轻松检索。支持两种类型的分组：

* 池
* 卷组


池和卷组是存储阵列中的顶级存储单元：它们将驱动器的容量划分为可管理的分区。在这些逻辑分区中、是指存储数据的单个卷或LUN。

部署存储系统后、第一步是通过以下方式向各种主机提供可用驱动器容量：

* 创建具有足够容量的池或卷组
* 将满足性能要求所需的驱动器数量添加到池或卷组
* 选择所需的RAID保护级别(如果使用卷组)以满足特定业务要求


您可以在同一存储系统上使用池或卷组、但一个驱动器不能属于多个池或卷组。然后、使用池或卷组上的空间创建提供给主机用于I/O的卷。



== 池

池用于将物理硬盘驱动器聚合到较大的存储空间中、并为其提供增强的RAID保护。池会根据分配给池的驱动器总数创建多个虚拟RAID集、并在所有参与驱动器之间平均分布数据。如果丢失或添加了驱动器、系统会在所有活动驱动器之间动态重新平衡数据。

池可作为另一个RAID级别运行、可对底层RAID架构进行虚拟化、以优化执行重建、驱动器扩展和处理驱动器丢失等任务时的性能和灵活性。在8+2配置中、系统会自动将RAID级别设置为6 (八个数据磁盘加上两个奇偶校验磁盘)。



=== 驱动器匹配

您可以选择在池中使用HDD或SSD；但是、与卷组一样、池中的所有驱动器都必须使用相同的技术。控制器会自动选择要包含的驱动器、因此您必须确保具有足够数量的驱动器来支持您选择的技术。



=== 管理故障驱动器

池的最小容量为11个驱动器；但是、如果驱动器发生故障、则会为一个驱动器预留一个容量作为备用容量。此备用容量称为"保留容量"。

创建池时、会保留一定的容量以供紧急使用。此容量以多个驱动器表示、但实际实施会分布在整个驱动器池中。保留的默认容量取决于池中的驱动器数量。

创建池后、您可以将保留容量值更改为更多或更少的容量、甚至可以将其设置为无保留容量(0个驱动器值)。可以保留的最大容量(以驱动器数表示)为10、但根据池中的驱动器总数、可用容量可能会更少。



== 卷组

卷组用于定义如何在存储系统中为卷分配容量。磁盘驱动器按RAID组进行组织、卷驻留在RAID组中的驱动器上。因此、卷组配置设置可确定哪些驱动器属于该组、以及使用了哪些RAID级别。

创建卷组时、控制器会自动选择要包含在此组中的驱动器。您必须手动为组选择RAID级别。卷组的容量是所选驱动器总数乘以其容量。



=== 驱动器匹配

您必须匹配卷组中的驱动器、以确定其大小和性能。如果卷组中的驱动器较小或较大、则会将所有驱动器识别为最小容量大小。如果卷组中的驱动器速度较慢、速度较快、则会以最慢的速度识别所有驱动器。这些因素会影响存储系统的性能和整体容量。

您不能混用不同的驱动器技术(HDD和SSD驱动器)。RAID 3、5和6最多限制为30个驱动器。RAID 1和RAID 10使用镜像、因此这些卷组的磁盘数量必须为偶数。



=== 管理故障驱动器

如果卷组中包含的RAID 1/10、RAID 3、RAID 5或RAID 6卷中的驱动器发生故障、则卷组会使用热备用驱动器作为备用驱动器。热备用驱动器不包含任何数据、并为存储阵列添加了另一个冗余级别。

如果存储阵列中的某个驱动器发生故障、则热备用驱动器会自动替换故障驱动器、而无需物理交换。如果在驱动器发生故障时热备用驱动器可用、则控制器会使用冗余数据将故障驱动器中的数据重建到热备用驱动器。



== 确定是使用池还是卷组



=== 选择一个池

* 如果您需要更快的驱动器重建速度和简化的存储管理、以及/或具有高度随机的工作负载。
* 如果要将每个卷的数据随机分布在构成池的一组驱动器上。您不能设置或更改池或池中卷的RAID级别。池使用RAID级别6。




=== 选择卷组

* 如果您需要最大的系统带宽、调整存储设置的能力以及高度顺序的工作负载、
* 如果要根据RAID级别在驱动器之间分布数据。您可以在创建卷组时指定RAID级别。
* 要在构成卷组的一组驱动器上按顺序写入每个卷的数据。



NOTE: 由于池可以与卷组共存、因此存储阵列可以同时包含池和卷组。



== 自动创建池与手动创建池

根据您的存储配置、您可以允许系统自动创建池、也可以手动自行创建池。池是一组逻辑分组的驱动器。

在创建和管理池之前、请查看以下各节、了解如何自动创建池以及何时可能需要手动创建池。



=== 自动创建

如果系统检测到存储阵列中的未分配容量、则会在系统检测到存储阵列中的未分配容量时启动自动创建池。它会自动提示您创建一个或多个池、或者向现有池添加未分配的容量、或者同时创建这两者。

如果满足以下条件之一、则会自动创建池：

* 存储阵列中不存在池、并且有足够的类似驱动器来创建新池。
* 新驱动器将添加到至少具有一个池的存储阵列中。一个池中的每个驱动器必须具有相同的驱动器类型(HDD或SSD)并具有类似的容量。系统将提示您完成以下任务：
* 如果这些类型的驱动器数量充足、请创建一个池。
* 如果未分配的容量包含不同的驱动器类型、请创建多个池。
* 如果已在存储阵列中定义池、请将驱动器添加到现有池、然后将相同驱动器类型的新驱动器添加到该池。
* 将相同驱动器类型的驱动器添加到现有池中、如果新驱动器的驱动器类型不同、请使用其他驱动器类型创建不同的池。




=== 手动创建

如果自动创建无法确定最佳配置、您可能需要手动创建池。出现这种情况的原因可能如下：

* 新驱动器可能会添加到多个池中。
* 一个或多个新池候选项可以使用磁盘架丢失保护或抽屉丢失保护。
* 一个或多个当前池候选项无法保持其磁盘架丢失保护或抽盒丢失保护状态。如果存储阵列上有多个应用程序、并且不希望这些应用程序争用相同的驱动器资源、您可能还需要手动创建池。在这种情况下、您可能会考虑手动为一个或多个应用程序创建一个较小的池。您只能分配一个或两个卷、而不能将工作负载分配给一个大型池、该池包含许多卷、可用于分布数据。手动创建专用于特定应用程序工作负载的单独池可以提高存储阵列操作的执行速度、并减少争用。

