---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-the-settings-for-a-host.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 您可以更改主机或主机集群的名称、主机操作系统类型以及关联的主机集群。 
---
= 更改主机的设置
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以更改主机或主机集群的名称、主机操作系统类型以及关联的主机集群。

.步骤
. 从管理页面中，选择具有主机连接的存储阵列。
. 选择菜单：配置 [ 配置主机 ] 。
+
此时将打开配置主机页面。

. 选择要编辑的主机、然后单击*查看/编辑设置*。
+
此时将显示一个对话框，其中显示了当前主机设置。

. 要更改主机属性、请确保已选中*属性*选项卡、然后根据需要更改设置。
+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 正在设置 ... | Description 


 a| 
Name
 a| 
您可以更改用户提供的主机名称。需要为主机指定名称。



 a| 
关联的主机集群
 a| 
您可以选择以下选项之一：

** *无*—此主机仍为独立主机。如果主机已与主机集群关联、则系统会将此主机从集群中删除。
** *<Host Cluster>*—系统将主机与选定集群关联。




 a| 
主机操作系统类型
 a| 
您可以更改在定义的主机上运行的操作系统类型。

|===
====
. 要更改端口设置、请单击*主机端口*选项卡、然后根据需要更改设置。
+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 正在设置 ... | Description 


 a| 
主机端口
 a| 
您可以选择以下选项之一：

** *添加*—使用添加将新的主机端口标识符与主机关联。主机端口标识符名称的长度由主机接口技术决定。光纤通道和Infiniband主机端口标识符名称必须包含16个字符。iSCSI 主机端口标识符名称最多包含 223 个字符。此端口必须是唯一的。不允许使用已配置的端口号。
** *删除*—使用删除删除删除主机端口标识符(取消关联)。删除选项不会物理删除主机端口。此选项将删除主机端口与主机之间的关联。除非您删除主机总线适配器或 iSCSI 启动程序，否则控制器仍可识别主机端口。



CAUTION: 如果删除主机端口标识符、它将不再与此主机关联。此外、主机将无法通过此主机端口标识符访问其分配的任何卷。



 a| 
Label
 a| 
要更改端口标签名称、请单击*编辑*图标(铅笔)。端口标签名称必须是唯一的。不允许使用已配置的标签名称。



 a| 
CHAP机密
 a| 
仅对iSCSI主机显示。您可以为启动程序(iSCSI主机)设置或更改CHAP密钥。系统使用质询握手身份验证协议(Challenge Handshake Authentication Protocol、CHAP)方法、在初始链路期间验证目标和启动程序的身份。身份验证基于一个称为CHAP机密的共享安全密钥。

|===
====
. 单击 * 保存 * 。

