---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-activate-staged-os-software.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 您可以选择在更方便的时间激活软件文件。 
---
= 激活暂存操作系统软件
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以选择立即激活软件文件，也可以等到更方便的时间再激活。此操作步骤假定您稍后选择激活此软件文件。

.关于此任务
您可以传输固件文件、而无需激活这些文件。您可以选择稍后激活，原因如下：

* * 当前时间 * —激活软件可能需要很长时间，因此您可能需要等待 I/O 负载变轻。控制器会在激活期间重新启动并进行故障转移，因此在升级完成之前性能可能会比平常低。
* * 软件包类型 * —您可能需要先在一个存储阵列上测试新软件和固件，然后再升级其他存储阵列上的文件。



NOTE: 激活过程启动后，您无法停止它。

.步骤
. 在主视图中、选择*管理*。如有必要、请单击页面顶部的*状态*列对状态为"OS Upgrade (waiting activation)"的所有存储阵列进行排序。
. 选择要为其激活软件的一个或多个存储阵列、然后选择菜单：升级中心[激活暂存SANtricity 软件]。
+
升级操作期间会执行以下操作：

+
** 在激活过程中会运行升级前运行状况检查。升级前运行状况检查会评估所有存储阵列组件，以确保激活可以继续进行。
** 如果存储阵列的任何运行状况检查失败，则激活将停止。您可以单击省略号(…) 并选择*保存日志*以查看错误。您也可以选择覆盖运行状况检查错误，然后单击 * 继续 * 继续进行激活。
** 您可以在升级前运行状况检查后取消激活操作。
+
成功完成升级前运行状况检查后，将激活。激活所需的时间取决于您的存储阵列配置以及要激活的组件。



. (可选)激活完成后、单击省略号(…)可查看为特定存储阵列激活的内容列表。 然后选择*保存日志*。
+
此文件将保存在浏览器的"Downloads"文件夹中、名称为`active_log-<date>。JSON`。


