---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-upgrade-santricity-os.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 使用最新软件和NVSRAM升级一个或多个存储阵列、以确保您拥有所有最新功能和错误修复。 
---
= 使用适用于vCenter的存储插件升级SANtricity软件和NVsan
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
使用最新软件和NVSRAM升级一个或多个存储阵列、以确保您拥有所有最新功能和错误修复。控制器NVSRAM是一个控制器文件、用于指定控制器的默认设置。

.开始之前
请确保：

* 运行此插件的主机系统上提供了最新的SANtricity OS文件。
* 您知道是要立即激活软件升级还是稍后激活。您可以选择稍后激活，原因如下：
+
** * 当前时间 * —激活软件可能需要很长时间，因此您可能需要等待 I/O 负载变轻。控制器会在激活期间进行故障转移，因此，在升级完成之前，性能可能会比平常低。
** * 软件包类型 * —您可能需要先在一个存储阵列上测试新的操作系统软件，然后再升级其他存储阵列上的文件。





CAUTION: * 数据丢失或存储阵列损坏的风险 * —升级期间请勿更改存储阵列。为存储阵列供电。

.步骤
. 如果存储阵列仅包含一个控制器或未使用多路径驱动程序，请停止存储阵列的 I/O 活动，以防止出现应用程序错误。如果存储阵列有两个控制器，并且您安装了多路径驱动程序，则无需停止 I/O 活动。
. 在主视图中、选择*管理*、然后选择要升级的一个或多个存储阵列。
. 选择菜单：Upgrade Center[升级> SANtricity OS >软件]。
+
此时将显示升级 SANtricity OS 软件页面。

. 从支持站点将最新的SANtricity OS软件包下载到本地计算机。
+
.. 单击向软件存储库添加新文件
.. 单击此链接可查找最新的SANtricity OS下载内容。
.. 单击 * 下载最新版本 * 链接。
.. 按照其余说明将操作系统文件和NVSRAM文件下载到本地计算机。
+

NOTE: 8.42 及更高版本需要使用数字签名固件。如果您尝试下载未签名的固件，则会显示一个错误，并中止下载。



. 选择要用于升级控制器的操作系统软件文件和 NVSRAM 文件：
+
.. 从下拉列表中、选择下载到本地计算机的操作系统文件。
+
如果有多个可用文件，则这些文件将从最新日期到最旧日期进行排序。

+

NOTE: 此软件存储库将列出与此插件关联的所有软件文件。如果未看到要使用的文件，可以单击链接 * 将新文件添加到软件存储库 * ，以浏览到要添加的操作系统文件所在的位置。

.. 从 * 选择 NVSRAM 文件 * 下拉列表中，选择要使用的控制器文件。
+
如果有多个文件，则这些文件将从最新日期到最旧日期进行排序。



. 在兼容存储阵列表中，查看与选定操作系统软件文件兼容的存储阵列，然后选择要升级的阵列。
+
** 默认情况下，您在 " 管理 " 视图中选择的存储阵列以及与选定固件文件兼容的存储阵列将在 " 兼容存储阵列 " 表中选择。
** 无法使用选定固件文件更新的存储阵列在兼容存储阵列表中不可选择，如状态 * 不兼容 * 所示。


. （可选）要在不激活软件文件的情况下将其传输到存储阵列，请选中 * 将操作系统软件传输到存储阵列，将其标记为暂存并稍后激活 * 复选框。
. 单击 * 开始 * 。
. 根据您选择现在激活还是稍后激活，执行以下操作之一：
+
** 键入`transfer`确认要在选定升级的阵列上传输建议的操作系统软件版本、然后单击*传输*。要激活已传输的软件、请选择菜单：升级中心[激活暂存SANtricity 操作系统软件]。
** 键入`upgrade`确认要在选定升级的阵列上传输和激活建议的操作系统软件版本、然后单击*升级*。
+
系统会将软件文件传输到您选择升级的每个存储阵列，然后通过启动重新启动来激活该文件。

+
升级操作期间会执行以下操作：

** 升级前运行状况检查会在升级过程中运行。升级前运行状况检查会评估所有存储阵列组件，以确保升级可以继续进行。
** 如果存储阵列的任何运行状况检查失败，升级将停止。您可以单击省略号(…) 并选择*保存日志*以查看错误。您还可以选择覆盖运行状况检查错误，然后单击 * 继续 * 继续升级。
** 您可以在升级前运行状况检查后取消升级操作。


. (可选)升级完成后、您可以单击省略号(…)来查看为特定存储阵列升级的内容列表。 然后选择*保存日志*。
+
此文件将保存在浏览器的"Downloads"文件夹中、名为`upgrade_log-<date>。JSON`。


