---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-host-access.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 要使用适用于vCenter的存储插件管理存储、您必须发现或定义网络中的每个主机。 
---
= 创建主机访问
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
要使用适用于vCenter的存储插件管理存储、您必须发现或定义网络中的每个主机。

通过创建主机、您可以定义主机参数以提供与存储阵列的连接以及对卷的I/O访问。

您可以允许主机上下文代理(Host Context Agent、HCA)自动检测主机、然后从配置主机页面中选择*查看/编辑设置*以验证此信息是否正确。但是、HCA并非在所有受支持的操作系统上都可用、您必须手动创建主机。

创建主机时、请牢记以下准则：

* 您必须定义与主机关联的主机标识符端口。
* 请确保提供与主机分配的系统名称相同的名称。
* 如果您选择的名称已在使用中，则此操作不会成功。
* 名称长度不能超过 30 个字符。


.步骤
. 从管理页面中，选择具有主机连接的存储阵列。
. 选择菜单：配置 [ 配置主机 ] 。
+
此时将打开配置主机页面。

. 单击菜单：创建 [ 主机 ] 。
+
此时将显示创建主机对话框。

. 根据需要选择主机设置。
+
.字段详细信息
====
[cols="25h,~"]
|===
| 正在设置 ... | Description 


 a| 
Name
 a| 
键入新主机的名称。



 a| 
主机操作系统类型
 a| 
从下拉列表中选择新主机上运行的操作系统。



 a| 
主机接口类型
 a| 
（可选）如果存储阵列支持多种类型的主机接口，请选择要使用的主机接口类型。



 a| 
主机端口
 a| 
执行以下操作之一：

** *选择I/O接口*-通常、主机端口应已登录并可从下拉列表中使用。您可以从列表中选择主机端口标识符。
** *手动添加*-如果列表中未显示主机端口标识符、则表示主机端口尚未登录。可以使用 HBA 实用程序或 iSCSI 启动程序实用程序来查找主机端口标识符并将其与主机关联。您可以手动输入主机端口标识符，也可以将它们从实用程序（一次一个）复制 / 粘贴到主机端口字段中。您必须一次选择一个主机端口标识符才能将其与主机关联，但您可以继续选择与主机关联的任意数量的标识符。每个标识符都会显示在主机端口字段中。如有必要，您还可以通过选择标识符旁边的 * X * 来删除该标识符。




 a| 
设置 CHAP 启动程序密钥
 a| 
(可选)如果您选择或手动输入具有iSCSI IQN的主机端口、并且希望要求尝试访问存储阵列的主机使用质询握手身份验证协议(CHAP)进行身份验证、请选中"设置CHAP启动程序密钥"复选框。对于您选择或手动输入的每个 iSCSI 主机端口，请执行以下操作：

** 输入在每个 iSCSI 主机启动程序上为 CHAP 身份验证设置的相同 CHAP 密钥。如果您使用相互 CHAP 身份验证（双向身份验证，可使主机向存储阵列验证自身，并使存储阵列向主机验证自身），则还必须在初始设置或通过更改设置为存储阵列设置 CHAP 密钥。
** 如果不需要主机身份验证，请将此字段留空。目前，唯一使用的 iSCSI 身份验证方法是 CHAP 。


|===
====
. 单击 * 创建 * 。
. 如果需要更新主机信息，请从表中选择主机，然后单击 * 查看 / 编辑设置 * 。


成功创建主机后，系统会为为为主机配置的每个主机端口创建一个默认名称（用户标签）。默认别名为 ` < 主机名端口号 >` 。例如，为主机 IPT 创建的第一个端口的默认别名为 `ipt_1` 。

您必须将卷分配给主机、以便用于I/O操作。转至 link:vc-olh-assign-volumes-to-hosts.html["将卷分配给主机"]。
