---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-do-i-need-to-know-about-the-resource-provisioned-volumes-feature.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 资源配置是EF300和EF600存储阵列中提供的一项功能、可在不执行后台初始化过程的情况下立即使用卷。 
---
= 关于资源配置卷功能、我需要了解哪些信息？
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
资源配置是EF300和EF600存储阵列中提供的一项功能、可在不执行后台初始化过程的情况下立即使用卷。


NOTE: 此时、资源配置功能不可用。在某些视图中、组件可能会报告为具有资源配置功能、但创建资源配置卷的功能已被禁用、直到可以在将来的更新中重新启用为止。



== 资源配置的卷

资源配置卷是SSD卷组或池中的厚卷、在创建卷时会分配(分配给卷)驱动器容量、但会取消分配(取消映射)驱动器块。相比之下、在传统厚卷中、所有驱动器块都会在后台卷初始化操作期间映射或分配、以便初始化数据保证保护信息字段并使每个RAID条带中的数据和RAID奇偶校验保持一致。对于资源配置的卷、不会进行有时间限制的后台初始化。而是在首次写入条带中的卷块时初始化每个RAID条带。

只有SSD卷组和池支持资源配置的卷、其中组或池中的所有驱动器都支持NVMe已取消分配或未写入逻辑块错误启用(DULBE")错误恢复功能。创建资源配置的卷时、分配给该卷的所有驱动器块都会进行取消分配(未映射)。此外、主机还可以使用NVMe Dataset Management命令取消分配卷中的逻辑块。取消分配块可以延长SSD的使用寿命并提高最大写入性能。性能提升因驱动器型号和容量而异。



== 启用和禁用此功能

在驱动器支持DULBE"的系统上、默认情况下会启用资源配置。您可以从"池和卷组"中禁用此默认设置。禁用资源配置是对现有卷执行的一项永久操作、无法反转(即、您无法为这些卷组和池重新启用资源配置)。

但是、如果要为您创建的任何新卷重新启用资源配置、则可以从菜单：Settings[系统]执行此操作。请注意、在重新启用资源配置时、仅会影响新创建的卷组和池。任何现有卷组和池将保持不变。如果需要、您还可以从菜单：Settings[系统]再次禁用资源配置。
