---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-consolidate-free-capacity-for-a-volume-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 使用整合可用容量选项整合选定卷组上的现有可用块区。通过执行此操作、您可以使用卷组中的最大可用容量创建更多卷。 
---
= 整合卷组的可用容量
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用整合可用容量选项整合选定卷组上的现有可用块区。通过执行此操作、您可以使用卷组中的最大可用容量创建更多卷。

.开始之前
* 卷组必须至少包含一个可用容量区域。
* 卷组中的所有卷都必须处于联机状态并处于最佳状态。
* 不得正在执行卷修改操作、例如更改卷的区块大小。


.关于此任务
操作开始后、您将无法取消。在整合操作期间、您的数据仍可访问。

您可以使用以下任一方法启动整合可用容量对话框：

* 如果至少为卷组检测到一个可用容量区域、则"通知"区域的"主页"页面上将显示"整合可用容量建议"。单击*整合可用容量*链接以启动对话框。
* 您还可以从"池和卷组"页面启动"整合可用容量"对话框、如以下任务所述。


.有关可用容量区域的更多信息
[%collapsible]
====
可用容量区域是指删除卷或在创建卷期间未使用所有可用容量时可能产生的可用容量。在卷组中创建具有一个或多个可用容量区域的卷时、卷的容量将限制为该卷组中最大的可用容量区域。例如、如果一个卷组的可用容量总计为15 GiB、而最大可用容量区域为10 GiB、则可以创建的最大卷为10 GiB。

您可以整合卷组上的可用容量以提高写入性能。随着主机写入、修改和删除文件、卷组的可用容量将逐渐变得碎片化。最终、可用容量不会位于一个连续块中、而是分散在卷组中的小片段中。这会导致文件进一步碎片化、因为主机必须将新文件作为碎片写入、才能将其放入可用集群范围内。

通过将选定卷组上的可用容量整合在一起、您会发现、每当主机写入新文件时、文件系统性能都会提高。整合过程还有助于防止新文件在将来被碎片化。

====
.步骤
. 从管理页面中、选择具有卷组的存储阵列。
. 选择菜单：配置[配置池和卷组]。
. 选择具有要整合的可用容量的卷组、然后选择菜单：不常见任务(整合卷组可用容量)。
+
此时将显示整合可用容量对话框。

. 键入`consolidate`确认要执行此操作。
. 单击*整合*。


.结果
系统将开始将卷组的可用容量区域整合(碎片整理)为一个连续的容量、以便执行后续的存储配置任务。

.完成后
从导航边栏中、选择*操作*以查看整合可用容量操作的进度。此操作可能会很长，并且可能会影响系统性能。
