---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-array-management-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: '使用"添加/发现"功能查找并添加要在组织网络中管理的存储阵列。' 
---
= 阵列管理概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
使用添加/发现功能在vCenter的存储插件中查找和添加要管理的存储阵列。在管理页面中、您还可以重命名、删除这些已发现阵列并提供新密码。



== 发现阵列的注意事项

要使插件能够显示和管理存储资源、您必须在组织的网络中发现要管理的存储阵列。您可以发现并添加一个或多个阵列。



=== 多个存储阵列

如果您选择发现多个阵列、则输入一个网络IP地址范围、然后系统将尝试单独连接到该范围中的每个IP地址。成功访问的任何存储阵列都会显示在此插件中、然后您可以将其添加到管理域中。



=== 单个存储阵列

如果您选择发现单个阵列、请为存储阵列中的一个控制器输入单个IP地址、然后将该阵列添加到管理域中。


NOTE: 插件仅会发现并显示分配给控制器的范围内的单个IP地址或IP地址。如果为这些控制器分配的备用控制器或IP地址不在此单个IP地址或IP地址范围内、则插件将不会发现或显示它们。但是、添加存储阵列后、所有关联的IP地址都将被发现并显示在管理视图中。



=== 用户凭据

您必须为要添加的每个存储阵列提供管理员密码。



=== 证书

在发现过程中、系统会验证发现的存储阵列是否正在使用受信任源的证书。系统对通过浏览器与建立的所有连接使用两种基于证书的身份验证：

* *可信证书*—如果证书链中的一个或两个控制器证书已过期、已撤消或缺少证书、则可能需要安装证书颁发机构提供的其他可信证书。
* *自签名证书*-阵列也可以使用自签名证书。如果您尝试在未导入签名证书的情况下发现阵列、则此插件还提供了一个步骤、可用于接受自签名证书。存储阵列的自签名证书将标记为可信、存储阵列将添加到插件中。如果您不相信与存储阵列的连接、请选择*取消*并验证存储阵列的安全证书策略、然后再将存储阵列添加到插件。




== 存储阵列状态

打开适用于vCenter的存储插件时、将与每个存储阵列建立通信、并显示每个存储阵列的状态。

在*管理-全部*页面中、您可以查看存储阵列的状态和存储阵列连接的状态。

|===
| Status | 表示 


| 最佳 | 存储阵列处于最佳状态。没有证书问题、密码有效。 


| 密码无效 | 提供的存储阵列密码无效。 


| 不可信证书 | 与存储阵列的一个或多个连接不可信、因为HTTPS证书是自签名的、尚未导入、或者证书是CA签名的、并且根和中间CA证书尚未导入。 


| 需要关注 | 存储阵列存在问题、需要您进行干预才能进行更正。 


| 锁定 | 存储阵列处于已锁定状态。 


| 未知 | 从未联系过存储阵列。如果插件正在启动且尚未与存储阵列进行联系、或者存储阵列处于脱机状态且自插件启动以来从未进行过联系、则可能会发生这种情况。 


| 脱机 | 插件先前已与存储阵列联系、但现在已断开与该存储阵列的所有连接。 
|===


== 插件界面与System Manager的对比

您可以使用适用于vCenter的存储插件执行存储阵列上的基本操作任务；但是、有时可能需要启动System Manager来执行插件中不可用的任务。

System Manager是存储阵列控制器上的嵌入式应用程序、它通过以太网管理端口连接到网络。System Manager包括所有基于阵列的功能。

下表可帮助您确定是否可以使用插件界面或System Manager界面执行特定存储阵列任务。

|===
| 功能 | 插件界面 | System Manager界面 


| 对包含多个存储阵列的组执行批处理操作 | 是的。 | 否操作在一个阵列上执行。 


| 升级SANtricity OS固件 | 是的。批处理操作中的一个或多个阵列。 | 是的。仅限单个阵列。 


| 将设置从一个阵列导入到多个阵列 | 是的。 | 否 


| 主机和主机集群管理(创建、分配卷、更新和删除) | 是的。 | 是的。 


| 池和卷组管理(创建、更新、启用安全性和删除) | 是的。 | 是的。 


| 卷管理(创建、调整大小、更新和删除) | 是的。 | 是的。 


| SSD缓存管理(创建、更新和删除) | 是的。 | 是的。 


| 镜像和快照管理 | 否 | 是的。 


| 硬件管理(查看控制器状态、配置端口连接、使控制器脱机、启用热备件、擦除驱动器、 等) | 否 | 是的。 


| 管理警报(电子邮件、SNMP和系统日志) | 否 | 是的。 


| 安全密钥管理 | 否 | 是的。 


| 控制器的证书管理 | 否 | 是的。 


| 控制器访问管理(LDAP、SAML等) | 否 | 是的。 


| AutoSupport 管理 | 否 | 是的。 
|===