---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-host-creation-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 要使用适用于vCenter的存储插件管理存储、您必须发现或定义网络中的每个主机。 
---
= 主机创建概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
要使用适用于vCenter的存储插件管理存储、您必须发现或定义网络中的每个主机。主机是指向存储阵列上的卷发送I/O的服务器。



== 自动创建与手动创建主机

创建主机是向存储阵列告知连接了哪些主机并允许对卷进行I/O访问所需的步骤之一。可以自动或手动创建主机。

* * 自动 * —主机上下文代理（ HCA ）会为基于 SCSI （而不是 NVMe-oF ）的主机启动自动主机创建。HCA 是一个实用程序，您可以在连接到存储阵列的每个主机上安装该实用程序。安装了 HCA 的每个主机都会通过 I/O 路径将其配置信息推送到存储阵列控制器。根据主机信息，控制器会自动创建主机以及关联的主机端口并设置主机类型。如果需要，您可以对主机配置进行任何其他更改。HCA 执行自动检测后，主机将自动配置以下属性：
+
** 从主机的系统名称派生的主机名。
** 与主机关联的主机标识符端口。
** 主机的主机操作系统类型。





NOTE: 主机作为独立主机创建； HCA 不会自动创建或添加到主机集群。

* *手动*—在手动创建主机期间、您可以通过从列表中选择主机端口标识符或手动输入这些标识符来关联主机端口标识符。创建主机后，如果您计划共享对卷的访问，则可以为其分配卷或将其添加到主机集群。




== 如何分配卷

要使主机向卷发送I/O、您必须为其分配卷。您可以在创建卷时选择主机或主机集群、也可以稍后将卷分配给主机或主机集群。主机集群是一组主机。您可以创建一个主机集群、以便轻松地将相同的卷分配给多个主机。

为主机分配卷非常灵活、可以满足您的特定存储需求。

* *独立主机、不属于主机集群*—您可以将卷分配给单个主机。卷只能由一台主机访问。
* *主机集群*-您可以将卷分配给主机集群。主机集群中的所有主机均可访问此卷。
* *主机集群中的主机*-您可以将卷分配给属于主机集群的单个主机。即使此主机属于主机集群、但此卷只能由单个主机访问、而不能由主机集群中的任何其他主机访问。


创建卷时、系统会自动分配逻辑单元号(LUN)。在I/O操作期间、LUN充当主机和控制器之间的地址。您可以在创建卷后更改LUN。
