---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-media-scan-settings-for-a-volume.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 介质扫描是一种后台操作、可扫描卷中的所有数据和冗余信息。使用此选项可以为一个或多个卷启用或禁用介质扫描设置、或者更改扫描持续时间。 
---
= 在适用于vCenter的SANtricity存储插件中更改卷的介质扫描设置
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
介质扫描是一种后台操作、可扫描卷中的所有数据和冗余信息。使用此选项可以为一个或多个卷启用或禁用介质扫描设置、或者更改扫描持续时间。

.开始之前
了解以下内容：

* 介质扫描会根据要扫描的容量和扫描持续时间以恒定速率持续运行。后台扫描可能会被较高优先级的后台任务(例如重建)临时暂停、但会以相同的恒定速率恢复。
* 只有在为存储阵列和卷启用了介质扫描选项时、才会扫描此卷。如果还为该卷启用了冗余检查、则会检查该卷中的冗余信息是否与数据一致、前提是该卷具有冗余。创建每个卷时、默认情况下会为其启用具有冗余检查的介质扫描。
* 如果在扫描期间遇到不可恢复的介质错误、则会使用冗余信息(如果有)修复数据。
+
例如、最佳RAID 5卷、最佳RAID 6卷或只有一个驱动器发生故障的RAID 6卷均提供冗余信息。如果无法使用冗余信息修复不可恢复的错误、则数据块将添加到不可读扇区日志中。可更正和不可更正的介质错误都会报告到事件日志中。

* 如果冗余检查发现数据与冗余信息不一致、则会向事件日志报告此信息。


.关于此任务
介质扫描可检测并修复应用程序不常读取的磁盘块上的介质错误。这样可以防止驱动器发生故障时数据丢失、因为故障驱动器的数据是使用卷组或池中其他驱动器的冗余信息和数据进行重建的。

您可以执行以下操作：

* 为整个存储阵列启用或禁用后台介质扫描
* 更改整个存储阵列的扫描持续时间
* 为一个或多个卷启用或禁用介质扫描
* 为一个或多个卷启用或禁用冗余检查


.步骤
. 从管理页面中、选择包含要更改其介质扫描设置的卷的存储阵列。
. 选择菜单：配置 [ 管理卷 ] 。
. 选择任何卷、然后选择菜单：更多(更改介质扫描设置)。
+
此时将显示更改驱动器介质扫描设置对话框。存储阵列上的所有卷都会显示在此对话框中。

. 要启用介质扫描、请选中*在过程中扫描介质...*复选框。禁用介质扫描复选框会暂停所有介质扫描设置。
. 指定要运行介质扫描的天数。
. 选中要对其执行介质扫描的每个卷对应的*介质扫描*复选框。系统会为您选择运行介质扫描的每个卷启用冗余检查选项。如果不想对个别卷执行冗余检查、请取消选中*冗余检查*复选框。
. 单击 * 保存 * 。


.结果
系统会根据您的选择对后台介质扫描应用更改。
