---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-add-capacity-to-a-pool-or-volume-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 添加驱动器以扩展现有池或卷组中的可用容量。 
---
= 在适用于vCenter的SANtricity存储插件中向池或卷组添加容量
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以添加驱动器以扩展现有池或卷组中的可用容量。

.开始之前
* 驱动器必须处于最佳状态。
* 驱动器必须具有相同的驱动器类型(HDD或SSD)。
* 池或卷组必须处于最佳状态。
* 如果池或卷组包含所有支持安全的驱动器、请仅添加支持安全的驱动器、以继续使用支持安全的驱动器的加密功能。


支持安全的驱动器可以是全磁盘加密(Full Disk Encryption、FDE)驱动器、也可以是联邦信息处理标准(Federal Information Processing Standard、FIPS)驱动器。

.关于此任务
在此任务中、您可以添加要包含在池或卷组中的可用容量。您可以使用此可用容量创建其他卷。在此操作期间、卷中的数据仍可访问。

对于池、一次最多可以添加60个驱动器。对于卷组、一次最多可以添加两个驱动器。如果需要添加的驱动器数超过最大数量、请重复执行操作步骤。(池中的驱动器数不能超过存储阵列的最大限制。)


NOTE: 添加驱动器后、可能需要增加保留容量。您应考虑在执行扩展操作后增加预留容量。


NOTE: 避免使用能够向不支持DA的池或卷组添加容量的数据保证(Data Assurance、DA)驱动器。池或卷组无法利用支持DA的驱动器的功能。在这种情况下、请考虑使用不支持DA的驱动器。

.步骤
. 从管理页面中、选择具有池或卷组的存储阵列。
. 选择菜单：配置[配置池和卷组]。
. 选择要添加驱动器的池或卷组、然后单击*添加容量*。
+
此时将显示添加容量对话框。仅显示与池或卷组兼容的未分配驱动器。

. 在*选择要添加容量的驱动器...*下、选择要添加到现有池或卷组的一个或多个驱动器。
+
控制器固件会使用顶部列出的最佳选项来排列未分配的驱动器。添加到池或卷组的总可用容量显示在*选定总容量*中的列表下方。

+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 字段 | Description 


 a| 
磁盘架
 a| 
指示驱动器的磁盘架位置。



 a| 
托架
 a| 
指示驱动器的托架位置



 a| 
容量(GiB)
 a| 
指示驱动器容量。

** 尽可能选择容量等于池或卷组中当前驱动器容量的驱动器。
** 如果您必须添加容量较小的未分配驱动器、请注意、池或卷组中当前每个驱动器的可用容量会减少。因此、池或卷组中的驱动器容量相同。
** 如果您必须添加容量更大的未分配驱动器、请注意、您添加的未分配驱动器的可用容量会减少、以便与池或卷组中驱动器的当前容量匹配。




 a| 
支持安全保护
 a| 
指示驱动器是否支持安全保护。

** 您可以使用驱动器安全功能保护池或卷组、但所有驱动器都必须具有安全功能才能使用此功能。
** 可以使用支持安全和不支持安全的驱动器组合创建池或卷组、但无法启用驱动器安全功能。
** 包含所有支持安全的驱动器的池或卷组不能接受不支持安全的驱动器来进行备用或扩展、即使未使用加密功能也是如此。
** 支持安全的驱动器可以是全磁盘加密(Full Disk Encryption、FDE)驱动器、也可以是联邦信息处理标准(Federal Information Processing Standard、FIPS)驱动器。FIPS驱动器可以是级别140-2或140-3、而级别140-3则是更高的安全性级别。如果选择140-2和140-3级别的混合驱动器、则池或卷组将以较低的安全级别(140-2)运行。




 a| 
支持DA
 a| 
指示驱动器是否支持数据保证(Data Assurance、DA)。

** 建议不要使用数据保证(Data Assurance、DA)无法向支持DA的池或卷组添加容量的驱动器。池或卷组不再具有DA功能、您也无法再对池或卷组中新创建的卷启用DA。
** 建议不要使用能够向不支持DA的池或卷组添加容量的数据保证(Data Assurance、DA)驱动器、因为该池或卷组无法利用支持DA的驱动器的功能(驱动器属性不匹配)。在这种情况下、请考虑使用不支持DA的驱动器。




 a| 
支持DULBE
 a| 
指示驱动器是否具有已取消分配或未写入逻辑块错误(DULBE")选项。DULBE"是NVMe驱动器上的一个选项、它允许EF300或EF600存储阵列支持资源配置的卷。

|===
====
. 单击 * 添加 * 。
+
如果要向池或卷组添加驱动器、则如果选择的驱动器导致池或卷组不再具有以下一个或多个属性、则会显示一个确认对话框：

+
** 磁盘架丢失保护
** 抽盒丢失保护
** 全磁盘加密功能
** 数据保证功能
** DULBE"功能


. 要继续、请单击*是*；否则请单击*取消*。


.结果
将未分配的驱动器添加到池或卷组后、该池或卷组中每个卷中的数据将重新分配、以包括其他驱动器。
