---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-settings-for-a-volume.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 更改卷的设置、例如名称、主机分配、区块大小、修改优先级、缓存、 等等。 
---
= 更改卷的设置
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以更改卷的设置、例如名称、主机分配、区块大小、修改优先级、缓存、 等等。

.开始之前
确保要更改的卷处于最佳状态。

.步骤
. 从管理页面中、选择包含要更改的卷的存储阵列。
. 选择菜单：配置 [ 管理卷 ] 。
. 选择要更改的卷、然后选择*查看/编辑设置*。
+
此时将显示卷设置对话框。选定卷的配置设置将显示在此对话框中。

. 选择*基本*选项卡以更改卷的名称和主机分配。
+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 正在设置 ... | Description 


 a| 
Name
 a| 
显示卷的名称。如果当前名称不再有意义或适用、请更改卷的名称。



 a| 
容量
 a| 
显示所选卷的已报告容量和已分配容量。



 a| 
池/卷组
 a| 
显示池或卷组的名称和RAID级别。指示池或卷组是否支持安全和启用安全。



 a| 
主机
 a| 
显示卷分配。您可以将卷分配给主机或主机集群、以便可以对其进行访问以执行I/O操作。此分配授予主机或主机集群对特定卷或存储阵列中的多个卷的访问权限。

** *已分配给*-标识可访问选定卷的主机或主机集群。
** * LUN *—逻辑单元号(LUN)是指分配给主机用于访问卷的地址空间的编号。卷以LUN的形式呈现给主机。每个主机都有自己的LUN地址空间。因此、不同的主机可以使用同一个LUN来访问不同的卷。


对于NVMe接口、此列显示命名空间ID。命名空间是指为块访问而格式化的NVM存储。它类似于SCSI中的逻辑单元、它与存储阵列中的卷相关。命名空间ID是NVMe控制器在命名空间中的唯一标识符、可设置为1到255之间的值。它类似于SCSI中的逻辑单元号(Logical Unit Number、LUN)。



 a| 
标识符
 a| 
显示选定卷的标识符。

** 全球通用标识符(WWID)。卷的唯一十六进制标识符。
** 扩展唯一标识符(Extended Unique Identifier、EUI)。卷的EUI-64标识符。
** 子系统标识符(SSID)。卷的存储阵列子系统标识符。


|===
====
. 选择*高级*选项卡可更改池或卷组中卷的其他配置设置。
+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 正在设置 ... | Description 


 a| 
应用程序和工作负载信息
 a| 
在创建卷期间、您可以创建应用程序专用的工作负载或其他工作负载。如果适用、将显示选定卷的工作负载名称、应用程序类型和卷类型。如果需要、您可以更改工作负载名称。



 a| 
服务质量设置
 a| 
*永久禁用数据保证*-只有在卷启用了数据保证(Data Assurance、DA)的情况下、才会显示此设置。DA可检查并更正在数据通过控制器向下传输到驱动器时可能发生的错误。使用此选项可在选定卷上永久禁用DA。禁用后、无法在此卷上重新启用DA。*启用预读取冗余检查*-只有当卷为厚卷时、才会显示此设置。预读取冗余检查可确定卷上的数据是否在执行读取时保持一致。如果控制器固件确定数据不一致、则启用了此功能的卷将返回读取错误。



 a| 
控制器所有权
 a| 
定义指定为卷的拥有或主控制器的控制器。控制器所有权非常重要、应仔细规划。对于总I/O、控制器应尽可能保持平衡。



 a| 
分段规模估算
 a| 
显示了分段大小调整设置、此设置仅对卷组中的卷显示。您可以更改区块大小以优化性能。*允许的区块大小转换*-系统将确定允许的区块大小转换。与当前区块大小的过渡不适当的区块大小在下拉列表中不可用。允许的过渡通常是当前区块大小的两倍或一半。例如，如果当前卷分段大小为 32 KiB ，则允许使用新的卷分段大小 16 KiB 或 64 KiB 。已启用SSD缓存的卷*—您可以为已启用SSD缓存的卷指定4-KiB分段大小。确保仅为支持 SSD 缓存且处理小块 I/O 操作的卷（例如， 16 KiB I/O 块大小或更小）选择 4-KiB 区块大小。如果为处理大型块顺序操作且已启用 SSD 缓存的卷选择 4 KiB 作为分段大小，则性能可能会受到影响。*更改区块大小所需的时间。*更改卷区块大小所需的时间取决于以下变量：

** 主机的 I/O 负载
** 卷的修改优先级
** 卷组中的驱动器数量
** 驱动器通道的数量
** 存储阵列控制器的处理能力


更改卷的区块大小时， I/O 性能会受到影响，但数据仍可用。



 a| 
修改优先级
 a| 
显示了修改优先级的设置、此设置仅适用于卷组中的卷。修改优先级用于定义为卷修改操作分配的处理时间与系统性能相关。您可以提高卷修改优先级、但这可能会影响系统性能。移动滑块条以选择优先级。*修改优先级速率*—最低优先级速率有利于系统性能、但修改操作所需时间较长。最高优先级比率有利于修改操作、但系统性能可能会受到影响。



 a| 
缓存
 a| 
显示了缓存设置、您可以更改此设置以影响卷的整体I/O性能。



 a| 
SSD 缓存
 a| 
(此功能在EF600或EF300存储系统上不可用。) 显示了SSD缓存设置、您可以在兼容卷上启用此设置以提高只读性能。如果卷共享相同的驱动器安全和数据保证功能、则这些卷是兼容的。SSD缓存功能使用一个或多个固态磁盘(SSD)来实施读取缓存。由于SSD的读取速度更快、因此应用程序性能得到了提高。由于读取缓存位于存储阵列中、因此使用该存储阵列的所有应用程序将共享缓存。只需选择要缓存的卷、即可自动动态缓存。

|===
====
. 单击 * 保存 * 。


.结果
卷设置将根据您的选择进行更改。
