---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-a-volume-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 您可以为主机可访问的一个或多个卷创建卷组。 
---
= 在适用于vCenter的SANtricity存储插件中创建卷组
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以为主机可访问的一个或多个卷创建卷组。卷组是指具有RAID级别和容量等共享特征的卷的容器。

.开始之前
请查看以下准则：

* 您至少需要一个未分配的驱动器。
* 对于一个卷组中的驱动器容量、存在限制。这些限制因主机类型而异。
* 要启用磁盘架/抽盒丢失保护、您必须创建一个卷组、该卷组使用至少位于三个磁盘架或抽盒中的驱动器、除非您使用的是RAID 1、其中至少包含两个磁盘架/抽盒。
* 在配置EF600或EF300存储阵列时、请确保每个控制器可以访问前12个插槽中相同数量的驱动器、以及最后12个插槽中相同数量的驱动器。此配置有助于控制器更有效地使用驱动器端PCIe总线。当前、系统允许在创建卷组时在"高级"功能下选择驱动器。


查看您选择的RAID级别如何影响卷组的生成容量。

* 如果选择RAID 1、则必须一次添加两个驱动器、以确保选择镜像对。如果选择四个或更多驱动器、则会实现镜像和条带化(称为RAID 10或RAID 1+0)。
* 如果选择RAID 5、则必须至少添加三个驱动器才能创建卷组。
* 如果选择RAID 6、则必须至少添加五个驱动器才能创建卷组。


.关于此任务
在创建卷组期间、您可以确定组特征、例如驱动器数量、安全功能、数据保证(Data Assurance、DA)功能、磁盘架丢失保护和抽盒丢失保护。

对于EF600和EF300存储阵列、设置还包括资源配置、驱动器块大小和卷块大小。


NOTE: 借助容量更大的驱动器以及在控制器之间分布卷的功能、可以为每个卷组创建多个卷、从而充分利用存储容量并保护数据。

.步骤
. 从管理页面中、选择卷组的存储阵列。
. 选择菜单：配置[配置池和卷组]。
. 单击菜单：创建[卷组]。
+
此时将显示创建卷组对话框。

. 键入卷组的名称。
. 选择最符合数据存储和保护要求的RAID级别。此时将显示卷组候选表、并且仅显示支持选定RAID级别的候选卷。
. (可选)如果存储阵列中有多种类型的驱动器、请选择要使用的驱动器类型。
+
此时将显示卷组候选表、并且仅显示支持选定驱动器类型和RAID级别的候选卷。

. (可选)您可以选择自动方法或手动方法来定义要在卷组中使用的驱动器。默认选择为"Automatic"方法。
+

CAUTION: 除非您是了解驱动器冗余和最佳驱动器配置的专家、否则请勿使用手动方法。

+
要手动选择驱动器、请单击*手动选择驱动器(高级)*链接。单击后、它将更改为*自动选择驱动器(高级)*。

+
使用手动方法可以选择卷组包含哪些特定驱动器。您可以选择特定的未分配驱动器以获取所需的容量。如果存储阵列包含具有不同介质类型或不同接口类型的驱动器、则只能为单个驱动器类型选择未配置的容量来创建新的卷组。

. 根据显示的驱动器特征、选择要在卷组中使用的驱动器、然后单击*创建*。


显示的驱动器特征取决于您选择的是自动方法还是手动方法。有关详细信息、请参见SANtricity System Manager文档、 https://docs.netapp.com/us-en/e-series-santricity/sm-storage/create-volume-group.html["创建卷组"^]。
