---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-storage.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 通过首先为特定应用程序类型创建工作负载来创建存储。接下来、您可以通过创建具有类似底层卷特征的卷来为工作负载添加存储容量。 
---
= 创建存储
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在适用于vCenter的存储插件中、您可以先为特定应用程序类型创建工作负载来创建存储。接下来、您可以通过创建具有类似底层卷特征的卷来为工作负载添加存储容量。



== 第1步：创建工作负载

工作负载是指支持应用程序的存储对象。您可以为每个应用程序定义一个或多个工作负载或实例。

.关于此任务
对于某些应用程序、系统会将工作负载配置为包含具有类似底层卷特征的卷。这些卷特征会根据工作负载支持的应用程序类型进行优化。例如、如果您创建了一个支持Microsoft SQL Server应用程序的工作负载、然后为该工作负载创建了卷、则底层卷特征将进行优化以支持Microsoft SQL Server。

系统建议仅针对以下应用程序类型优化卷配置：

* Microsoft SQL Server
* Microsoft Exchange Server
* 视频监控
* VMware ESXi (适用于要与虚拟机文件系统结合使用的卷)


.步骤
. 从管理页面中，选择存储阵列。
. 选择菜单：配置 [ 管理卷 ] 。
. 选择菜单：创建[工作负载]。
+
此时将显示创建应用程序工作负载对话框。

. 使用下拉列表选择要为其创建工作负载的应用程序类型、然后键入工作负载名称。
. 单击 * 创建 * 。




== 第2步：创建卷

您可以创建卷来为应用程序特定的工作负载添加存储容量、并使创建的卷对特定主机或主机集群可见。

.关于此任务
大多数应用程序类型默认为用户定义的卷配置、而其他类型则在创建卷时应用智能配置。例如、如果要为Microsoft Exchange应用程序创建卷、系统会询问您需要多少邮箱、平均邮箱容量要求是多少以及所需数据库副本的数量。系统会使用此信息为您创建最佳卷配置、您可以根据需要对其进行编辑。

您可以从菜单：配置(Manage Volumes >创建>卷)或菜单：配置(Configure Pools and Volume Groups > Create > Volumes])创建卷。对于任一选择、操作步骤 都是相同的。

创建卷的过程分为多步操作步骤。



=== 步骤2a：为卷选择主机

在第一步中、您可以为卷选择特定的主机或主机集群、也可以选择稍后分配主机。

.开始之前
请确保：

* 已定义有效的主机或主机集群(转至菜单：配置(Configure Hosts])。
* 已为主机定义主机端口标识符。
* 如果您计划创建启用了DA的卷、则主机连接必须支持数据保证(Data Assurance、DA)。如果存储阵列中控制器上的任何主机连接不支持 DA ，则关联的主机将无法访问已启用 DA 的卷上的数据。


.关于此任务
分配卷时，请记住以下准则：

* 主机的操作系统可以对主机可以访问的卷数设置特定限制。在创建卷供特定主机使用时、请记住此限制。
* 您可以为存储阵列中的每个卷定义一个分配。
* 分配的卷在存储阵列中的控制器之间共享。
* 主机或主机集群不能使用同一逻辑单元号(LUN)两次来访问卷。您必须使用唯一的LUN。
* 如果要加快创建卷的过程、可以跳过主机分配步骤、使新创建的卷脱机初始化。



NOTE: 如果您尝试将卷分配给与主机集群中已建立的主机分配冲突的主机集群、则向主机分配卷将失败。

.步骤
. 从管理页面中，选择存储阵列。
. 选择菜单：配置 [ 管理卷 ] 。
. 选择菜单：创建 [ 卷 ] 。
+
此时将显示选择主机对话框。

. 从下拉列表中，选择要将卷分配到的特定主机或主机集群，或者选择稍后再分配主机或主机集群。
. 要继续为选定主机或主机集群创建卷、请单击*下一步。*
+
此时将显示选择工作负载对话框。





=== 第2b步：为卷选择工作负载

在第二步中、您可以选择一个工作负载、以便为VMware等特定应用程序自定义存储阵列配置。

.关于此任务
此任务介绍如何为工作负载创建卷。通常、工作负载包含具有类似特征的卷、这些卷会根据工作负载支持的应用程序类型进行优化。您可以在此步骤中定义工作负载、也可以选择现有工作负载。

请牢记以下准则：

* 在使用特定于应用程序的工作负载时、系统建议使用经过优化的卷配置、以最大程度地减少应用程序工作负载I/O与应用程序实例中的其他流量之间的争用。您可以查看建议的卷配置、然后使用添加/编辑卷对话框(可在下一步中找到)编辑、添加或删除系统建议的卷和特征。
* 使用其他应用程序类型时、您可以使用添加/编辑卷对话框(可在下一步中使用)手动指定卷配置。


.步骤
. 执行以下操作之一：
+
** 选择 * 为现有工作负载创建卷 * 选项，然后从下拉列表中选择工作负载。
** 选择*创建新工作负载*选项为支持的应用程序或"其他"应用程序定义新工作负载、然后执行以下步骤：
+
*** 从下拉列表中，选择要为其创建新工作负载的应用程序的名称。如果未列出要在此存储阵列上使用的应用程序、请选择"其他"条目之一。
*** 输入要创建的工作负载的名称。




. 单击 * 下一步 * 。
. 如果您的工作负载与支持的应用程序类型关联，请输入所请求的信息；否则，请转到下一步。




=== 第2c步：添加或编辑卷

在第三步中、您可以定义卷配置。

.开始之前
* 池或卷组必须具有足够的可用容量。
* 一个卷组中允许的最大卷数为256。
* 池中允许的最大卷数取决于存储系统型号：
+
** 2、048个卷(EF600和E5700系列)
** 1、024个卷(EF300)
** 512个卷(E2800系列)


* 要创建启用了数据保证(Data Assurance、DA)的卷、您计划使用的主机连接必须支持DA。
+
** 如果要创建启用了DA的卷、请选择一个支持DA的池或卷组(在Pool and volume group candidates表中的"DA"旁边查找*是*)。
** DA 功能在池和卷组级别提供。DA 保护功能可检查并更正数据通过控制器向下传输到驱动器时可能发生的错误。为新卷选择支持 DA 的池或卷组可确保检测到并更正任何错误。
** 如果存储阵列中控制器上的任何主机连接不支持 DA ，则关联的主机将无法访问已启用 DA 的卷上的数据。


* 要创建启用了安全保护的卷，必须为存储阵列创建安全密钥。
+
** 如果要创建启用了安全的卷，请选择一个支持安全的池或卷组（在 Pool and volume group candidates 表中，查找 "Secure-capable" 旁边的是）。
** 驱动器安全功能在池和卷组级别提供。支持安全的驱动器可防止未经授权访问从存储阵列中物理删除的驱动器上的数据。启用了安全保护的驱动器会在写入期间对数据进行加密，并在读取期间使用唯一的加密密钥对数据进行解密。
** 池或卷组可以同时包含支持安全和不支持安全的驱动器，但所有驱动器都必须具有安全功能才能使用其加密功能。


* 要创建资源配置的卷，所有驱动器都必须是具有已取消分配或未写入逻辑块错误（ DULBE" ）选项的 NVMe 驱动器。


.关于此任务
您可以从符合条件的池或卷组创建卷、这些池或卷组显示在添加/编辑卷对话框中。对于每个符合条件的池和卷组，将显示可用驱动器数和总可用容量。

对于某些特定于应用程序的工作负载，每个符合条件的池或卷组都会根据建议的卷配置显示建议的容量，并以 GiB 显示剩余可用容量。对于其他工作负载，在将卷添加到池或卷组并指定报告的容量时，将显示建议的容量。

.步骤
. 根据您在上一步中选择的是其他工作负载还是应用程序专用工作负载，选择以下操作之一：
+
** *其他*-单击要用于创建一个或多个卷的每个池或卷组中的*添加新卷*。
+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 字段 | Description 


 a| 
卷名称
 a| 
在卷创建序列期间，系统会为卷分配默认名称。您可以接受默认名称，也可以提供一个更具描述性的名称来指示卷中存储的数据类型。



 a| 
已报告容量
 a| 
定义新卷的容量以及要使用的容量单位（ MIB ， GiB 或 TiB ）。对于厚卷、最小容量为1 MiB、最大容量由池或卷组中驱动器的数量和容量决定。请注意、复制服务(Snapshot映像、Snapshot卷、卷副本和远程镜像)也需要存储容量；因此、 请勿将所有容量分配给标准卷。池中的容量以4 GiB为增量进行分配。分配的容量不是4 GiB的倍数、但不可用。要确保整个容量可用、请以4 GiB为增量指定容量。如果存在不可用的容量，则要重新获得该容量，唯一的方法是增加卷的容量。



 a| 
卷块大小(仅限EF300和EF600)
 a| 
显示了可为卷创建的块大小：

*** 512 – 512 字节
*** 4 k – 4 ， 096 字节




 a| 
区块大小
 a| 
显示了分段大小调整设置，此设置仅适用于卷组中的卷。您可以更改区块大小以优化性能。*允许的区块大小转换*-系统将确定允许的区块大小转换。与当前区块大小的过渡不适当的区块大小在下拉列表中不可用。允许的过渡通常是当前区块大小的两倍或一半。例如，如果当前卷分段大小为 32 KiB ，则允许使用新的卷分段大小 16 KiB 或 64 KiB 。已启用SSD缓存的卷*—您可以为已启用SSD缓存的卷指定4-KiB分段大小。确保仅为支持 SSD 缓存且处理小块 I/O 操作的卷（例如， 16 KiB I/O 块大小或更小）选择 4-KiB 区块大小。如果为处理大型块顺序操作且已启用 SSD 缓存的卷选择 4 KiB 作为分段大小，则性能可能会受到影响。*更改区块大小所需的时间*-更改卷区块大小所需的时间取决于以下变量：

*** 主机的 I/O 负载
*** 卷的修改优先级
*** 卷组中的驱动器数量
*** 驱动器通道的数量
*** 存储阵列控制器的处理能力


更改卷的区块大小时， I/O 性能会受到影响，但数据仍可用。



 a| 
支持安全保护
 a| 
只有当池或卷组中的驱动器具有安全功能时、"安全功能"旁边才会显示*是*。驱动器安全性可防止未经授权访问从存储阵列中物理删除的驱动器上的数据。只有在启用了驱动器安全功能且为存储阵列设置了安全密钥时，此选项才可用。池或卷组可以同时包含支持安全和不支持安全的驱动器，但所有驱动器都必须具有安全功能才能使用其加密功能。



 a| 
da.
 a| 
只有当池或卷组中的驱动器支持数据保证(Data Assurance、DA)时、"DA"旁边才会显示*是*。DA 可提高整个存储系统的数据完整性。通过 DA ，存储阵列可以检查在数据通过控制器向下传输到驱动器时可能发生的错误。对新卷使用 DA 可确保检测到任何错误。



 a| 
已配置资源(仅限EF300和EF600)
 a| 
只有当驱动器支持此选项时、"已配置资源"旁边才会显示*是*。资源配置是EF300和EF600存储阵列中提供的一项功能、可在不执行后台初始化过程的情况下立即使用卷。

|===
====
** *应用程序专用工作负载*—单击*下一步*接受系统为选定工作负载建议的卷和特征、或者单击*编辑卷*更改、添加或删除系统为选定工作负载建议的卷和特征。
+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 字段 | Description 


 a| 
卷名称
 a| 
在卷创建序列期间，系统会为卷分配默认名称。您可以接受默认名称，也可以提供一个更具描述性的名称来指示卷中存储的数据类型。



 a| 
已报告容量
 a| 
定义新卷的容量以及要使用的容量单位（ MIB ， GiB 或 TiB ）。对于厚卷、最小容量为1 MiB、最大容量由池或卷组中驱动器的数量和容量决定。请注意、复制服务(Snapshot映像、Snapshot卷、卷副本和远程镜像)也需要存储容量；因此、 请勿将所有容量分配给标准卷。池中的容量以 4 GiB 为增量进行分配。分配的容量不是 4 GiB 的倍数，但不可用。要确保整个容量可用，请以 4 GiB 为增量指定容量。如果存在不可用的容量，则要重新获得该容量，唯一的方法是增加卷的容量。



 a| 
卷类型
 a| 
卷类型指示为特定于应用程序的工作负载创建的卷类型。



 a| 
卷块大小(仅限EF300和EF600)
 a| 
显示了可为卷创建的块大小：

*** 512—512字节
*** 4 k—4、096字节




 a| 
区块大小
 a| 
显示了分段大小调整设置，此设置仅适用于卷组中的卷。您可以更改区块大小以优化性能。*允许的区块大小转换*-系统将确定允许的区块大小转换。与当前区块大小的过渡不适当的区块大小在下拉列表中不可用。允许的过渡通常是当前区块大小的两倍或一半。例如，如果当前卷分段大小为 32 KiB ，则允许使用新的卷分段大小 16 KiB 或 64 KiB 。已启用SSD缓存的卷*—您可以为已启用SSD缓存的卷指定4-KiB分段大小。确保仅为支持 SSD 缓存且处理小块 I/O 操作的卷（例如， 16 KiB I/O 块大小或更小）选择 4-KiB 区块大小。如果为处理大型块顺序操作且已启用 SSD 缓存的卷选择 4 KiB 作为分段大小，则性能可能会受到影响。*更改区块大小所需的时间*-更改卷区块大小所需的时间取决于以下变量：

*** 主机的 I/O 负载
*** 卷的修改优先级
*** 卷组中的驱动器数量
*** 驱动器通道的数量
*** 存储阵列控制器的处理能力


更改卷的区块大小时， I/O 性能会受到影响，但数据仍可用。



 a| 
支持安全保护
 a| 
只有当池或卷组中的驱动器具有安全功能时、"安全功能"旁边才会显示*是*。驱动器安全性可防止未经授权访问从存储阵列中物理删除的驱动器上的数据。只有在已启用驱动器安全功能且为存储阵列设置了安全密钥时、此选项才可用。池或卷组可以同时包含支持安全和不支持安全的驱动器，但所有驱动器都必须具有安全功能才能使用其加密功能。



 a| 
da.
 a| 
只有当池或卷组中的驱动器支持数据保证(Data Assurance、DA)时、"DA"旁边才会显示*是*。DA 可提高整个存储系统的数据完整性。通过 DA ，存储阵列可以检查在数据通过控制器向下传输到驱动器时可能发生的错误。对新卷使用 DA 可确保检测到任何错误。



 a| 
已配置资源(仅限EF300和EF600)
 a| 
只有当驱动器支持此选项时、"已配置资源"旁边才会显示*是*。资源配置是EF300和EF600存储阵列中提供的一项功能、可在不执行后台初始化过程的情况下立即使用卷。

|===
====


. 要继续对选定应用程序执行卷创建序列，请单击 * 下一步 * 。




=== 第2D步：查看卷配置

在最后一步中、您将查看要创建的卷的摘要并进行任何必要的更改。

.步骤
. 查看要创建的卷。要进行更改，请单击 * 返回 * 。
. 对卷配置感到满意后，单击 * 完成 * 。


.完成后
* 在vSphere Client中、为卷创建数据存储库。
* 在应用程序主机上执行任何必要的操作系统修改、以便应用程序可以使用卷。
* 运行基于主机的`hot_add`实用程序或操作系统专用实用程序(可从第三方供应商获得)、然后运行`SMdevices`实用程序将卷名称与主机存储阵列名称关联起来。
+
`hot_add`实用程序和`SMdevices`实用程序作为`SMutils`软件包的一部分提供。`SMutils`软件包是一组实用程序、用于验证主机从存储阵列中看到的内容。它作为 SANtricity 软件安装的一部分提供。


