---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-host-cluster.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 如果两个或更多主机需要对相同卷进行I/O访问、则可以创建主机集群。 
---
= 在适用于vCenter的SANtricity存储插件中创建主机集群
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
如果两个或更多主机需要对相同卷进行I/O访问、则可以创建主机集群。

.关于此任务
创建主机集群时、请记住以下准则：

* 除非有两个或更多主机可用于创建集群、否则此操作不会启动。
* 主机集群中的主机可以具有不同的操作系统(异构)。
* 主机集群中的NVMe主机不能与非NVMe主机混合使用。
* 要创建启用了数据保证(Data Assurance、DA)的卷、您计划使用的主机连接必须支持DA。
+
如果存储阵列中控制器上的任何主机连接不支持 DA ，则关联的主机将无法访问已启用 DA 的卷上的数据。

* 如果您选择的名称已在使用中，则此操作不会成功。
* 名称长度不能超过 30 个字符。


.步骤
. 从管理页面中，选择具有主机连接的存储阵列。
. 选择菜单：配置 [ 配置主机 ] 。
+
此时将打开配置主机页面。

. 选择菜单：创建[主机集群]。
+
此时将显示创建主机集群对话框。

. 根据需要选择主机集群的设置。
+
|===
| 正在设置 ... | Description 


| Name | 键入新主机集群的名称。 


| 选择要共享卷访问的主机 | 从下拉列表中选择两个或更多主机。列表中仅显示尚未加入主机集群的主机。 
|===
. 单击 * 创建 * 。
+
如果选定主机连接到具有不同数据保证(Data Assurance、DA)功能的接口类型、则会显示一个对话框、其中会显示一条消息、指出DA在主机集群上不可用。此不可用性将阻止将已启用DA的卷添加到主机集群中。选择*是*继续、或者选择*否*取消。

+
DA 可提高整个存储系统的数据完整性。通过DA、存储阵列可以检查在主机和驱动器之间移动数据时可能发生的错误。对新卷使用 DA 可确保检测到任何错误。



.结果
此时、新主机集群将显示在表中、而分配的主机将显示在下一行中。

.完成后
您必须将卷分配给主机集群、以便用于I/O操作。转至 link:vc-olh-assign-volumes-to-hosts.html["将卷分配给主机"]。
