---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-provisioning-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 您可以创建称为卷的数据容器、以便主机可以访问阵列上的存储。 
---
= 配置概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在适用于vCenter的存储插件中、您可以创建称为卷的数据容器、以便主机可以访问阵列上的存储。



== 卷类型和特征

卷是一种数据容器，用于管理和组织存储阵列上的存储空间。

您可以使用存储阵列上的可用存储容量创建卷，这有助于组织系统的资源。" 卷 " 的概念类似于在计算机上使用文件夹 / 目录来组织文件以实现快速访问。

卷是主机唯一可见的数据层。在 SAN 环境中，卷会映射到逻辑单元号（ LUN ）。这些LUN可保存可使用存储阵列支持的一个或多个主机访问协议(包括FC、iSCSI和SAS)访问的用户数据。

池或卷组中的每个卷都可以根据要存储的数据类型具有自己的特征。其中一些特征包括：

* *区块大小*—区块是指存储阵列移至条带中下一个驱动器(RAID组)之前存储在驱动器上的数据量(以千字节(KiB)为单位)。区块大小等于或小于卷组的容量。区块大小是固定的、不能为池更改。
* *容量*-使用池或卷组中的可用容量创建卷。在创建卷之前、池或卷组必须已存在、并且必须具有足够的可用容量来创建卷。
* *控制器所有权*-所有存储阵列均可具有一个或两个控制器。在单控制器阵列上、卷的工作负载由单个控制器管理。在双控制器阵列上、卷将具有一个首选控制器(A或B)、该控制器"拥有"该卷。在双控制器配置中、使用自动负载平衡功能自动调整卷所有权、以便在工作负载在控制器之间移动时更正任何负载平衡问题。自动负载平衡可实现自动I/O工作负载平衡、并确保在两个控制器之间动态管理和平衡来自主机的传入I/O流量。
* *卷分配*—您可以在创建卷时或稍后为主机授予对卷的访问权限。所有主机访问均通过逻辑单元号(LUN)进行管理。主机会检测分配给卷的LUN。如果要将卷分配给多个主机、请使用集群软件确保卷可供所有主机使用。
+
主机类型可以对主机可以访问的卷数进行特定限制。在创建卷供特定主机使用时、请记住此限制。

* *资源配置*—对于EF600或EF300存储阵列、您可以指定在不执行后台初始化过程的情况下立即使用卷。资源配置卷是SSD卷组或池中的厚卷、在创建卷时会分配(分配给卷)驱动器容量、但会取消分配(取消映射)驱动器块。
* *描述性名称*—您可以根据需要为卷命名任何名称、但我们建议将此名称设置为描述性名称。


在创建卷期间、系统会为每个卷分配容量、并为其分配名称、区块大小(仅限卷组)、控制器所有权以及卷到主机的分配。卷数据会根据需要在控制器之间自动进行负载平衡。



== 卷的容量

存储阵列中的驱动器可为数据提供物理存储容量。开始存储数据之前、必须先将分配的容量配置到称为池或卷组的逻辑组件中。您可以使用这些存储对象配置、存储、维护和保留存储阵列上的数据。



=== 用于创建和扩展卷的容量

您可以从池或卷组中的未分配容量或可用容量创建卷。

* 使用未分配的容量创建卷时、您可以同时创建池或卷组和卷。
* 使用可用容量创建卷时、您正在现有池或卷组上创建一个额外的卷。扩展卷容量后、必须手动增加文件系统大小以匹配。如何执行此操作取决于所使用的文件系统。有关详细信息、请参见主机操作系统文档。



NOTE: 插件界面不提供创建精简卷的选项。



=== 报告的卷容量

报告的卷容量等于分配的物理存储容量。必须存在全部物理存储容量。物理分配的空间等于向主机报告的空间。

通常、您会将卷的报告容量设置为您认为卷将增长到的最大容量。卷可为应用程序提供高且可预测的性能、这主要是因为所有用户容量都是在创建时预留和分配的。



=== 容量限制

卷的最小容量为1 MiB、最大容量由池或卷组中驱动器的数量和容量决定。

增加卷的报告容量时、请记住以下准则：

* 您最多可以指定三个小数位(例如、55.375 GiB)。
* 容量必须小于(或等于)卷组中的最大可用容量。创建卷时、系统会为动态区块大小(DSS)迁移预先分配一些额外容量。DSS迁移是软件的一项功能、可用于更改卷的区块大小。
* 某些主机操作系统支持大于2 TiB的卷(报告的最大容量由主机操作系统决定)。事实上、某些主机操作系统最多支持128个TiB卷。有关更多详细信息、请参见主机操作系统文档。




== 应用程序特定的工作负载

创建卷时、您可以选择一个工作负载来为特定应用程序自定义存储阵列配置。

工作负载是指支持应用程序的存储对象。您可以为每个应用程序定义一个或多个工作负载或实例。对于某些应用程序、系统会将工作负载配置为包含具有类似底层卷特征的卷。这些卷特征会根据工作负载支持的应用程序类型进行优化。例如、如果您创建了一个支持Microsoft SQL Server应用程序的工作负载、然后为该工作负载创建了卷、则底层卷特征将进行优化以支持Microsoft SQL Server。

在创建卷期间、系统会提示您回答有关工作负载使用情况的问题解答 问题。例如、如果要为Microsoft Exchange创建卷、系统会询问您需要多少邮箱、平均邮箱容量要求是多少以及所需数据库副本的数量。系统会使用此信息为您创建最佳卷配置、您可以根据需要对其进行编辑。或者、您也可以在卷创建序列中跳过此步骤。



=== 工作负载类型

您可以创建两种类型的工作负载：特定于应用程序的工作负载和其他工作负载。

* *应用程序专用*—当您使用应用程序专用工作负载创建卷时、系统可能会建议优化卷配置、以最大程度地减少应用程序工作负载I/O与应用程序实例中的其他流量之间的争用。对于为以下应用程序类型创建的工作负载、系统会自动建议并优化卷特征、例如I/O类型、区块大小、控制器所有权以及读写缓存。
+
** Microsoft SQL Server
** Microsoft Exchange Server
** 视频监控应用程序
** VMware ESXi (适用于要与虚拟机文件系统结合使用的卷)
+
您可以使用添加/编辑卷对话框查看建议的卷配置以及编辑、添加或删除系统建议的卷和特征。



* *其他(或不支持特定卷创建的应用程序)*- 其他工作负载使用的卷配置必须手动指定、以便在创建与特定应用程序无关的工作负载时、或者系统没有为要在存储阵列上使用的应用程序进行内置优化时。您必须使用添加/编辑卷对话框手动指定卷配置。




=== 应用程序和工作负载视图

要查看应用程序和工作负载、请启动System Manager。在此界面中、您可以通过多种不同方式查看与应用程序特定工作负载关联的信息：

* 您可以选择卷图块中的应用程序和工作负载选项卡、以查看按工作负载分组的存储阵列卷以及与工作负载关联的应用程序类型。
* 您可以选择"性能"图块中的"应用程序和工作负载"选项卡、以查看逻辑对象的性能指标(延迟、IOPS和MBs)。对象按应用程序和关联工作负载分组。通过定期收集此性能数据、您可以建立基线测量并分析趋势、这有助于您调查与I/O性能相关的问题。

