---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-upgrade-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 您可以为多个相同类型的存储阵列管理SANtricity 软件和NVSRAM升级。 
---
= 升级概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在适用于vCenter的存储插件中、您可以为多个相同类型的存储阵列管理SANtricity 软件和NVSRAM升级。



== 升级工作流

以下步骤提供了执行软件升级的高级工作流：

. 您可以从支持站点下载最新的SANtricity OS文件(可从支持页面访问链接)。将此文件保存在管理主机系统(在浏览器中访问此插件的主机)上、然后解压缩此文件。
. 在插件中、您可以将SANtricity OS软件文件和NVSRAM文件加载到存储库(存储文件的服务器区域)。
. 将文件加载到存储库中后、您可以选择要在升级中使用的文件。从升级SANtricity OS软件页面中、选择操作系统软件文件和NVSRAM文件。选择软件文件后、此页面上将显示兼容存储阵列列表。然后、选择要使用新软件升级的存储阵列。(不能选择不兼容的阵列。)
. 然后、您可以立即开始软件传输和激活、也可以选择稍后暂存文件以进行激活。在升级过程中、插件将执行以下任务：
+
** 对存储阵列执行运行状况检查、以确定是否存在任何可能阻止升级完成的条件。如果任何阵列未通过运行状况检查，您可以跳过该特定阵列并继续对其他阵列进行升级，也可以停止整个过程并对未通过的阵列进行故障排除。
** 将升级文件传输到每个控制器。
** 重新启动控制器并激活新的操作系统软件、一次一个控制器。激活期间、现有操作系统文件将替换为新文件。





NOTE: 您还可以指定稍后激活此软件。



== 升级注意事项

在升级多个存储阵列之前、请在规划过程中查看主要注意事项。



=== 当前版本

您可以从适用于vCenter的存储插件的"管理"页面查看每个已发现存储阵列的当前SANtricity OS软件版本。此版本显示在SANtricity OS软件列中。单击每行中的操作系统版本时、会在弹出对话框中显示控制器固件和NVSRAM信息。



=== 其他需要升级的组件

在升级过程中、您可能还需要升级主机的多路径/故障转移驱动程序或HBA驱动程序、以便主机可以正确地与控制器进行交互。有关兼容性信息，请参见 link:https://imt.netapp.com/matrix/["互操作性表工具"^]。



=== 双控制器

如果存储阵列包含两个控制器，并且您安装了多路径驱动程序，则在升级期间，存储阵列可以继续处理 I/O 。在升级期间，将执行以下过程：

. 控制器 A 将其所有 LUN 故障转移到控制器 B
. 升级在控制器 A 上进行
. 控制器 A 将收回其 LUN 以及控制器 B 的所有 LUN 。
. 升级在控制器 B 上进行


升级完成后，您可能需要在控制器之间手动重新分布卷，以确保卷返回到正确的所属控制器。
