---
permalink: maintenance-ef50-ef80/controller-replace-prepare.html 
sidebar: sidebar 
keywords: ef50, ef80, prepare the impaired controller 
summary: 通过打开替换控制器的包装，确认其部件号正确，并备份配置数据库，准备替换 EF50 或 EF80 存储系统中受损的控制器。 
---
= 准备更换控制器 - EF50 和 EF80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
准备更换 EF50 或 EF80 存储系统中受损的控制器，方法是打开更换控制器的包装，记下其 MAC 地址，确认其部件号正确，并备份存储系统的配置数据库。

.步骤
. 拆开更换控制器的包装，并将其放置在平坦的无静电表面上。
+
保存包装材料，以便在退回受损控制器时使用。

. 记下更换控制器侧面的 MAC 地址。
+
您将在稍后的控制器更换过程中使用 MAC 地址。

. 确认替换控制器上的零件号与 SANtricity System Manager 中控制器的替换零件号相同：
+

CAUTION: *可能丢失数据访问权限*：如果两个部件号不同，请不要尝试此过程。存在不匹配的控制器会导致更换控制器在您将其联机时锁定。

+
.. 记下更换控制器侧面的部件号。
.. 找到 Recovery Guru 详细信息区域中显示的受损控制器的更换零件号。
+
如果您需要手动查找此号码，请按照以下步骤操作：

+
... 选择 *Hardware* > *Controllers and components*。
... 选择受损控制器（Controller A 或 Controller B）的控制器图形以查看上下文菜单。
... 选择 * 查看设置 * 。
... 在 * 基本 * 选项卡上，记下控制器的 * 更换部件号 * 。


.. 比较两个零件编号以确认它们是相同的。
.. 下一步取决于零件号是否相同：
+
[cols="1,2"]
|===
| 条件 | 操作 


 a| 
两个零件编号相同
 a| 
继续下一步。



 a| 
这两个零件编号不同
 a| 
您不能继续此过程。

请联系  https://mysupport.netapp.com/site/global/dashboard["NetApp 支持"] 以获得帮助。

|===


. 使用 SANtricity System Manager 备份存储系统的配置数据库。
+
如果删除控制器时出现问题，您可以使用保存的文件还原您的配置。系统保存 RAID 配置数据库的当前状态，其中包括控制器上卷组和磁盘池的所有数据。

+
.. 选择*支持›支持中心›诊断*。
.. 选择 * 收集配置数据 * 。
.. 选择 *Collect*。
+
此文件将保存在浏览器的 "Downloads" 文件夹中，名为 * configurationData-<arrayName>-<DateTime>.7z* 。





.下一步是什么？
准备好控制器更换后，link:controller-replace-offline-controller.html["使受损控制器脱机"]。
