---
permalink: maintenance-ef50-ef80/controller-replace-offline-controller.html 
sidebar: sidebar 
keywords: ef50, ef80, offline the impaired controller 
summary: 将受损的控制器在 EF50 或 EF80 存储系统中离线，以防止数据丢失，并确保更换控制器时的系统稳定性。 
---
= 使受损控制器脱机 - EF50 和 EF80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
将受损的控制器在 EF50 或 EF80 存储系统中离线，以防止数据丢失，并确保更换控制器时的系统稳定性。

.执行前
* 您必须已满足此程序的link:controller-replace-requirements.html["要求"]。
* 您必须已完成此程序的link:controller-replace-prepare.html["准备"]。


.关于此任务
每当您将控制器置于离线状态时，都需要等待至少一分钟才能使控制器恢复联机。此等待期允许存储系统更新控制器的状态，并确保将所有缓存数据写入驱动器。

.步骤
. 如果受损控制器尚未离线，请使用 SANtricity System Manager 将其置于离线状态：
+
.. 选择 *Hardware* > *Controllers and components* 以显示控制器。
.. 选择要置于脱机状态的控制器以显示其内容菜单。
.. 选择 *Place offline*，然后确认您要执行此操作。
+

NOTE: 如果您使用尝试脱机的控制器访问 SANtricity System Manager，则会显示 SANtricity System Manager Unavailable 消息。选择*连接到备用网络连接*以使用其他控制器自动访问 SANtricity System Manager。



. 等待 SANtricity System Manager 将控制器状态更新为脱机。
+

CAUTION: 更新状态之前，请勿开始任何其他操作。

. 使用 Recovery Guru 确认移除有故障的组件是安全的：
+
.. 选择 *Recheck*。
.. 确认详细信息区域中的 *OK to remove* 字段显示 *Yes*。
+

CAUTION: 如果 *OK to remove* 字段未显示 *Yes*，请不要继续移除有故障的组件。相反，请使用 Recovery Guru 对问题进行故障排除。





.下一步是什么？
将受损控制器脱机后，link:controller-replace-move-hardware.html["更换受损的控制器"]。
