---
permalink: config-windows/install-storage-manager-for-smcli-task.html 
sidebar: sidebar 
keywords: install Storage Manager Windows, install CLI Windows, install command line interface, install Host Context Agent, install HCA, express Windows configuration, software configuration, Windows host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 在 Windows 快速方法中安装适用于 CLI 和 HCA 的 Storage Manager 。 
---
= 安装适用于SMCli(11.53或更早版本)的SANtricity Storage Manager - Windows
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用的是 SANtricity 软件 11.53 或更早版本，则可以在管理工作站上安装 SANtricity 存储管理器软件，以帮助管理阵列。

SANtricity 存储管理器包括用于执行其他管理任务的命令行界面（ CLI ）以及用于通过 I/O 路径将主机配置信息推送到存储阵列控制器的主机上下文代理。


NOTE: 如果您使用的是 SANtricity 软件 11.60 及更高版本，则无需执行以下步骤。SANtricity 安全命令行界面（ SMcli ）包含在 SANtricity 操作系统中，可通过 SANtricity 系统管理器下载。有关如何通过SANtricity系统管理器下载SMcli的详细信息、请参阅 link:https://docs.netapp.com/us-en/e-series-santricity/sm-settings/download-cli.html["下载SANtricity系统管理器联机帮助下的命令行界面(CLI)主题"^]


NOTE: 从SANtricity软件11.80.1版开始、不再支持主机上下文代理。

.开始之前
确保您已具备以下条件：

* SANtricity 软件 11.53 或更早版本。
* 正确的管理员或超级用户权限。
* 适用于 SANtricity Storage Manager 客户端的系统，具有以下最低要求：
+
** * RAM * ： 2 GB 用于 Java Runtime Engine
** * 磁盘空间 * ： 5 GB
** * 操作系统 / 架构 * ：有关确定支持的操作系统版本和架构的指导，请访问 http://mysupport.netapp.com["NetApp 支持"^]。从 * 下载 * 选项卡中，转到菜单：下载 [E 系列 SANtricity 存储管理器 ] 。




.步骤
. 从下载 SANtricity 软件版本 http://mysupport.netapp.com["NetApp 支持"^]。在 * 下载 * 选项卡中，菜单：下载 [E 系列 SANtricity 存储管理器 ] 。
. 运行 SANtricity 安装程序。双击要执行的 SMIA* 。 exe 安装包。
. 使用安装向导在管理工作站上安装软件。

