---
permalink: upgrade-controllers/complete-upgrade-controllers-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E4000, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, vendor ID, upgrade status, upgrade validate 
summary: 启动控制器架并验证控制器软件版本，以完成控制器升级。然后，您可以收集支持数据并恢复操作。 
---
= 完成控制器升级
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
启动控制器架并验证控制器软件版本，以完成控制器升级。然后，您可以收集支持数据并恢复操作。

如果要升级双工控制器驱动器托盘中的控制器，请重复所有步骤以完成第二个控制器的升级。



== 第 1 步：启动控制器

您必须打开控制器架的电源，以确认其工作正常。

.步骤
. 打开连接到控制器驱动器托盘的每个驱动器托盘背面的电源开关
. 等待两分钟，使驱动器加速。
. 打开控制器驱动器托盘背面的电源开关
. 等待三分钟，以完成启动过程。
. 如果您要对 E2800 或 E5700 控制器执行完整的控制器更换，请根据您的驱动器安全场景继续执行以下过程之一。
+
|===
| 完整的控制器更换类型 | 操作步骤和前提条件 


 a| 
所有不安全的驱动器，不包括外部或内部密钥管理
 a| 
继续执行下一步。



 a| 
混合使用安全和不安全驱动器，内部密钥管理
 a| 
您必须先创建内部安全密钥，然后手动导入安全密钥以解锁受保护的驱动器。驱动器解锁后，您可以访问这些驱动器。

.. 创建内部安全密钥
.. 使用内部密钥管理和一个或多个驱动器进行控制器交换
.. 运行smclient命令、 `set allDrives nativeState`。
.. 等待两个控制器重新启动。




 a| 
所有安全驱动器，内部密钥管理
 a| 
使用内部密钥管理和一个或多个驱动器进行控制器交换



 a| 
混合使用安全和不安全驱动器，外部密钥管理
 a| 
继续执行下一步。

执行控制器更换后，控制器将自动与外部密钥管理服务器重新同步，驱动器将解锁并可访问。


NOTE: 在使用内部密钥管理对混合安全驱动器执行控制器更换后，如果您收到七段显示锁定代码 `L5` ，请联系技术支持。



 a| 
所有受保护驱动器，外部密钥管理，您已暂时切换回内部密钥管理以更换控制器操作步骤
 a| 
您必须先使用内部密钥管理操作步骤解锁受保护的驱动器。在驱动器解锁后，您可以通过为存储阵列创建新的外部安全密钥来过渡回外部密钥管理。

.. 使用内部密钥管理和一个或多个驱动器进行控制器交换
.. 创建外部安全密钥
.. 运行smclient命令、 `set allDrives nativeState`。
.. 等待两个控制器重新启动。




 a| 
所有安全驱动器，外部密钥管理，您尚未临时切换到内部密钥管理来更换控制器操作步骤
 a| 
使用外部密钥管理和所有驱动器进行控制器交换。有关详细说明、请参见 https://docs.netapp.com/us-en/e-series/upgrade-controllers/upgrade-unlock-drives-task.html#external-key-management["外部密钥管理"^]。

|===




== 第 2 步：检查控制器和托盘的状态

您可以使用 LED 和存储管理软件检查控制器和托盘的状态。

.步骤
. 查看控制器 A 上的 LED ，确保其正确启动。
+
重新启动期间，需要执行主机链路服务操作的 LED 将变为绿色。

+
控制器成功完成重新启动后、您可以使用存储管理软件发现新的控制器箱。

. 如果控制器驱动器托盘的任何 "Service Action Required" LED 为 _ON_ ，或者 "Controller Service Action Required LED" 为 _ON_ ：
+
.. 检查控制器箱是否已正确安装，以及所有缆线是否均已正确就位。如有必要，重新安装控制器箱。
.. 再次检查控制器驱动器托盘的 "Service Action Required LED" 和 "Controller Service Action Required LED" 。如果问题未得到解决，请联系技术支持。


. 对于双工配置，对控制器 B 重复步骤 1 到步骤 2
. 使用 LED 和存储管理软件，检查存储阵列中所有托盘的状态。如果任何组件处于 Needs Attention 状态，请使用 Recovery Guru 进行故障排除。如果问题未得到解决，请联系技术支持。




== 第 3 步：验证控制器软件版本

您必须确保新控制器运行的操作系统（控制器固件）级别和 NVSRAM 正确。

.步骤
. 如果控制器升级涉及协议更改（例如，光纤通道到 iSCSI ），并且您已为存储阵列定义了主机，请将新主机端口与主机关联：
+
.. 在 System Manager 中，选择菜单： Storage[Hosts] 。
.. 选择要与端口关联的主机，然后单击 * 查看 / 编辑设置 * 。
+
此时将显示一个对话框，其中显示了当前主机设置。

.. 单击 * 主机端口 * 选项卡。
+
此对话框将显示当前主机端口标识符。

.. 要更新与每个主机关联的主机端口标识符信息，请将旧主机适配器中的主机端口 ID 替换为新主机适配器的新主机端口 ID 。
.. 对每个主机重复步骤 d 。
.. 单击 * 保存 * 。


+
有关兼容硬件的信息，请参见 https://mysupport.netapp.com/NOW/products/interoperability["NetApp 互操作性表"^] 和 http://hwu.netapp.com/home.aspx["NetApp Hardware Universe"^]。

. 如果在准备机头交换时为所有精简卷禁用了回写缓存，请重新启用回写缓存。
+
.. 在 System Manager 中，选择菜单： Storage[Volumes] 。
.. 选择任何卷，然后选择菜单：更多（更改缓存设置）。
+
此时将显示更改缓存设置对话框。存储阵列上的所有卷都会显示在此对话框中。

.. 选择*Basic*选项卡并启用读取缓存和写入缓存设置。
.. 单击 * 保存 * 。


. 如果在准备机头交换时禁用了 SAML ，请重新启用 SAML 。
+
.. 在 System Manager 中，选择菜单：设置 [ 访问管理 ] 。
.. 选择 * SAML * 选项卡，然后按照页面上的说明进行操作。


. 使用 GUI 或 CLI 收集有关存储阵列的支持数据：
+
** 使用System Manager收集并保存存储阵列的支持包。
+
*** 在 System Manager 中，选择菜单： Support[ 支持中心 > 诊断选项卡 ] 。然后选择 * 收集支持数据 * 并单击 * 收集 * 。
+
此文件将保存在浏览器的 "Downloads" 文件夹中，名为 `support-data.7z` 。

+
如果磁盘架包含抽盒，则该磁盘架的诊断数据将归档在名为 `try-component-state-capture.7z` 的单独压缩文件中



** 使用 CLI 运行 `save storageArray supportData` 命令，以收集有关存储阵列的全面支持数据。
+

NOTE: 收集支持数据可能会暂时影响存储阵列的性能。



. 在对存储阵列配置所做的更改时，提醒 NetApp 技术支持。
+
.. 获取您在中记录的控制器驱动器托盘的序列号 xref:prepare-upgrade-controllers-task.adoc[准备升级控制器]。
.. 登录到 NetApp 支持站点，网址为 http://mysupport.netapp.com/eservice/assistant["mysupport.netapp.com/eservice/assistant"^]。
.. 从 * 类别 1* 下的下拉列表中选择 * 产品注册 * 。
.. 在 "* 注释 "* 文本框中输入以下文本，并将控制器驱动器托盘的序列号替换为序列号：
+
`请针对序列号创建警报：序列号。警报名称应为 E 系列升级。警报文本应如下所示：`

+
` " 注意：此系统中的控制器已从原始配置升级。在订购更换控制器之前验证控制器配置，并通知派单系统已升级。 "`

.. 单击表单底部的 * 提交 * 按钮。




.下一步是什么？
您的控制器升级已完成、您可以恢复正常操作。
