---
permalink: upgrade-controllers/overview-requirements-concept.html 
sidebar: sidebar 
keywords: E-Series, eseries, E4000, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, upgrade controller requirements, upgrade compatibility, upgrade SAS shelf, upgrade SAS shelves, upgrade SAS enclosures, SAS-2 to SAS-3 
summary: 查看升级和更换 E 系列控制器的要求。 
---
= 升级注意事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
升级控制器之前，请查看以下注意事项。


NOTE: 有关每个E系列控制器支持的配置的具体信息、请参见 https://docs.netapp.com/us-en/e-series/getting-started/learn-hardware-concept.html#e2800-models["E 系列硬件概述"]。



== 硬件和固件要求

* * 双工和单工控制器升级 *
+
对于双工控制器驱动器托盘，您需要更换这两个控制器。对于单工控制器驱动器托盘，您需要更换一个控制器。在这两种情况下，都必须关闭控制器驱动器托盘的电源因此，在成功完成更换之前，您无法访问存储阵列上的数据。

* * 托盘和磁盘架 *
+
使用E系列控制器架的存储阵列通常使用SANtricity System Manager用户界面进行管理。

* * 控制器电池 *
+
新控制器在出厂时未安装电池。如果可能，您应从旧控制器中取出电池，然后将该电池安装到新控制器中。但是，对于某些控制器升级，旧控制器中的电池与新控制器不兼容。在这种情况下，您必须随新控制器一起订购电池，并在开始执行这些任务之前准备好该电池。

* * 同步镜像和异步镜像 *
+
如果存储阵列参与同步镜像，则主站点和远程站点之间仅支持 iSCSI 或光纤通道连接。如果新控制器中的主机接口卡（ HIC ）配置不包括 iSCSI 或光纤通道连接，则不支持同步镜像。

+
对于异步镜像，本地存储阵列和远程存储阵列可以运行不同版本的固件。支持的最低固件版本为 SANtricity 固件版本 7.84 。




NOTE: 对于E4000控制器、只有光纤通道连接才支持镜像。

* * 存储对象限制 *
+
如果将控制器从中端型号更改为入门级型号(例如5x00型号更改为2x00型号)、则新存储阵列配置支持的存储管理软件中的某些存储对象(例如卷)数量将低于旧配置。您必须确保旧配置不超过存储对象限制。

+
有关详细信息、请参见 http://hwu.netapp.com/home.aspx["Hardware Universe"^] 。

* *升级到较新的型号*
+
如果要更换控制器以升级到新型号，请记住，您当前的存储阵列可能安装了新型号无法支持的高级功能。

+
升级E系列控制器时、应禁用存储阵列上使用的新控制器不支持的任何高级功能。





== 升级兼容性

查看每个存储阵列型号支持的升级路径。

[role="tabbed-block"]
====
.E4000控制器升级兼容性
--
[cols="h,d,d,d"]
|===
| 升级路径 | 电池 | 功能支持 | SAS-3 磁盘架 


| 从 E2800 到 E4000  a| 
订购新电池。
 a| 
* E4000不支持ARVM iSCSI
* E4000基板端口仅支持iSCSI、不能更改为FC
* E4000只能支持300个驱动器
* E4000只能支持512个卷
* E4000不支持SAS配置
* E4000不支持远程存储卷

 a| 
E4000控制器必须使用SAS-3磁盘架。



| 从 E5700 到 E4000  a| 
订购新电池。
 a| 
* E4000不支持ARVM iSCSI
* E4000基板端口仅支持iSCSI、不能更改为FC
* E4000只能支持300个驱动器
+
** E5700最多可支持480个驱动器


* E4000只能支持512个卷
+
** E5700最多可支持2048个卷


* InfiniBand主机接口卡支持不可用
* E4000不支持SAS配置

 a| 
E4000控制器必须使用SAS-3磁盘架。

|===
--
.EF600和EF300控制器升级兼容性
--
[cols="h,d,d,d"]
|===
| 升级路径 | 电池 | 功能支持 | SAS-3 磁盘架 


| 使用不同的主机接口卡从EF600到EF600  a| 
重复使用旧电池。
 a| 
* 不支持精简配置卷
* 不支持同步镜像

| EF600控制器必须使用SAS-3磁盘架。 


| 从 EF300 到 EF600  a| 
重复使用旧电池。
 a| 
* 不支持精简配置卷
* 不支持同步镜像

 a| 
EF600控制器必须使用SAS-3磁盘架。

|===
--
.原有控制器升级兼容性
--
[cols="h,d,d,d,d"]
|===
| 升级路径 | 电池 | 供应商ID | 功能支持 | SAS-3 磁盘架 


| 从 E2x00 到 E2x00  a| 
重复使用旧电池。
 a| 
需要执行其他步骤。
 a| 
E2700不支持原有快照。
 a| 
不得将 E2800 控制器置于 SAS-2 磁盘架中。



| 从 E2x00 到 E5x00  a| 
订购新电池。
 a| 
从E2600升级到E5500或E5600或从E2700升级到E5400时、需要执行其他步骤。
 a| 
* E5500 或 E5600 不支持原有快照。
* 使用 iSCSI HIC 的 E5500 或 E5600 不支持原有远程卷镜像（ RVM ）。
* 使用 iSCSI HIC 的 E5500 或 E5600 不支持数据保证。
* 不得将 E5700 控制器置于 SAS-2 磁盘架中。

 a| 
不得将E5400、E5500和E5600控制器置于SAS-3磁盘架中。



| 从 E5x00 到 E2x00  a| 
订购新电池。
 a| 
从E5500或E5600升级到E2600或从E5400升级到E2700时、需要执行其他步骤。
 a| 
E2700不支持原有快照。
 a| 
5400、E5500和E5600控制器不得置于SAS-3磁盘架中。



| 从 E5x00 到 E5x00  a| 
重复使用旧电池。
 a| 
从E5400升级到E5500或E5600时需要执行其他步骤。
 a| 
* E5500 或 E5600 不支持原有快照。
* 使用 iSCSI HIC 的 E5400 或 E5500 不支持原有远程卷镜像（ RVM ）。
* 使用 iSCSI HIC 的 E5400 或 E5500 不支持数据保证。
* 不得将 E5700 控制器置于 SAS-2 磁盘架中。

 a| 
不得将E5400、E5500和E5600控制器置于SAS-3磁盘架中。



| 从 EF5x0 到 EF5x0  a| 
重复使用旧电池。
 a| 
从EF540升级到EF550或EF560所需的其他步骤。
 a| 
* EF550/EF560 没有旧 Snapshot 。
* 对于采用 iSCSI 的 EF550/EF560 ，不提供数据保证。
* 不得将 EF570 控制器置于 SAS-3 磁盘架中。

 a| 
不得将EF540、EF550和EF560控制器置于SAS-3磁盘架中。

|===
--
====


== SAS 机箱

E5700 通过机头升级支持 DE5600 和 DE6600 SAS-2 机箱。如果将 E5700 控制器安装在 SAS-2 机箱中，则会禁用对基本主机端口的支持。

|===
| SAS-2 磁盘架 | SAS-3 磁盘架 


 a| 
SAS-2 磁盘架包括以下型号：

* DE1600 ， DE5600 和 DE6600 驱动器托盘
* E5400 ， E5500 和 E5600 控制器驱动器托盘
* EF540 ， EF550 和 EF560 闪存阵列
* E2600 和 E2700 控制器驱动器托盘

 a| 
SAS-3 磁盘架包括以下型号：

* E4000 控制器架
* EF600控制器架^1^
* EF300控制器架^1^
* E2800 控制器架
* E5700 控制器架
* DE212C ， DE224C ， DE460C 驱动器架


|===
注意：

. EF600和EF300控制器只能使用SAS-3磁盘架进行扩展。




== SAS-2 到 SAS-3 投资保护

您可以重新配置 SAS-2 系统，以便在新的 SAS-3 控制器架（ E57XX/EF570/E28XX ）后面使用。


NOTE: 此操作步骤需要一个功能产品差异请求（ FPVR ）。要提交 FPVR ，请联系您的销售团队。
