---
permalink: upgrade-controllers/overview-requirements-concept.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, upgrade controller requirements, upgrade compatibility, upgrade SAS shelf, upgrade SAS shelves, upgrade SAS enclosures, SAS-2 to SAS-3 
summary: 查看升级和更换 E 系列控制器的要求。 
---
= 升级注意事项
:icons: font
:imagesdir: ../media/


[role="lead"]
升级控制器之前，请查看以下注意事项。



== 硬件和固件要求

* * 双工和单工控制器升级 *
+
对于双工控制器驱动器托盘，您需要更换这两个控制器。对于单工控制器驱动器托盘，您需要更换一个控制器。在这两种情况下，都必须关闭控制器驱动器托盘的电源因此，在成功完成更换之前，您无法访问存储阵列上的数据。

* * 托盘和磁盘架 *
+
使用 E2800 或 E5700 控制器架的存储阵列通常通过 SANtricity System Manager 用户界面进行管理。您也可以使用 SANtricity 存储管理器界面管理 E2800 或 E5700 控制器架。此操作步骤中引用的所有其他控制器驱动器托盘均使用 SANtricity 存储管理器。

* * 控制器电池 *
+
新控制器在出厂时未安装电池。如果可能，您应从旧控制器中取出电池，然后将该电池安装到新控制器中。但是，对于某些控制器升级，旧控制器中的电池与新控制器不兼容。在这种情况下，您必须随新控制器一起订购电池，并在开始执行这些任务之前准备好该电池。

* * 供应商标识 *
+
某些控制器升级会导致 SCSI Inquiry Data 中的 Vendor ID 从 `LSI` 更改为 `NetApp` 。如果供应商 ID 从 `LSI` 更改为 `NetApp` ，则需要在 Windows ， VMware 和 AIX 操作系统上执行其他步骤来回收设备。此升级操作步骤包含这些操作系统的步骤。

* * 同步镜像和异步镜像 *
+
如果存储阵列参与同步镜像，则主站点和远程站点之间仅支持 iSCSI 或光纤通道连接。如果新控制器中的主机接口卡（ HIC ）配置不包括 iSCSI 或光纤通道连接，则不支持同步镜像。

+
对于异步镜像，本地存储阵列和远程存储阵列可以运行不同版本的固件。支持的最低固件版本为 SANtricity 固件版本 7.84 。

* * 存储对象限制 *
+
如果将控制器从 5x00 型号更改为 2x00 型号，则新的存储阵列配置支持的存储管理软件中的某些存储对象（例如卷）数量将低于旧配置。您必须确保旧配置不超过存储对象限制。请参见 http://hwu.netapp.com/home.aspx["Hardware Universe"^] 有关详细信息 ...





== 升级到较新的型号

如果要更换控制器以升级到新型号，请记住，您当前的存储阵列可能安装了新型号无法支持的高级功能。例如， E2700 控制器不支持原有的 Snapshot 高级功能。

如果您将 E2600 控制器更换为 E2700 控制器，并且存储阵列使用的是原有的 Snapshot 功能，则在更换控制器之前，必须禁用此功能并删除或转换与此功能关联的所有卷（即快照，存储库）。您可以将原有快照转换为更新后的快照功能。在升级控制器驱动器托盘之前，您应禁用存储阵列上使用的新控制器不支持的任何高级功能。



== 升级兼容性

[role="lead"]
查看每个存储阵列型号支持的升级路径。



=== 从 E2x00 到 E2x00

* * 电池 * ：重复使用旧电池。
* * 供应商 ID* ：需要执行其他步骤。
* * 功能支持 * ： E2700 不支持原有快照。
* * SAS-2 磁盘架 * ：不得将 E2800 控制器置于 SAS-2 磁盘架中。




=== 从 E2x00 到 E5x00

* * 电池 * ：订购新电池。
* * 供应商 ID* ：从 E2600 升级到 E5500 或 E5600 或从 E2700 升级到 E5400 时，需要执行其他步骤。
* * 功能支持 * ：
+
** E5500 或 E5600 不支持原有快照。
** 使用 iSCSI HIC 的 E5500 或 E5600 不支持原有远程卷镜像（ RVM ）。
** 使用 iSCSI HIC 的 E5500 或 E5600 不支持数据保证。
** 不得将 E5700 控制器置于 SAS-2 磁盘架中。


* * SAS-3 磁盘架 * ：不得将 E5400 ， E5500 和 E5600 控制器置于 SAS-3 磁盘架中。




=== 从 E5x00 到 E2x00

* * 电池 * ：订购新电池。
* * 供应商 ID* ：从 E5500 或 E5600 升级到 E2600 或从 E5400 升级到 E2700 时，需要执行其他步骤。
* * 功能支持 * ： E2700 不支持原有快照。
* * SAS-3 磁盘架 * ：不得将 E5400 ， E5500 和 E5600 控制器置于 SAS-3 磁盘架中。




=== 从 E5x00 到 E5x00

* * 电池 * ：重复使用旧电池。
* * 供应商 ID* ：从 E5400 升级到 E5500 或 E5600 时需要执行的其他步骤。
* * 功能支持 * ：
+
** E5500 或 E5600 不支持原有快照。
** 使用 iSCSI HIC 的 E5400 或 E5500 不支持原有远程卷镜像（ RVM ）。
** 使用 iSCSI HIC 的 E5400 或 E5500 不支持数据保证。
** 不得将 E5700 控制器置于 SAS-2 磁盘架中。


* * SAS-3 磁盘架 * ：不得将 E5400 ， E5500 和 E5600 控制器置于 SAS-3 磁盘架中。




=== 从 EF5x0 到 EF5x0

* * 电池 * ：重复使用旧电池。
* * 供应商 ID* ：从 EF540 升级到 EF550 或 EF560 时需要执行的其他步骤。
* * 功能支持 * ：
+
** EF550/EF560 没有旧 Snapshot 。
** 对于采用 iSCSI 的 EF550/EF560 ，不提供数据保证。
** 不得将 EF570 控制器置于 SAS-3 磁盘架中。


* * SAS-3 磁盘架 * ：不得将 EF540 ， EF550 和 EF560 控制器置于 SAS-3 磁盘架中。




=== SAS 机箱

E5700 通过机头升级支持 DE5600 和 DE6600 SAS-2 机箱。如果将 E5700 控制器安装在 SAS-2 机箱中，则会禁用对基本主机端口的支持。

|===
| SAS-2 磁盘架 | SAS-3 磁盘架 


 a| 
SAS-2 磁盘架包括以下型号：

* DE1600 ， DE5600 和 DE6600 驱动器托盘
* E5400 ， E5500 和 E5600 控制器驱动器托盘
* EF540 ， EF550 和 EF560 闪存阵列
* E2600 和 E2700 控制器驱动器托盘

 a| 
SAS-3 磁盘架包括以下型号：

* E2800 控制器架
* E5700 控制器架
* DE212C ， DE224C ， DE460C 驱动器架


|===


=== SAS-2 到 SAS-3 投资保护

您可以重新配置 SAS-2 系统，以便在新的 SAS-3 控制器架（ E57XX/EF570/E28XX ）后面使用。


NOTE: 此操作步骤需要一个功能产品差异请求（ FPVR ）。要提交 FPVR ，请联系您的销售团队。
