---
permalink: upgrade-controllers/reconfigure-sas-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, reconfigure SAS-2, SAS-2, SAS-3, convert controller shelf, convert drive shelf, 
summary: 您可以将批准的 SAS-2 阵列（ E2700 ， E550/EF5500 ， E5600/EF560 ）中的控制器架转换为驱动器架，然后将该架以及任何关联的批准的 SAS-2 驱动器架（ DE1600 ， DE5600 ， DE6600 ）放置在新批准的 SAS-3 阵列（ E2800 ， E5700/EF570 ）和批准的 SAS-3 驱动器架（ DE224C ， DEC ）后面 不保留数据。 
---
= 在新的 SAS-3 控制器架后面重新配置 SAS-2 系统
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如有必要，您可以重新配置 SAS-2 系统，以便在新的 SAS-3 控制器架后使用。

经批准的 SAS-2 阵列包括 E2700 ， E550/EF5500 和 E5600/EF560 。经批准的 SAS-2 驱动器架包括 DE1600 ， DE5600 和 DE6600 。经批准的 SAS-3 阵列包括 E2800 和 E5700/EF570 。经批准的 SAS-3 驱动器架包括 DE212C ， DE224C 和 DE460C 。

.关于此任务
在此操作步骤中，您可以将批准的 SAS-2 阵列中的控制器架转换为驱动器架，然后将该架放置在新批准的 SAS-3 阵列和驱动器架后面，而无需保留数据。

此 操作步骤 适用场景 IOM12 和 IOM12B 驱动器架。


NOTE: 只有SANtricity OS 11.07.2及更高版本才支持IOM12B模块。在安装或升级到IOM12B之前、请确保已更新控制器的固件。

.开始之前
由于此操作步骤的复杂性，需要满足以下要求：

* 您必须具有功能产品差异请求（ FPVR ）。要提交 FPVR ，请联系 NetApp 专业服务部门。
+

NOTE: 尝试此操作步骤之前未能获取 FPVR 可能会导致驱动器故障和控制器锁定。

* 如果您能够备份数据，则无需 NetApp 专业服务的协助即可执行此操作步骤。
* 如果您无法备份数据，请联系 NetApp 专业服务部门以获得有关此操作步骤的帮助。
* 确保您的两个阵列均已为操作步骤做好准备：
+
** * 现有阵列 * ：已启动 SANtricity OS 8.25 或更高版本的现有阵列。
** * 新阵列 * ：新阵列已解压缩并关闭电源。


* 记下要转换为驱动器架的 SAS-2 控制器架中的序列号。




== 第 1 步：关闭控制器电源（非数据保留）

必须先关闭所有操作，然后才能关闭控制器的电源。

.步骤
. 如果现有的 SAS-2 阵列仍可访问，请删除所有卷组，关闭两个控制器的电源并拔下所有缆线。
. 记下要转换为驱动器架的 SAS-2 控制器架中的序列号。
. 如果现有阵列使用驱动器安全性，请确保安全密钥可用。




== 第 2 步：安装控制器（非数据保留）

成功关闭后，您可以更换阵列中的控制器。

.步骤
. 将现有阵列中的两个控制器更换为 IOM 或 ESM 。
. 如果可能，请使用现有阵列中的主机缆线和网络缆线，并将其连接到新阵列中的控制器。
+

NOTE: 根据新阵列的主机连接，可能需要不同的缆线。

. 为新阵列中控制器后面的驱动器架布线。
+
现有控制器驱动器托盘以及连接的任何驱动器托盘将成为驱动器架，并可通过缆线连接到新阵列中的控制器。

+

NOTE: 要将 SAS-2 连接到 SAS-3 ，需要使用 SAS HD 到迷你 SAS 缆线。有关特定控制器和扩展架配置的详细布线信息，请参见 link:../install-hw-cabling/index.html["Cabling"] 或 https://library.netapp.com/ecm/ecm_download_file/ECMLP2588749["《 E 系列硬件布线指南》"^]。





== 第 3 步：启动控制器（非数据保留）

安装完成后，启动控制器并将您的配置更改提交给 NetApp 技术支持。

.步骤
. 启动新阵列，包括任何已连接的驱动器架。
. 通过安装来配置管理端口和 IP 地址 https://mysupport.netapp.com/tools/info/ECMLP2563821I.html["SANtricity 快速连接"^] 实用程序。
. 如果现有阵列正在使用驱动器安全性，请导入安全密钥。
. 如果在执行此操作步骤之前无法从现有阵列中删除卷组，则必须将所有外部驱动器设置为显示为原生。有关如何将驱动器设置为原生的详细信息，请参阅 SANtricity 联机帮助。
. 将您的配置更改发送给 NetApp 技术支持。
+
.. 获取您在步骤 2 中记录的旧控制器驱动器托盘的序列号。
.. 登录到 http://mysupport.netapp.com/eservice/assistant["NetApp 支持站点"^]。
.. 从 * 反馈类别 * 下的下拉列表中，选择 * 已安装产品 > 取消配置请求 * 。
.. 选择 * 创建案例 * 。在 * 注释 * 文本框中输入以下文本，并将控制器驱动器托盘的序列号替换为序列号：
+
`请停用此序列号，因为授权已移至系统中的另一序列号。请在 SN 备注中引用此内容。`

.. 选择 * 提交 * 。




完成的 SAS-2 到 SAS-3 配置更改将提交给 NetApp 技术支持。
