---
permalink: upgrade-controllers/remount-volumes-lsi-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, remount volume, upgrade LSI, vendor ID 
summary: 如果控制器升级导致将供应商 ID 从 LSI 更改为 NetApp ，则需要重新挂载卷。 
---
= 将供应商从 LSI 更改为 NetApp 后重新挂载卷
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您的控制器升级导致供应商 ID 从 LSI 更改为 NetApp ，请根据您的主机类型遵循相应的操作步骤：

* <<Remount volumes on an AIX host>>
* <<Remount volumes on a VMware host>>
* <<Remount volumes on a Windows host>>




== 在 AIX 主机上重新挂载卷

更换控制器后，您可能会发现主机显示存储阵列上的新卷，但也会显示原始卷出现故障。

如果出现故障卷，请运行 `cfgmgr` 命令。



== 在 VMware 主机上重新挂载卷

更换控制器后，可能会出现以下情况：

* VMware 会显示存储阵列上卷的新路径，但也会将原始路径显示为无路径。
* 这些主机仍会将存储阵列上的卷列为具有 LSI 供应商 ID 。如果卷在开始时由 LSI 规则声明，则可能会发生这种情况，因此在卷恢复联机后，继续使用相同的 LSI 规则。
* 显示名称不会反映从 LSI 到 NetApp 的变化。之所以出现这种情况，可能是因为在首次发现后显示名称变为空闲测试。在这种情况下，您可以手动更改显示名称。


.步骤
. 对每个主机执行重新扫描。
. 暂停对该子系统执行的所有主机 I/O 操作。
. 根据 NetApp 规则回收卷。
+
.. 运行 `esxcli storage core device list` 命令。检查命令的输出以确定名称格式为 `aa.xxxx` 的卷。
.. 运行命令 `do esxcli storage core saiming reclaiming -d naa.xxxxx` 将 LSI 供应商 ID 更改为 NetApp 。






== 在 Windows 主机上重新挂载卷

更换控制器后，您必须在 Windows 主机上重新挂载卷，以使连接的主机能够对升级后的存储阵列上的卷执行 I/O 操作。

.步骤
. 在 * 设备管理器 * 中，选择 * 显示隐藏设备 * 。
. 对于 * 设备管理器 * 中列出的每个 NetApp SCSI 磁盘设备，右键单击该条目，然后选择 * 卸载 * 。
+
如果 Windows 显示一个对话框，其中包含一条消息，指示您应重新启动主机，请在扫描硬件并重新启动之前完成卸载所有卷。

. 右键单击 * 设备管理器 * ，然后选择 * 扫描硬件更改 * 。
. 重新启动主机。

