---
permalink: upgrade-controllers/upgrade-unlock-drives-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, unlock drives, key management, Drive Security, 
summary: 如果要升级 E2800 和 E5700 控制器且已启用驱动器安全功能，则必须手动解锁驱动器。 
---
= 解锁驱动器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
这些控制器的驱动器安全功能将部分、外部或内部锁定驱动器。如果启用了驱动器安全功能，则必须手动解锁这些驱动器。

按照相应的操作步骤执行以下操作：

* <<内部密钥管理>>
* <<外部密钥管理>>




== 内部密钥管理

当所有驱动器均已锁定时，请按照以下步骤进行内部密钥管理。

.关于此任务
新交换的控制器将锁定、并显示七段代码*。L5*。如果没有驱动器可以执行自动模式同步(ACS)、则会发生此锁定。导入安全密钥后、ACS将恢复并更新新控制器。


NOTE: 如果您不使用管理端口 1 ，请尝试使用其他默认 IP 地址： + Ctrl A port 1 ： 169.254.128.101 + Ctrl A port 2 ： 169.254.128.102 + Ctrl B port 1 ： 169.254.128.101 + Ctrl B port 2 ： 169.254.128.102

.步骤
. 在存储阵列与SANtricity 客户端的笔记本电脑或PC之间建立直接的专用以太网连接。为此、请执行以下操作：
+
.. 使用RJ45以太网缆线将笔记本电脑连接到控制器A上的管理端口1
.. 要完成连接、您可能需要将笔记本电脑分配给与控制器A位于同一子网中的IP地址。在控制器被关闭期间、控制器A的默认管理地址为169.254.128.101。因此、您可以将笔记本电脑分配给子网、例如"169.254.128.201"。


. 使用IP地址169.254.128.101且用户名*admin*和密码为空，使用CLI命令导入内部密钥 `import storageArray securityKey file`，并将安全密钥保存在中link:prepare-upgrade-controllers-task.html["准备升级控制器"]。有关使用此命令的信息，请参见 https://docs.netapp.com/us-en/e-series-cli/index.html["命令行界面参考"]。
+
*示例:* `SMcli 169.254.128.101 -k -u admin -p "" -c "import storageArray securityKey file=\"Directory&FileName\" passPhrase=\"passPhraseString\";"`

+
或者、您也可以通过以下调用通过REST API导入内部密钥： `/storage-systems/{system-id}/security-key/import`



控制器将继续从驱动器执行自动节点同步过程，然后重新启动。重新启动后，可以通过原始 IP 配置访问控制器。



== 外部密钥管理

当所有驱动器均已锁定时，请按照以下步骤进行外部密钥管理。

.关于此任务
新交换的控制器将锁定、并显示七段代码*。L5*。如果没有驱动器可以执行自动模式同步(ACS)、则会发生此锁定。导入安全密钥后、ACS将恢复并更新新控制器。

.步骤
. 在存储阵列与SANtricity 客户端的笔记本电脑或PC之间建立直接的专用以太网连接。为此、请执行以下操作：
+
.. 使用RJ45以太网缆线将笔记本电脑连接到控制器A上的管理端口1
.. 要完成连接、您可能需要将笔记本电脑分配给与控制器A位于同一子网中的IP地址。在控制器被关闭期间、控制器A的默认管理地址为169.254.128.101。因此、您可以将笔记本电脑分配给子网、例如"169.254.128.201"。


. 使用保存在中的安全密钥link:prepare-upgrade-controllers-task.html["准备升级控制器"]，将外部密钥导入到IP地址169.254.128.101，用户名*admin*和密码留空。
+
*示例:* `SMcli 169.254.128.101 -k -u admin -p "" -c "import storageArray securityKey file=\"Directory&FileName\" passPhrase=\"passPhraseString\";"`

+
或者、您也可以通过以下调用通过REST API导入外部密钥： `/storage-systems/{system-id}/security-key/import`

+
控制器将继续从驱动器执行自动节点同步过程，然后重新启动。重新启动后，可以通过原始 IP 配置访问控制器。

. (可选)如果需要、可以通过执行以下操作来重新设置驱动器的密钥：
+
*示例:* `SMcli <original_controller _ip> -u admin -p "<original_array_password>" -c "create storageArray securityKey" passPhrase=\"passPhraseString\" file=\"filename\";”`


