---
permalink: remote-storage-volumes/import-remote-storage-task.html 
sidebar: sidebar 
keywords: import Remote Storage Volumes, RTV import, import remote volumes, remote storage E-Series 
summary: 远程存储设备的导入可通过 SANtricity 系统管理器下的导入远程存储向导执行。通过远程存储导入功能，可以将远程存储设备中的数据移动到本地 E 系列阵列。 
---
= 导入远程存储
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要启动从远程系统到本地 E 系列存储系统的存储导入，请使用 SANtricity 系统管理器用户界面中的导入远程存储向导。

.您需要什么？ #8217 ；将需要什么
* 必须将 E 系列存储系统配置为与远程存储系统进行通信。请参见 link:setup-remote-volumes-concept.html["配置硬件"]。
* 对于远程存储系统，请收集以下信息：
+
** iSCSI IQN
** iSCSI IP 地址
** 远程存储设备（源卷）的 LUN 编号


* 对于本地 E 系列存储系统，请创建或选择要用于数据导入的卷。目标卷必须满足以下要求：
+
** 与远程存储设备（源卷）的块大小匹配。
** 容量等于或大于远程存储设备。
** 状态为最佳且可用。有关完整的要求列表，请参见 link:system-reqs-concept.html["要求和限制"]。


* 建议：在开始导入过程之前，备份远程存储系统上的卷。


在此任务中，您将在远程存储设备与本地 E 系列存储系统上的卷之间创建映射。完成配置后，导入将开始。


NOTE: 由于许多变量可能会影响导入操作及其完成时间，因此应先执行较小的 " 测试 " 导入。使用这些测试可确保所有连接均按预期工作，并且导入操作会在适当的时间内完成。

.步骤
. 在 SANtricity 系统管理器中，单击 * 存储 > 远程存储 * 。
. 单击 * 导入远程存储 * 。
+
此时将显示一个用于导入远程存储的向导。

. 在配置源面板的步骤 1a 中，输入连接信息。
+
.. 在 * 名称 * 字段下，输入远程存储设备的名称。
.. 在 * iSCSI 连接属性 * 下，为远程存储设备输入以下内容： IQN ， IP 地址和端口号（默认值为 3260 ）。
+
如果要添加另一个 iSCSI 连接，请单击 * + 添加另一个 IP 地址 * 以添加远程存储的其他 IP 地址。完成后，单击 * 下一步 * 。

+
单击下一步后，将显示配置源面板的步骤 1b 。



. 在 * LUN * 字段下，为远程存储设备选择所需的源 LUN ，然后单击 * 下一步 * 。
+
此时将打开配置目标面板，并显示要用作导入目标的卷候选对象。由于块大小，容量或卷可用性，某些卷不会显示在候选卷列表中。

. 从表中，选择 E 系列存储系统上的目标卷。如果需要，请使用滑块更改导入优先级。单击 * 下一步 * 。在下一个对话框中键入 `continue` ，然后单击 * 继续 * ，确认操作。
+
如果目标卷的容量大于源卷，则不会向连接到 E 系列系统的主机报告此额外容量。要使用新容量，必须在导入操作完成并断开连接后在主机上执行文件系统扩展操作。

+
在对话框中确认配置后，将显示 Review 面板。

. 在 Review 屏幕中，验证指定的远程存储设备，目标和导入设置是否准确。单击 * 完成 * 以完成远程存储的创建。
+
此时将打开另一个对话框，询问您是否要启动另一个导入。

. 如果需要，请单击 * 是 * 以创建另一个远程存储导入。单击是返回到配置源面板的步骤 1a ，您可以在其中选择现有配置或添加新配置。如果不想创建另一个导入，请单击 * 否 * 退出对话框。
+
导入过程开始后，整个目标卷将被复制的数据覆盖。如果在此过程中主机向目标卷写入任何新数据，则新数据将传播回远程设备（源卷）。

. 在远程存储面板下的查看操作对话框中查看操作进度。
+
完成导入操作所需的时间取决于远程存储系统的大小，导入的优先级设置以及两个存储系统及其关联卷上的 I/O 负载量。导入完成后，本地卷将与远程存储设备重复。

. 准备好中断两个卷之间的关系后，从操作进行中视图中选择导入对象上的 * 断开连接 * 。断开关系后，本地卷的性能将恢复正常，不再受远程连接的影响。

