---
permalink: remote-storage-volumes/system-reqs-concept.html 
sidebar: sidebar 
keywords: Remote Storage Volumes requirements, RTV requirements, RTV restrictions, remote volumes, remote storage E-Series 
summary: 您的系统必须满足远程存储卷的兼容性要求。 
---
= 远程存储的要求和限制
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在配置远程存储卷功能之前，请查看以下要求和限制。



== 硬件要求



=== 支持的协议

对于初始版本的远程存储卷功能，仅支持 iSCSI 和 IPv4 协议。

请参见 http://mysupport.netapp.com/matrix["NetApp 互操作性表工具"^] 有关主机与用于远程存储卷功能的 E 系列（目标）阵列之间的最新支持和配置信息。



=== 存储系统要求

E 系列存储系统必须包括：

* 两个控制器（双工模式）
* 两个 E 系列控制器的 iSCSI 连接，用于通过一个或多个 iSCSI 连接与远程存储系统进行通信
* SANtricity OS 11.71 或更高版本
* 在子型号 ID （ SMID ）中启用远程存储功能


远程系统可以是 E 系列存储系统，也可以是其他供应商提供的系统。它必须包含支持 iSCSI 的接口。



== 卷要求：

用于导入的卷必须满足大小，状态和其他条件的要求。



=== 远程存储卷

导入的源卷称为 " 远程存储卷 " 。 此卷必须满足以下条件：

* 不能属于其他导入
* 必须处于联机状态


导入开始后，控制器固件将在后台创建远程存储卷。由于此后台进程，远程存储卷在 System Manager 中无法管理，只能用于导入操作。

创建远程存储卷后，该卷将与 E 系列系统上的任何其他标准卷一样进行处理，但以下情况除外：

* 可用作远程存储设备的代理。
* 不能用作其他卷副本或快照的候选项。
* 无法在导入过程中更改数据保证设置。
* 无法映射到任何主机，因为这些主机是严格为导入操作预留的。


每个远程存储卷仅与一个远程存储对象关联；但是，一个远程存储对象可以与多个远程存储卷关联。远程存储卷通过以下方式的组合进行唯一标识：

* 远程存储对象标识符
* 远程存储设备 LUN 编号




=== 目标卷候选项

目标卷是本地 E 系列系统上的目标卷。

目标卷必须满足以下条件：

* 必须是 RAID/DDP 卷。
* 容量必须等于或大于远程存储卷。
* 块大小必须与远程存储卷相同。
* 必须具有有效状态（最佳）。
* 不能具有以下任何关系：卷副本， Snapshot 副本，异步或同步镜像。
* 不能进行任何重新配置操作：动态卷扩展，动态容量扩展，动态区块大小，动态 RAID 迁移，动态容量缩减， 或碎片整理。
* 导入开始前无法映射到主机（但是，导入完成后可以映射）。
* 无法启用 Flash Read Cached （ FRC ）。


System Manager 会在导入远程存储向导中自动检查这些要求。在选择目标卷时，仅会显示满足所有要求的卷。



== 限制

远程存储功能具有以下限制：

* 必须禁用镜像。
* E 系列系统上的目标卷不能具有快照。
* 在启动导入之前，不得将 E 系列系统上的目标卷映射到任何主机。
* E 系列系统上的目标卷必须已禁用资源配置。
* 不支持将远程存储卷直接映射到一个或多个主机。
* 不支持 Web 服务代理。
* 不支持 iSCSI CHAP 密码。
* 不支持 SMcli 。
* 不支持 VMware 数据存储库。
* 如果存在导入对，则一次只能升级关系 / 导入对中的一个存储系统。




== 准备生产导入

您应在生产导入之前执行测试或 " 试运行 " 导入，以验证存储和网络结构配置是否正确。

许多变量可能会影响导入操作和完成时间。为了确保生产导入成功并获得持续时间估计值，您可以使用这些测试导入来确保所有连接均按预期工作，并且导入操作在适当的时间内完成。然后，您可以在启动生产导入之前进行调整，以获得所需的结果。
