---
permalink: install-hw-ef50-ef80/install-prepare.html 
sidebar: sidebar 
keywords:  
summary: 准备安装 EF50 或 EF80 存储系统时，请准备好站点，了解存储系统的吊装注意事项，打开包装箱，将内容与装箱单进行比较，并注册存储系统以获得支持优势。 
---
= 准备安装 - EF50 和 EF80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
准备安装 EF50 或 EF80 存储系统时，请准备好站点，了解存储系统的吊装注意事项，打开包装箱，将内容与装箱单进行比较，并注册存储系统以获得支持优势。



== 步骤 1：准备站点

确保计划使用的站点和机柜或机架符合您的存储系统的规格。

.步骤
. 使用  https://hwu.netapp.com["NetApp Hardware Universe"^] 确认您的站点是否满足存储系统的环境和电气要求。
. 请确保您的存储系统和任何交换机有足够的机柜或机架空间。
+
如果需要，请参阅  https://hwu.netapp.com["NetApp Hardware Universe"^] 以了解存储系统的确切尺寸。

+
** 2U 用于存储系统
** 1U 适用于大多数交换机


. 安装任何所需的网络交换机。
. 确保您拥有管理软件支持的浏览器：
+
** Google Chrome (89及更高版本)
** Microsoft Edge (90及更高版本)
** Mozilla Firefox (80及更高版本)
** Safari (版本14及更高版本)


. 获取安装所需的以下设备和工具：
+
** 静电放电 (ESD) 腕带
** Philips #2 螺丝刀
** Flashlight






== 步骤 2：了解起重注意事项

在拆箱之前以及以后安装存储系统时，应了解存储系统的重量，以便在提起和移动存储系统时采取必要的预防措施。

EF50 或 EF80 存储系统的重量可达 61.5 磅（27.9 千克）。要提升存储系统，请使用两人或液压提升机。

image::../media/drw_g_lifting_weight_ieops-1831.svg[AFF A20 A30 A50 和 C30 和 C60 重量警告图标]



== 步骤 3：拆箱

在确保您计划使用的场地和机柜或机架符合存储系统的规格，并且您了解提升预防措施后，打开所有箱子并将内容与装箱单上的项目进行比较。

.步骤
. 仔细打开所有盒子，并有条不紊地布置内容物。
. 将您打开的内容与装箱单进行比较。
+
您可以通过扫描装运箱侧面的二维码获取装箱单。

+

NOTE: 如果有任何差异，请将其记录下来，以便采取进一步行动。

+
以下项目是您可能会在框中看到的一些内容。

+
如果需要，请参见 https://hwu.netapp.com/["NetApp Hardware Universe"^]以了解其他支持的电缆并确定其用途。

+
[cols="9,9,5"]
|===


| *硬件* | *电缆* |  


 a| 
** 带驱动器的存储系统
** 交换机
** 带有说明的机架安装硬件
** 挡板

 a| 
** 控制器间镜像 Ethernet 缆线
** 管理以太网缆线（RJ-45 缆线）
** 网络电缆
** Power cables

|  
|===




== 步骤 4：注册您的存储系统

在确保您的站点符合您的存储系统规格，并且您已验证您拥有所订购的所有部件后，您应注册您的存储系统。

. 在中创建帐户并注册硬件 http://mysupport.netapp.com/["NetApp 支持"^]。
+
注册过程需要每个控制器的序列号 (SN)。您可以在以下位置找到序列号：

+
** 在每个控制器上
** 在装箱单上
** 在您的确认电子邮件中
+
image::../media/drw_ef50-ef80_sn_label_ieops-2689.svg[序列号标签示例]





.下一步是什么？
准备安装存储系统后，link:install-hardware.html["安装硬件"]。
