---
permalink: upgrade-santricity/overview-upgrade-consider-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, SANtricity, drive firmware, upgrade SANtricity, upgrade OS, upgrade E-Series, upgrade firmware, upgrading, upgrade IOM firmware, upgrade NVSRAM, upgrade controller 
summary: 查看存储阵列的 SANtricity 操作系统控制器软件和固件及其驱动器固件的升级注意事项。 
---
= 升级注意事项
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要确保升级成功，请查看以下升级注意事项。



== 控制器升级（单个或多个）

升级控制器之前，请查看这些主要注意事项。



=== 当前版本

您可以按如下所示查看软件和固件的当前版本：

* 对于单个控制器，请使用 SANtricity 系统管理器界面。转到菜单： Support[ 升级中心 ] ，然后单击 * 软件和固件清单 * 链接。
* 对于多个控制器，请使用 SANtricity 统一管理器界面。转到 * 管理 * 页面以查看已发现的存储阵列。这些版本显示在 * SANtricity OS Software* 列中。单击每行中的 SANtricity OS 版本时，会在弹出对话框中显示控制器固件和 NVSRAM 信息。




=== 升级中包含的组件

SANtricity 操作系统升级过程包括以下组件：

* * 系统管理器 * — System Manager 是用于管理存储阵列的软件。
* * 控制器固件 * —控制器固件用于管理主机和卷之间的 I/O 。
* * IOM 固件 * — I/O 模块（ IOM ）固件用于管理控制器与驱动器架之间的连接。它还会监控组件的状态。
* * 监控软件 * —监控软件是运行该软件的控制器上的虚拟机。




=== 要单独升级的组件

以下组件必须单独升级：

* * 控制器 NVSRA* - 控制器 NVSRAM 是一个控制器文件，用于指定控制器的默认设置。有关升级 NVSRAM 的说明随控制器的升级说明一起提供。
* * 驱动器固件 * —请参见 link:upgrade-drive-firmware-task.html["升级驱动器固件"] 以获取单独的说明。
* * 多路径 / 故障转移驱动程序 * —在升级过程中，可能还需要升级主机的多路径 / 故障转移驱动程序，以便主机可以与控制器正确交互。如果运行 Microsoft Windows 以外的操作系统的主机与存储系统具有 I/O 连接，请升级这些主机的多路径驱动程序。有关兼容性信息，请参见 https://mysupport.netapp.com/NOW/products/interoperability["NetApp 互操作性表"^]。有关升级说明，请参见 link:../config-linux/index.html["Linux 快速配置"]， 或 。
* * SANtricity 统一管理器 * — Unified Manager 软件用于管理多个存储系统，包括 E2800 ， E5700 ， EF300 和 EF600 型号。Unified Manager 是 SANtricity Web 服务代理的一部分，该代理是单独安装在主机系统上的 RESTful API 服务器，用于管理数百个新旧的 NetApp E 系列存储系统。有关详细信息，请参见 link:../web-services-proxy/index.html["SANtricity Web 服务代理概述"]。
* * 实用程序 * —其他管理实用程序需要单独升级，例如 SANtricity Windows 主机实用程序， SANtricity Linux 主机实用程序和 SANtricity Windows DSM 。有关这些实用程序的详细信息，请参见 link:../config-linux/index.html["Linux 快速配置"]， 或 。
* * 旧版系统 * —如果存储系统属于包含旧版存储系统的存储网络，则可能需要使用旧版 SANtricity Storage Manager 企业管理窗口（ EMW ）提供所有存储系统的企业级视图。在这种情况下，请检查是否存在较新的 SANtricity 存储管理器维护版本。




=== 双控制器和 I/O 处理

如果存储阵列包含两个控制器，并且您安装了多路径驱动程序，则在升级期间，存储阵列可以继续处理 I/O 。在升级期间，将执行以下过程：

. 控制器 A 将其所有 LUN 故障转移到控制器 B
. 升级在控制器 A 上进行
. 控制器 A 将收回其 LUN 以及控制器 B 的所有 LUN 。
. 升级在控制器 B 上进行


升级完成后，您可能需要在控制器之间手动重新分布卷，以确保卷返回到正确的所属控制器。



=== 运行状况检查

在升级过程中运行状况检查。此运行状况检查会评估所有存储阵列组件，以确保升级可以继续进行。以下情况可能会阻止升级：

* 已分配的驱动器出现故障
* 正在使用热备件
* 卷组不完整
* 正在运行排他操作
* 缺少卷
* 控制器处于非最佳状态
* 事件日志事件数量过多
* 配置数据库验证失败
* 使用旧版 DAC 存储的驱动器


您也可以单独运行升级前运行状况检查，而无需执行升级。



=== 立即或分阶段升级

您可以立即激活升级，也可以稍后暂存升级。您可以选择稍后激活，原因如下：

* * 当前时间 * —激活软件可能需要很长时间，因此您可能需要等待 I/O 负载变轻。根据 I/O 负载和缓存大小，完成控制器升级通常需要 15 到 25 分钟。控制器会在激活期间重新启动并进行故障转移，因此在升级完成之前性能可能会比平常低。
* * 软件包类型 * —您可能需要先在一个存储阵列上测试新软件和固件，然后再升级其他存储阵列上的文件。




== 驱动器固件升级

在升级驱动器固件之前，请查看以下主要注意事项。



=== 驱动器兼容性

每个驱动器固件文件都包含有关运行固件的驱动器类型的信息。您只能将指定的固件文件下载到兼容驱动器。System Manager 会在升级过程中自动检查兼容性。



=== 驱动器升级方法

驱动器固件升级方法有两种：联机和脱机。

|===
| 联机升级 | 脱机升级 


 a| 
在联机升级期间，驱动器会按顺序升级，一次升级一个。升级期间，存储阵列将继续处理 I/O 。您不必停止 I/O如果驱动器可以执行联机升级，则会自动使用联机方法。

可以执行联机升级的驱动器包括：

* 最佳池中的驱动器
* 最佳冗余卷组（ RAID 1 ， RAID 5 和 RAID 6 ）中的驱动器
* 未分配的驱动器
* 备用热备用驱动器


执行联机驱动器固件升级可能需要几个小时，从而使存储阵列面临潜在的卷故障。在以下情况下，可能会发生卷故障：

* 在 RAID 1 或 RAID 5 卷组中，在升级卷组中的另一个驱动器时，一个驱动器发生故障。
* 在 RAID 6 池或卷组中，升级池或卷组中的另一个驱动器时，两个驱动器发生故障。

 a| 
在脱机升级期间，同一驱动器类型的所有驱动器都会同时升级。此方法需要停止与选定驱动器关联的卷的 I/O 活动。由于多个驱动器可以同时（并行）升级，因此整体停机时间会显著减少。如果驱动器只能执行脱机升级，则会自动使用脱机方法。

以下驱动器必须使用脱机方法：

* 非冗余卷组中的驱动器（ RAID 0 ）
* 非最佳池或卷组中的驱动器
* SSD 缓存中的驱动器


|===