---
permalink: upgrade-santricity/upgrade-single-controller-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, SANtricity, upgrade SANtricity, upgrade OS, upgrade E-Series, upgrade firmware, upgrading, upgrade IOM firmware, upgrade NVSRAM, upgrade controller 
summary: 升级单个 E 系列控制器的软件和固件。 
---
= 升级单个控制器的软件和固件
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以升级单个控制器，以确保您拥有所有最新的功能和修复程序。

此过程涉及升级存储阵列的软件以及可选的 IOM 固件和非易失性静态随机存取存储器（ NVSRAM ）。

.开始之前
* 请查看 link:overview-upgrade-consider-task.html["升级注意事项"]。
* 确定是否要在升级操作系统固件的同时升级控制器 NVSRAM 文件。
+
通常，您应同时升级所有组件。但是，如果您的文件已修补或为自定义版本，并且您不想覆盖此文件，则您可能会决定不升级控制器 NVSRAM 文件。

* 确定是否要升级 IOM 固件。
+
通常，您应同时升级所有组件。但是，如果您不希望在 SANtricity OS 软件升级过程中升级 IOM 固件，或者技术支持已指示您降级 IOM 固件（您只能使用命令行界面降级固件），则可能决定不升级 IOM 固件。

* 确定是要立即激活操作系统升级还是稍后激活。
+
稍后激活的原因可能包括：

+
** * 时间 * —激活软件和固件可能需要很长时间，因此您可能需要等待 I/O 负载减轻。控制器会在激活期间进行故障转移，因此在升级完成之前性能可能会比平常低。
** * 软件包类型 * —您可能希望先在一个存储阵列上测试新软件和固件，然后再升级其他存储阵列上的文件。






== 第 1 步：从支持站点下载软件文件

在此步骤中，您将转到 NetApp 支持站点将新的可下载软件包（ DLP ）软件文件保存到管理主机系统中。

升级所需的时间取决于您的存储阵列配置以及要升级的组件。

.步骤
. 如果存储阵列仅包含一个控制器或您未安装多路径驱动程序，请停止存储阵列的 I/O 活动，以防止出现应用程序错误。如果存储阵列有两个控制器，并且您安装了多路径驱动程序，则无需停止 I/O 活动。
+

CAUTION: 如果要在 StorageGRID 设备（例如 SG5612 或 SG5760 ）上升级 SANtricity OS ，则需要先将设备置于维护模式以停止 I/O 活动，然后再继续使用此操作步骤，否则可能会丢失数据。有关详细步骤，请参见 StorageGRID 设备的安装和维护说明。

. 从 System Manager 界面中，选择菜单： Support[Upgrade Center] 。
. 在标记为 "NetApp OS 软件升级 " 的区域中，单击 * SANtricity SANtricity OS Downloads* 以打开 NetApp 支持站点。
. 从 "Downloads" 页面中，选择 * E 系列 SANtricity 操作系统控制器软件 * 。
+

NOTE: 8.42 及更高版本需要使用数字签名固件。如果您尝试下载未签名的固件，则会显示一个错误，并中止下载。

. 按照屏幕上的说明下载适用于您的控制器型号的最新操作系统软件。如果您还想升级 NVSRAM ，请下载单个控制器的 NVSRAM 文件。




== 第 2 步：将软件文件传输到控制器

在此步骤中，您可以将软件文件传输到控制器，以便开始升级过程。这些组件会从管理客户端复制到控制器，并放置在闪存中的暂存区域。


CAUTION: * 数据丢失或存储阵列损坏的风险 * —升级期间请勿更改存储阵列。为存储阵列供电。

.步骤
. （可选）。如果您计划在特定维护时段执行升级，则可能需要事先运行升级前运行状况检查以确定是否存在任何重大存储阵列问题。如果出现这种情况，请从 System Manager 的升级中心（菜单： Support[Upgrade Center] ）中选择 * 升级前运行状况检查 * ，然后按照屏幕上的说明进行操作。否则，您可以跳过此步骤，因为运行状况检查是升级过程的一部分。
. 如果此时不想升级 IOM 固件，请单击 * 暂停 IOM 自动同步 * 并按照对话框中的说明进行操作。
+
如果存储阵列具有一个控制器，则不会升级 IOM 固件。

. 在 System Manager 的升级中心中，单击 * 从 SANtricity OS 软件升级开始升级 * 。
+
此时将显示升级 SANtricity OS 软件对话框。

. 选择一个或多个文件以开始升级过程：
+
.. 单击 * 浏览 * 并导航到从支持站点下载的操作系统软件文件，选择 SANtricity 操作系统软件文件。
.. 单击 * 浏览 * 并导航到从支持站点下载的 NVSRAM 文件，以选择控制器 NVSRAM 文件。控制器 NVSRAM 文件的文件名类似于 `N2800-830000-000.DLP` 。


+
执行以下操作：

+
** 默认情况下，仅显示与当前存储阵列配置兼容的文件。
** 选择要升级的文件时，将显示该文件的名称和大小。


. （可选）如果您选择了要升级的 SANtricity 操作系统软件文件，则可以通过选中 * 立即传输文件，但不升级（稍后激活升级） * 复选框将文件传输到控制器而不激活这些文件。
. 单击 * 开始 * ，然后确认您要执行此操作。
+
您可以在升级前运行状况检查期间取消此操作，但不能在传输或激活期间取消此操作。

. （可选）要查看已升级内容的列表，请单击 * 保存日志 * 。
+
此文件将保存在浏览器的 "Downloads" 文件夹中，名称为 `drive_upgrade_log-timestamp.txt` 。



如果您已激活软件文件，请转至 <<Step 4: Complete software and firmware upgrade>>；否则，请转到 <<Step 3: Activate software files>>。



== 第 3 步：激活软件文件

只有当您的软件或固件已传输但未激活时，才执行此步骤。要检查此状态，请在 System Manager 主页页面的通知区域或升级中心页面中查找通知。

执行激活操作时，当前软件和固件将替换为新的软件和固件。激活过程启动后，您无法停止它。

.步骤
. 从 System Manager 界面中，选择菜单： Support[Upgrade Center] 。
. 在标有 SANtricity OS 软件升级的区域中，单击 * 激活 * ，然后确认您要执行此操作。
. （可选）要查看已升级内容的列表，请单击 * 保存日志 * 。
+
此文件将保存在浏览器的 "Downloads" 文件夹中，名称为 `drive_upgrade_log-timestamp.txt` 。





== 第 4 步：完成软件和固件升级

通过在软件和固件清单对话框中验证版本来完成软件和固件升级。

.开始之前
* 您必须已激活软件或固件。


.步骤
. 在 System Manager 中，验证所有组件是否均显示在硬件页面上。
. 选中软件和固件清单对话框以验证新的软件和固件版本（转到菜单：支持 [ 升级中心 ] ，然后单击 * 软件和固件清单 * 链接）。
. 如果您升级了控制器 NVSRAM ，则在激活过程中，应用于现有 NVSRAM 的任何自定义设置都将丢失。激活过程完成后，您需要再次将自定义设置应用于 NVSRAM 。
. 如果在升级操作步骤期间出现以下任何错误，请采取适当的建议操作。
+
|===
| 如果遇到此固件下载错误 ... | 然后执行以下操作 ... 


 a| 
已分配的驱动器出现故障
 a| 
出现此故障的一个原因可能是驱动器没有相应的签名。确保受影响的驱动器为授权驱动器。有关详细信息，请联系技术支持。

更换驱动器时，请确保更换驱动器的容量等于或大于要更换的故障驱动器。

您可以在存储阵列接收 I/O 时更换故障驱动器



 a| 
检查存储阵列
 a| 
** 确保已为每个控制器分配 IP 地址。
** 确保连接到控制器的所有缆线均未损坏。
** 确保所有缆线均已紧密连接。




 a| 
集成热备用驱动器
 a| 
必须先更正此错误情况，然后才能升级固件。启动 System Manager 并使用 Recovery Guru 解决此问题。



 a| 
卷组不完整
 a| 
如果一个或多个卷组或磁盘池不完整，则必须更正此错误情况，然后才能升级固件。启动 System Manager 并使用 Recovery Guru 解决此问题。



 a| 
当前在任何卷组上运行的独占操作（后台介质 / 奇偶校验扫描除外）
 a| 
如果正在执行一个或多个独占操作，则必须先完成这些操作，然后才能升级固件。使用 System Manager 监控操作进度。



 a| 
缺少卷
 a| 
您必须先更正缺少的卷情况，然后才能升级固件。启动 System Manager 并使用 Recovery Guru 解决此问题。



 a| 
任一控制器处于非最佳状态
 a| 
其中一个存储阵列控制器需要注意。必须先更正此情况，然后才能升级固件。启动 System Manager 并使用 Recovery Guru 解决此问题。



 a| 
控制器对象图形之间的存储分区信息不匹配
 a| 
验证控制器上的数据时出错。请联系技术支持以解决此问题描述。



 a| 
SPM 验证数据库控制器检查失败
 a| 
控制器上发生存储分区映射数据库错误。请联系技术支持以解决此问题描述。



 a| 
配置数据库验证（如果存储阵列的控制器版本支持）
 a| 
控制器上发生配置数据库错误。请联系技术支持以解决此问题描述。



 a| 
与 Mel 相关的检查
 a| 
请联系技术支持以解决此问题描述。



 a| 
过去 7 天报告了 10 个以上的 DDN 信息性或严重 MEL 事件
 a| 
请联系技术支持以解决此问题描述。



 a| 
过去 7 天报告了超过 2 页 2C 的严重 MEL 事件
 a| 
请联系技术支持以解决此问题描述。



 a| 
过去 7 天报告了 2 个以上的 " 降级驱动器通道 " 严重 MEL 事件
 a| 
请联系技术支持以解决此问题描述。



 a| 
过去 7 天内超过 4 个关键 MEL 条目
 a| 
请联系技术支持以解决此问题描述。

|===


控制器软件升级已完成。您可以恢复正常操作。
