---
permalink: upgrade-santricity/upgrade-multiple-controller-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, SANtricity, drive firmware, upgrade SANtricity, upgrade OS, upgrade E-Series, upgrade firmware, upgrading, upgrade IOM firmware, upgrade NVSRAM, upgrade controller 
summary: 使用 SANtricity 统一管理器在多个相同类型的存储阵列上升级 SANtricity OS 软件。 
---
= 升级多个控制器的软件和固件
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 SANtricity Unified Manager 升级多个相同类型的控制器。

.开始之前
* 请查看 link:overview-upgrade-consider-task.html["升级注意事项"]。
* 确定您是要立即激活软件升级还是稍后激活软件升级。您可以选择稍后激活，原因如下：
+
** * 当前时间 * —激活软件可能需要很长时间，因此您可能需要等待 I/O 负载变轻。控制器会在激活期间进行故障转移，因此，在升级完成之前，性能可能会比平常低。
** * 软件包类型 * —您可能需要先在一个存储阵列上测试新的操作系统软件，然后再升级其他存储阵列上的文件。


* 请查看以下预防措施：



CAUTION: 数据丢失风险或存储阵列损坏风险—升级期间，请勿更改存储阵列。为存储阵列供电。


CAUTION: 如果要在 StorageGRID 设备（例如 SG5612 或 SG5760 ）上升级 SANtricity OS ，则需要先将设备置于维护模式以停止 I/O 活动，然后再继续使用此操作步骤，否则可能会丢失数据。有关详细步骤，请参见 StorageGRID 设备的安装和维护说明。



== 第 1 步：执行升级前运行状况检查

运行状况检查会在升级过程中运行，但您也可以在开始之前单独运行运行运行运行状况检查。运行状况检查会评估存储阵列的组件，以确保升级可以继续进行。

.步骤
. 打开 Unified Manager 。
. 在主视图中，选择 * 管理 * ，然后选择菜单：升级中心 [ 升级前运行状况检查 ] 。
+
此时将打开升级前运行状况检查对话框，其中列出了所有已发现的存储系统。

. 如果需要，可对列表中的存储系统进行筛选或排序，以便您可以查看当前未处于最佳状态的所有系统。
. 选中要通过运行状况检查运行的存储系统对应的复选框。
. 单击 * 开始 * 。
+
执行运行状况检查时，此进度将显示在对话框中。

. 运行状况检查完成后，您可以单击每行右侧的省略号（ ... ）以查看更多信息并执行其他任务。
+

NOTE: 如果任何阵列未通过运行状况检查，您可以跳过该特定阵列并继续对其他阵列进行升级，也可以停止整个过程并对未通过的阵列进行故障排除。





== 第 2 步：从支持站点下载软件文件

在此步骤中，您将转到 NetApp 支持站点将新的可下载软件包（ DLP ）软件文件保存到管理主机系统中。

.步骤
. 如果存储阵列仅包含一个控制器或未使用多路径驱动程序，请停止存储阵列的 I/O 活动，以防止出现应用程序错误。如果存储阵列有两个控制器，并且您安装了多路径驱动程序，则无需停止 I/O 活动。
. 在 Unified Manager 的主视图中，选择 * 管理 * ，然后选择要升级的一个或多个存储阵列。
. 选择菜单：升级中心 [ 升级 SANtricity 操作系统软件 ] 。
+
此时将显示升级 SANtricity OS 软件页面。

. 从 NetApp 支持站点将最新的 SANtricity OS 软件包下载到您的本地计算机。
+
.. 单击 * 将新文件添加到软件存储库 * 。
.. 单击链接以查找最新的 * SANtricity OS Downloads* 。
.. 单击 * 下载最新版本 * 链接。
.. 按照其余说明将 SANtricity 操作系统文件和 NVSRAM 文件下载到本地计算机。


+

NOTE: 8.42 及更高版本需要使用数字签名固件。如果您尝试下载未签名的固件，则会显示一个错误，并中止下载。





== 第 3 步：将软件文件传输到控制器

您可以将 SANtricity 操作系统软件文件和 NVSRAM 文件加载到存储库中，以便 Unified Manager 升级中心可以访问该文件。


CAUTION: 数据丢失风险或存储阵列损坏风险—升级期间，请勿更改存储阵列。为存储阵列供电。

.步骤
. 在 Unified Manager 的主视图中，选择 * 管理 * ，然后选择要升级的一个或多个存储阵列。
. 选择菜单：升级中心 [ 升级 SANtricity 操作系统软件 ] 。
+
此时将显示升级 SANtricity OS 软件页面。

. 从 NetApp 支持站点将最新的 SANtricity OS 软件包下载到您的本地计算机。
+
.. 单击 * 将新文件添加到软件存储库 * 。
.. 单击链接以查找最新的 * SANtricity OS Downloads* 。
.. 单击 * 下载最新版本 * 链接。
.. 按照其余说明将 SANtricity 操作系统文件和 NVSRAM 文件下载到本地计算机。


+

NOTE: 8.42 及更高版本需要使用数字签名固件。如果您尝试下载未签名的固件，则会显示一个错误，并中止下载。

. 选择要用于升级控制器的操作系统软件文件和 NVSRAM 文件：
+
.. 从 * 选择 SANtricity OS 软件文件 * 下拉列表中，选择下载到本地计算机的操作系统文件。
+
如果有多个可用文件，则这些文件将从最新日期到最旧日期进行排序。

+

NOTE: 软件存储库列出了与 Web 服务代理关联的所有软件文件。如果未看到要使用的文件，可以单击链接 * 将新文件添加到软件存储库 * ，以浏览到要添加的操作系统文件所在的位置。

.. 从 * 选择 NVSRAM 文件 * 下拉列表中，选择要使用的控制器文件。
+
如果有多个文件，则这些文件将从最新日期到最旧日期进行排序。



. 在兼容存储阵列表中，查看与选定操作系统软件文件兼容的存储阵列，然后选择要升级的阵列。
+
** 默认情况下，您在 " 管理 " 视图中选择的存储阵列以及与选定固件文件兼容的存储阵列将在 " 兼容存储阵列 " 表中选择。
** 无法使用选定固件文件更新的存储阵列在兼容存储阵列表中不可选择，如状态 * 不兼容 * 所示。


. （可选）要在不激活软件文件的情况下将其传输到存储阵列，请选中 * 将操作系统软件传输到存储阵列，将其标记为暂存并稍后激活 * 复选框。
. 单击 * 开始 * 。
. 根据您选择现在激活还是稍后激活，执行以下操作之一：
+
** 键入 * 传输 * 确认要在选定升级的阵列上传输建议的操作系统软件版本，然后单击 * 传输 * 。
+
要激活已传输的软件，请选择菜单：升级中心 [ 激活暂存操作系统软件 ] 。

** 键入 * 升级 * 确认要在选定升级的阵列上传输并激活建议的操作系统软件版本，然后单击 * 升级 * 。
+
系统会将软件文件传输到您选择升级的每个存储阵列，然后通过启动重新启动来激活该文件。



+
升级操作期间会执行以下操作：

+
** 升级前运行状况检查会在升级过程中运行。升级前运行状况检查会评估所有存储阵列组件，以确保升级可以继续进行。
** 如果存储阵列的任何运行状况检查失败，升级将停止。您可以单击省略号（ ... ）并选择 * 保存日志 * 以查看错误。您还可以选择覆盖运行状况检查错误，然后单击 * 继续 * 继续升级。
** 您可以在升级前运行状况检查后取消升级操作。


. （可选）升级完成后，您可以通过单击省略号（ ... ）并选择 * 保存日志 * 来查看为特定存储阵列升级的内容列表。
+
此文件将保存在浏览器的 "Downloads" 文件夹中，名为``upgrade_log-<date>.json`` 。





== 第 4 步：激活暂存软件文件（可选）

您可以选择立即激活软件文件，也可以等到更方便的时间再激活。此操作步骤假定您稍后选择激活此软件文件。


NOTE: 激活过程启动后，您无法停止它。

.步骤
. 在 Unified Manager 的主视图中，选择 * 管理 * 。如有必要，单击状态列对状态为 "OS Upgrade （ waiting activation ） " 的所有存储阵列进行排序。
. 选择要为其激活软件的一个或多个存储阵列，然后选择菜单：升级中心 [ 激活暂存操作系统软件 ] 。
+
升级操作期间会执行以下操作：

+
** 在激活过程中会运行升级前运行状况检查。升级前运行状况检查会评估所有存储阵列组件，以确保激活可以继续进行。
** 如果存储阵列的任何运行状况检查失败，则激活将停止。您可以单击省略号（ ... ）并选择 * 保存日志 * 以查看错误。您也可以选择覆盖运行状况检查错误，然后单击 * 继续 * 继续进行激活。
** 您可以在升级前运行状况检查后取消激活操作。成功完成升级前运行状况检查后，将激活。激活所需的时间取决于您的存储阵列配置以及要激活的组件。


. （可选）激活完成后，您可以通过单击省略号（ ... ）并选择 * 保存日志 * 来查看为特定存储阵列激活的内容列表。
+
此文件将保存在浏览器的 "Downloads" 文件夹中，名称为 `active_log-<date>.json` 。



控制器软件升级已完成。您可以恢复正常操作。
