---
permalink: upgrade-santricity/upgrade-drive-firmware-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, SANtricity, drive firmware, upgrade SANtricity, upgrade OS, upgrade E-Series, upgrade firmware, upgrading, upgrade IOM firmware, upgrade NVSRAM, upgrade controller 
summary: 您可以升级驱动器的固件，以确保具有所有最新功能和错误修复。 
---
= 升级驱动器固件
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
按照此操作步骤升级驱动器固件，以确保您拥有所有最新功能和修复。



== 第 1 步：下载驱动器固件文件

在此步骤中，您将转到 NetApp 支持站点将驱动器固件文件下载到管理客户端。

.步骤
. 在 SANtricity 系统管理器中，选择菜单： Support[ 升级中心 ] 。
. 在驱动器固件升级下，单击 * NetApp 支持 * 并登录到 NetApp 支持站点。
. 在支持站点中，单击 * 下载 * 选项卡，然后选择 * 磁盘驱动器和固件列表 * 。
. 选择 * E 系列和 EF 系列磁盘固件。 *
. 按照屏幕上的说明下载文件。




== 第 2 步：开始升级驱动器固件

在此步骤中，您将升级驱动器的固件。

.开始之前
* 使用磁盘到磁盘备份，卷副本（到不受计划的固件升级影响的卷组）或远程镜像备份数据。
* 确保存储阵列处于最佳状态。
* 确保所有驱动器均处于最佳状态。
* 确保存储阵列上未运行任何配置更改。
* 请了解，如果驱动器只能脱机升级，则与驱动器关联的所有卷的 I/O 活动将停止。


.步骤
. 从 System Manager 升级中心（菜单： Support[ 升级中心 ] ）中，从 " 驱动器固件升级 " 部分中单击 * 开始升级 * 。
+
此时将显示一个对话框，其中列出了当前正在使用的驱动器固件文件。

. 提取（解压缩）从支持站点下载的文件。
. 单击 * 浏览 * ，然后选择从支持站点下载的新驱动器固件文件。
+
驱动器固件文件的文件名类似于 `D HUC101212CS600_30602291_MS01_2800_0002` ，扩展名为 ` 。 lp` 。

+
您最多可以选择四个驱动器固件文件，一次一个。如果多个驱动器固件文件与同一驱动器兼容，则会收到文件冲突错误。确定要用于升级的驱动器固件文件，然后删除另一个驱动器固件文件。

. 单击 * 下一步 * 。
+
此时将显示选择驱动器对话框，其中列出了可使用选定文件升级的驱动器。

+
仅显示兼容的驱动器。

+
为驱动器选择的固件将显示在 * 建议的固件 * 信息区域中。如果必须更改固件，请单击 * 返回 * 以返回上一个对话框。

. 选择要执行的升级类型：
+
** * 联机（默认） * —显示存储阵列正在处理 I/O 时可支持固件下载 _FIRMWARE 的驱动器。选择此升级方法时，不必停止使用这些驱动器对关联卷的 I/O 。在存储阵列处理这些驱动器的 I/O 时，这些驱动器一次升级一个。
** * 脱机（并行） * - 显示在使用驱动器的任何卷上的所有 I/O 活动均已停止时可以支持固件下载 _only 的驱动器。选择此升级方法时，必须停止使用要升级的驱动器的任何卷上的所有 I/O 活动。不具有冗余的驱动器必须作为脱机操作进行处理。此要求包括与 SSD 缓存关联的任何驱动器， RAID 0 卷组或任何已降级的池或卷组。脱机（并行）升级通常比联机（默认）方法要快。


. 在表的第一列中，选择要升级的一个或多个驱动器。
. 单击 * 开始 * ，然后确认您要执行此操作。
+
如果需要停止升级，请单击 * 停止 * 。当前正在进行的所有固件下载均已完成。已取消所有尚未启动的固件下载。

+

CAUTION: 停止驱动器固件升级可能会导致数据丢失或驱动器不可用。

. （可选）要查看已升级内容的列表，请单击 * 保存日志 * 。
+
此文件将保存在浏览器的 "Downloads" 文件夹中，名为 `drive_upgrade_log-timestamp.txt` 。

. 如果在升级操作步骤期间出现以下任何错误，请采取适当的建议操作。
+
|===
| 如果遇到此固件下载错误 ... | 然后执行以下操作 ... 


 a| 
** 已分配的驱动器出现故障

 a| 
出现此故障的一个原因可能是驱动器没有相应的签名。确保受影响的驱动器为授权驱动器。有关详细信息，请联系技术支持。

更换驱动器时，请确保更换驱动器的容量等于或大于要更换的故障驱动器。

您可以在存储阵列接收 I/O 时更换故障驱动器



 a| 
检查存储阵列
 a| 
** 确保已为每个控制器分配 IP 地址。
** 确保连接到控制器的所有缆线均未损坏。
** 确保所有缆线均已紧密连接。




 a| 
集成热备用驱动器
 a| 
必须先更正此错误情况，然后才能升级固件。启动 System Manager 并使用 Recovery Guru 解决此问题。



 a| 
卷组不完整
 a| 
如果一个或多个卷组或磁盘池不完整，则必须更正此错误情况，然后才能升级固件。启动 System Manager 并使用 Recovery Guru 解决此问题。



 a| 
当前在任何卷组上运行的独占操作（后台介质 / 奇偶校验扫描除外）
 a| 
如果正在执行一个或多个独占操作，则必须先完成这些操作，然后才能升级固件。使用 System Manager 监控操作进度。



 a| 
缺少卷
 a| 
您必须先更正缺少的卷情况，然后才能升级固件。启动 System Manager 并使用 Recovery Guru 解决此问题。



 a| 
任一控制器处于非最佳状态
 a| 
其中一个存储阵列控制器需要注意。必须先更正此情况，然后才能升级固件。启动 System Manager 并使用 Recovery Guru 解决此问题。



 a| 
控制器对象图形之间的存储分区信息不匹配
 a| 
验证控制器上的数据时出错。请联系技术支持以解决此问题描述。



 a| 
SPM 验证数据库控制器检查失败
 a| 
控制器上发生存储分区映射数据库错误。请联系技术支持以解决此问题描述。



 a| 
配置数据库验证（如果存储阵列的控制器版本支持）
 a| 
控制器上发生配置数据库错误。请联系技术支持以解决此问题描述。



 a| 
与 Mel 相关的检查
 a| 
请联系技术支持以解决此问题描述。



 a| 
过去 7 天报告了 10 个以上的 DDN 信息性或严重 MEL 事件
 a| 
请联系技术支持以解决此问题描述。



 a| 
过去 7 天报告了超过 2 页 2C 的严重 MEL 事件
 a| 
请联系技术支持以解决此问题描述。



 a| 
过去 7 天报告了 2 个以上的 " 降级驱动器通道 " 严重 MEL 事件
 a| 
请联系技术支持以解决此问题描述。



 a| 
过去 7 天内超过 4 个关键 MEL 条目
 a| 
请联系技术支持以解决此问题描述。

|===


驱动器固件升级已完成。您可以恢复正常操作。
