---
permalink: web-services-proxy/array-intro-concept.html 
sidebar: sidebar 
keywords: Web Services, WSP, SANtricity API, discover storage WSP, 
summary: 要管理网络中的存储系统，您必须先发现它们，然后将其添加到管理列表中。 
---
= 使用 Web 服务代理管理存储系统
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要管理网络中的存储系统，您必须先发现它们，然后将其添加到管理列表中。



== 发现存储系统

您可以设置自动发现或手动发现存储系统。



=== 自动发现存储系统

您可以通过修改 wsconfig.xml 文件中的设置来指定在网络中自动发现存储系统。默认情况下， IPv6 自动发现处于禁用状态， IPv4 处于启用状态。

要添加存储系统，只需提供一个管理 IP 或 DNS 地址即可。如果未配置路径或路径已配置且可轮换，则服务器会自动发现所有管理路径。


NOTE: 如果在建立初始连接后尝试使用 IPv6 协议自动从控制器配置发现存储系统，则此过程可能会失败。失败的可能原因包括：在存储系统上启用 IP 地址转发或 IPv6 期间出现问题，但服务器上未启用 IPv6 。

在启用 IPv6 发现设置之前，请确认您的基础架构支持与存储系统的 IPv6 连接，以缓解任何连接问题。

.步骤
. 打开 wsconfig.xml 文件，该文件位于：
+
** （ Windows ）— C ： \Program Files\NetApp\SANtricity Web 服务代理
** （ Linux ）— /opt/netapp/SANtricity web_services_proxy


. 在自动发现字符串中，根据需要将设置从 `true` 更改为 `false` 。请参见以下示例。
+
[listing]
----
<env key="autodiscover.ipv6.enable">true</env>
----
+

NOTE: 如果配置了路径，但未对路径进行配置，使服务器能够路由到地址，则会发生间歇性连接错误。如果您无法将 IP 地址设置为可从主机路由，请关闭自动发现（将设置更改为 `false` ）。

. 保存文件。




=== 使用 API 端点发现和添加存储系统

您可以使用 API 端点发现存储系统并将其添加到受管列表中。此操作步骤会在存储系统和 API 之间创建管理连接。


NOTE: 此任务介绍如何使用 REST API 发现和添加存储系统，以便您可以在交互式 API 文档中管理这些系统。但是，您可能需要改用 Unified Manager 来管理存储系统，它提供了一个易于使用的界面。有关详细信息，请参见 Unified Manager 提供的联机帮助。

对于 SANtricity 版本为 11.30 及更高版本的存储系统，必须在 SANtricity System Manager 界面中为 SYMBOL 启用原有管理界面。否则，发现端点将失败。要查找此设置，请打开 System Manager ，然后转到菜单：设置 [ 系统 > 其他设置 > 更改管理界面 ] 。

.步骤
. 登录到 link:install-login-task.html["交互式 API 文档"]。
. 发现存储系统，如下所示：
+
.. 在 API 文档中，确保在下拉列表中选择了 * V2 * ，然后展开 * 存储系统 * 类别。
.. 单击 * 发布： /discover* 端点，然后单击 * 试用 * 。
.. 按照表中所述输入参数。
+
|===


 a| 
startIP

endIP
 a| 
将字符串替换为网络中一个或多个存储系统的起始和结束 IP 地址范围。



 a| 
使用代理
 a| 
将此值设置为：

*** true = 使用带内代理进行网络扫描。
*** false = 不要在网络扫描中使用带内代理。




 a| 
连接超时
 a| 
输入在连接超时之前允许扫描的秒数。



 a| 
maxPortsToUse.
 a| 
输入用于网络扫描的最大端口数。

|===
.. 单击 * 执行 * 。
+

NOTE: API 操作在不提示用户的情况下执行。

+
发现过程在后台运行。

.. 确保此代码返回 202 。
.. 在 * 响应正文 * 下，找到为 requestId 返回的值。您需要此请求 ID 才能在下一步中查看结果。


. 查看发现结果，如下所示：
+
.. 单击 * 获取： /discover星 * 端点，然后单击 * 试用 * 。
.. 输入上一步中的请求 ID 。如果将 * 请求 ID* 留空，则端点默认为上次执行的请求 ID 。
.. 单击 * 执行 * 。
.. 确保此代码返回 200 。
.. 在响应正文中，找到您的请求 ID 以及 storageSystems 的字符串。这些字符串类似于以下示例：
+
[listing]
----
"storageSystems": [
    {
      "serialNumber": "123456789",
      "wwn": "000A011000AF0000000000001A0C000E",
      "label": "EF570_Array",
      "firmware": "08.41.10.01",
      "nvsram": "N5700-841834-001",
      "ipAddresses": [
        "10.xxx.xx.213",
        "10.xxx.xx.214"
      ],
----
.. 记下 WWN ，标签和 IP 地址的值。您需要这些信息才能执行下一步。


. 添加存储系统，如下所示：
+
.. 单击 * 发布： /storage-system* 端点，然后单击 * 试用 * 。
.. 按照表中所述输入参数。
+
|===


 a| 
id
 a| 
为此存储系统输入一个唯一名称。您可以输入标签（显示在 GET ： /discovery 的响应中），但名称可以是您选择的任何字符串。如果不为此字段提供值， Web 服务将自动分配唯一标识符。



 a| 
控制器插件
 a| 
输入 GET ： /discovery 响应中显示的 IP 地址。对于双控制器，请使用逗号分隔 IP 地址。例如：

` "IP 地址 1" ， "IP 地址 2"`



 a| 
验证
 a| 
输入 `true` ，以便您可以收到 Web 服务可以连接到存储系统的确认消息。



 a| 
password
 a| 
输入存储系统的管理密码。



 a| 
WWN
 a| 
输入存储系统的 WWN （显示在对 GET ： /discovery 的响应中）。

|===
.. 删除 ` enabletrace" ： true` 后的所有字符串，使整个字符串集与以下示例类似：
+
[listing]
----
{
  "id": "EF570_Array",
  "controllerAddresses": [
    "Controller-A-Mgmt-IP","Controller-B-Mgmt_IP"
  ],
  "validate":true,
  "password": "array-admin-password",
  "wwn": "000A011000AF0000000000001A0C000E",
  "enableTrace": true
}
----
.. 单击 * 执行 * 。
.. 确保代码响应为 201 ，表示端点已成功执行。
+
已将 * 发布： /storage-systems* 端点排队。您可以在下一步中使用 * 获取： /storage-systems* 端点查看结果。



. 确认添加列表，如下所示：
+
.. 单击 * 获取： /storage-system* 端点。
+
不需要任何参数。

.. 单击 * 执行 * 。
.. 确保代码响应为 200 ，表示端点已成功执行。
.. 在响应正文中，查找存储系统详细信息。返回的值表示已成功将其添加到受管阵列列表中，类似于以下示例：
+
[listing]
----
[
  {
    "id": "EF570_Array",
    "name": "EF570_Array",
    "wwn": "000A011000AF0000000000001A0C000E",
    "passwordStatus": "valid",
    "passwordSet": true,
    "status": "optimal",
    "ip1": "10.xxx.xx.213",
    "ip2": "10.xxx.xx.214",
    "managementPaths": [
      "10.xxx.xx.213",
      "10.xxx.xx.214"
  ]
  }
]
----






== 纵向扩展受管存储系统的数量

默认情况下， API 最多可以管理 100 个存储系统。如果您需要管理更多，则必须满足服务器的内存要求。

服务器设置为使用 512 MB 的内存。对于网络中每增加 100 个存储系统，请在该数量中增加 250 MB 。请勿添加比物理内存更多的内存。为您的操作系统和其他应用程序留出足够的额外空间。


NOTE: 默认缓存大小为 8 ， 192 个事件。对于每 8 ， 192 个事件， MEL 事件缓存的大致数据使用量为 1 MB 。因此，通过保留默认值，存储系统的缓存使用量应大约为 1 MB 。


NOTE: 除了内存之外，代理还会对每个存储系统使用网络端口。Linux 和 Windows 将网络端口视为文件句柄。作为一项安全措施，大多数操作系统都会限制进程或用户一次可以打开的打开文件句柄的数量。尤其是在 Linux 环境中，如果将开放式 TCP 连接视为文件句柄，则 Web 服务代理很容易超过此限制。由于此修复程序取决于系统，因此您应参考操作系统的文档，了解如何提高此值。

.步骤
. 执行以下操作之一：
+
** 在 Windows 上，转到 appserver64.init 文件。找到行 `vmarg.3=-Xmx512M`
** 在 Linux 上，转到 webserver.sh 文件。找到行 `java_options="-Xmx512M"`


. 要增加内存，请将 `512` 更换为所需的内存（以 MB 为单位）。
. 保存文件。

