---
permalink: web-services-proxy/install-reqs-task.html 
sidebar: sidebar 
keywords: installation, download, install proxy, 
summary: Web 服务代理的安装和升级要求以及注意事项。 
---
= 查看安装和升级要求
:icons: font
:imagesdir: ../media/


[role="lead"]
在安装 Web 服务代理之前，请查看安装要求和升级注意事项。



== 安装要求

您可以在 Windows 或 Linux 主机系统上安装和配置 Web 服务代理。

代理安装包括以下要求。

|===
| 要求 | Description 


 a| 
主机名限制
 a| 
请确保计划安装 Web 服务代理的服务器的主机名仅包含 ASCII 字母，数字和连字符（ - ）。此要求是由于 Java keytool 的限制所致，该工具用于为服务器生成自签名证书。如果服务器的主机名包含任何其他字符，例如下划线（ _ ），则 Webserver 将无法在安装后启动。



 a| 
操作系统
 a| 
您可以在以下操作系统上安装代理：

* Linux
* Windows


有关操作系统和固件兼容性的完整列表，请参见 http://mysupport.netapp.com/matrix["NetApp 互操作性表工具"^]。



 a| 
Linux ：其他注意事项
 a| 
要使 Web 服务器正常运行，需要使用 Linux 标准基础库（ init-function ）。您必须为操作系统安装 lsb/insServ 软件包。有关详细信息，请参阅自述文件的 " 所需的其他软件包 " 部分。



 a| 
多个实例
 a| 
一个服务器上只能安装一个 Web 服务代理实例；但是，您可以在网络中的多个服务器上安装该代理。



 a| 
容量规划
 a| 
Web 服务代理需要足够的空间来进行日志记录。确保您的系统满足以下可用磁盘空间要求：

* 所需安装空间— 275 MB
* 最小日志记录空间— 200 MB
* 系统内存— 2 GB ；堆空间默认为 1 GB


您可以使用磁盘空间监控工具验证可用于永久性存储和日志记录的磁盘驱动器空间。



 a| 
许可证
 a| 
Web 服务代理是一款免费的独立产品，不需要许可证密钥。但是，适用的版权和服务条款仍适用。如果要在图形或控制台模式下安装代理，则必须接受最终用户许可协议（ EULA ）。

|===


== 升级注意事项

如果要从先前版本升级，请注意，某些项目会保留或删除。

* 对于 Web 服务代理，将保留先前的配置设置。这些设置包括用户密码，所有已发现的存储系统，服务器证书，可信证书和服务器运行时配置。
* 对于 Unified Manager ，先前加载在存储库中的所有 SANtricity OS 文件都会在升级期间删除。

