---
permalink: web-services-proxy/install-wsp-task.html 
sidebar: sidebar 
keywords: installation, download, install proxy, 
summary: 安装涉及下载文件，然后在 Linux 或 Windows 服务器上安装代理软件包。 
---
= 下载并安装 Web 服务代理文件
:icons: font
:imagesdir: ../media/


[role="lead"]
安装涉及下载文件，然后在 Linux 或 Windows 服务器上安装代理软件包。



== 下载 Web 服务代理文件

您可以从 NetApp 支持站点的软件下载页面下载安装文件和自述文件。

下载包包括 Web 服务代理和 Unified Manager 界面。

.步骤
. 转至 https://mysupport.netapp.com/site/downloads["NetApp 支持—下载"^]。
. 选择 * E 系列 SANtricity Web 服务代理 * 。
. 按照说明下载文件。请确保为您的服务器选择正确的下载包（例如，适用于 Windows 的 exe ；适用于 Linux 的 BIN 或 RPM ）。
. 将安装文件下载到要安装代理和 Unified Manager 的服务器。




== 在 Windows 或 Linux 服务器上安装

您可以使用以下三种模式之一（图形，控制台或静默）或 RPM 文件（仅限 Linux ）安装 Web 服务代理和 Unified Manager 。

.开始之前
* link:install-reqs-task.html["查看安装要求"]。
* 确保已将正确的安装文件（适用于 Windows 的 exe ；适用于 Linux 的 BIN ）下载到要安装代理和 Unified Manager 的服务器。




=== 图形模式安装

您可以在图形模式下为 Windows 或 Linux 运行安装。在图形模式下，系统会在 Windows 模式界面中显示提示。

.步骤
. 访问下载安装文件的文件夹。
. 启动 Windows 或 Linux 安装，如下所示：
+
** Windows —双击安装文件：
+
`santriciity_webservice-windows_x64-nn.nnn.nnnn.exe`

** Linux —运行以下命令： `santriciity_webservice-linux_x64-nn.nnn.nn.nnn.bin`
+
在上述文件名中， `nn.nn.nn.nnnn` 表示版本号。



+
安装过程将启动，此时将显示 NetApp SANtricity Web 服务代理 + Unified Manager 启动屏幕。

. 按照屏幕上的提示进行操作。
+
在安装期间，系统会提示您启用多项功能并输入一些配置参数。如有必要，您可以稍后在配置文件中更改其中任何一个选项。

. 出现 Webserver started 消息时，单击 * 确定 * 完成安装。
+
此时将显示安装完成对话框。

. 如果要启动 Unified Manager 或交互式 API 文档，请单击复选框，然后单击 * 完成 * 。




=== 控制台模式安装

您可以在控制台模式下为 Windows 或 Linux 运行安装。在控制台模式下，终端窗口中会显示提示。

.步骤
. 运行以下命令： ` <install filename> -i console`
+
在上述命令中， ` <install filename>` 表示您下载的代理安装文件的名称（例如： `santriciity_webservice-windows_x64-n.nn.nn.nnnnn.exe` ）。

+

NOTE: 要在安装过程中随时取消安装，请在命令提示符处键入 `quit` 。

+
安装过程将开始，并显示启动安装程序 - 简介消息。

. 按照屏幕上的提示进行操作。
+
在安装期间，系统会提示您启用多项功能并输入一些配置参数。如有必要，您可以稍后在配置文件中更改其中任何一个选项。

. 安装完成后，按 * 输入 * 退出安装程序。




=== 静默模式安装

您可以在静默模式下为 Windows 或 Linux 运行安装。在静默模式下，终端窗口中不会显示任何返回消息或脚本。

.步骤
. 运行以下命令： ` <install filename> -i silent`
+
在上述命令中， ` <install filename>` 表示您下载的代理安装文件的名称（例如： `santriciity_webservice-windows_x64-n.nn.nn.nnnnn.exe` ）。

. 按 * 输入 * 。
+
安装过程可能需要几分钟才能完成。成功安装后，终端窗口将显示命令提示符。





=== rpm 命令安装（仅限 Linux ）

对于与 RPM 软件包管理系统兼容的 Linux 系统，您可以使用可选的 RPM 文件安装 Web 服务代理。

.步骤
. 将 RPM 文件下载到要安装代理和 Unified Manager 的服务器。
. 打开终端窗口。
. 输入以下命令：
+
`rpm -u SANtricity webservices_nnn 。 nn 。 nnnn-1.6461.rpm`

+

NOTE: 在上述命令中， `nn.nn.nn.nnnn` 表示版本号。

+
安装过程可能需要几分钟才能完成。成功安装后，终端窗口将显示命令提示符。


